import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateMaranhao1744495182259
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdMaranhao = 'adb2b4fa-e63a-4433-9cb0-bbdc3b33d0b5';

    await queryRunner.query(`
       INSERT INTO cities(name, state_id) VALUES
        ('Açailândia', '${stateIdMaranhao}'),
        ('Afonso Cunha', '${stateIdMaranhao}'),
        ('Água Doce do Maranhão', '${stateIdMaranhao}'),
        ('Alcântara', '${stateIdMaranhao}'),
        ('Aldeias Altas', '${stateIdMaranhao}'),
        ('Altamira do Maranhão', '${stateIdMaranhao}'),
        ('Alto Alegre do Maranhão', '${stateIdMaranhao}'),
        ('Alto Alegre do Pindaré', '${stateIdMaranhao}'),
        ('Alto Parnaíba', '${stateIdMaranhao}'),
        ('Amapá do Maranhão', '${stateIdMaranhao}'),
        ('Amarante do Maranhão', '${stateIdMaranhao}'),
        ('Anajatuba', '${stateIdMaranhao}'),
        ('Anapurus', '${stateIdMaranhao}'),
        ('Apicum-Açu', '${stateIdMaranhao}'),
        ('Araguanã', '${stateIdMaranhao}'),
        ('Araioses', '${stateIdMaranhao}'),
        ('Arame', '${stateIdMaranhao}'),
        ('Arari', '${stateIdMaranhao}'),
        ('Axixá', '${stateIdMaranhao}'),
        ('Bacabal', '${stateIdMaranhao}'),
        ('Bacabeira', '${stateIdMaranhao}'),
        ('Bacuri', '${stateIdMaranhao}'),
        ('Bacurituba', '${stateIdMaranhao}'),
        ('Balsas', '${stateIdMaranhao}'),
        ('Barão de Grajaú', '${stateIdMaranhao}'),
        ('Barra do Corda', '${stateIdMaranhao}'),
        ('Barreirinhas', '${stateIdMaranhao}'),
        ('Bela Vista do Maranhão', '${stateIdMaranhao}'),
        ('Belágua', '${stateIdMaranhao}'),
        ('Benedito Leite', '${stateIdMaranhao}'),
        ('Bequimão', '${stateIdMaranhao}'),
        ('Bernardo do Mearim', '${stateIdMaranhao}'),
        ('Boa Vista do Gurupi', '${stateIdMaranhao}'),
        ('Bom Jardim', '${stateIdMaranhao}'),
        ('Bom Jesus das Selvas', '${stateIdMaranhao}'),
        ('Bom Lugar', '${stateIdMaranhao}'),
        ('Brejo', '${stateIdMaranhao}'),
        ('Brejo de Areia', '${stateIdMaranhao}'),
        ('Buriti', '${stateIdMaranhao}'),
        ('Buriti Bravo', '${stateIdMaranhao}'),
        ('Buriticupu', '${stateIdMaranhao}'),
        ('Buritirana', '${stateIdMaranhao}'),
        ('Cachoeira Grande', '${stateIdMaranhao}'),
        ('Cajapió', '${stateIdMaranhao}'),
        ('Cajari', '${stateIdMaranhao}'),
        ('Campestre do Maranhão', '${stateIdMaranhao}'),
        ('Cândido Mendes', '${stateIdMaranhao}'),
        ('Cantanhede', '${stateIdMaranhao}'),
        ('Capinzal do Norte', '${stateIdMaranhao}'),
        ('Carolina', '${stateIdMaranhao}'),
        ('Carutapera', '${stateIdMaranhao}'),
        ('Caxias', '${stateIdMaranhao}'),
        ('Cedral', '${stateIdMaranhao}'),
        ('Central do Maranhão', '${stateIdMaranhao}'),
        ('Centro do Guilherme', '${stateIdMaranhao}'),
        ('Centro Novo do Maranhão', '${stateIdMaranhao}'),
        ('Chapadinha', '${stateIdMaranhao}'),
        ('Cidelândia', '${stateIdMaranhao}'),
        ('Codó', '${stateIdMaranhao}'),
        ('Coelho Neto', '${stateIdMaranhao}'),
        ('Colinas', '${stateIdMaranhao}'),
        ('Conceição do Lago-Açu', '${stateIdMaranhao}'),
        ('Coroatá', '${stateIdMaranhao}'),
        ('Cururupu', '${stateIdMaranhao}'),
        ('Davinópolis', '${stateIdMaranhao}'),
        ('Dom Pedro', '${stateIdMaranhao}'),
        ('Duque Bacelar', '${stateIdMaranhao}'),
        ('Esperantinópolis', '${stateIdMaranhao}'),
        ('Estreito', '${stateIdMaranhao}'),
        ('Feira Nova do Maranhão', '${stateIdMaranhao}'),
        ('Fernando Falcão', '${stateIdMaranhao}'),
        ('Formosa da Serra Negra', '${stateIdMaranhao}'),
        ('Fortaleza dos Nogueiras', '${stateIdMaranhao}'),
        ('Fortuna', '${stateIdMaranhao}'),
        ('Godofredo Viana', '${stateIdMaranhao}'),
        ('Gonçalves Dias', '${stateIdMaranhao}'),
        ('Governador Archer', '${stateIdMaranhao}'),
        ('Governador Edison Lobão', '${stateIdMaranhao}'),
        ('Governador Eugênio Barros', '${stateIdMaranhao}'),
        ('Governador Luiz Rocha', '${stateIdMaranhao}'),
        ('Governador Newton Bello', '${stateIdMaranhao}'),
        ('Governador Nunes Freire', '${stateIdMaranhao}'),
        ('Graça Aranha', '${stateIdMaranhao}'),
        ('Grajaú', '${stateIdMaranhao}'),
        ('Guimarães', '${stateIdMaranhao}'),
        ('Humberto de Campos', '${stateIdMaranhao}'),
        ('Icatu', '${stateIdMaranhao}'),
        ('Igarapé do Meio', '${stateIdMaranhao}'),
        ('Igarapé Grande', '${stateIdMaranhao}'),
        ('Imperatriz', '${stateIdMaranhao}'),
        ('Itaipava do Grajaú', '${stateIdMaranhao}'),
        ('Itapecuru Mirim', '${stateIdMaranhao}'),
        ('Itinga do Maranhão', '${stateIdMaranhao}'),
        ('Jatobá', '${stateIdMaranhao}'),
        ('Jenipapo dos Vieiras', '${stateIdMaranhao}'),
        ('João Lisboa', '${stateIdMaranhao}'),
        ('Joselândia', '${stateIdMaranhao}'),
        ('Junco do Maranhão', '${stateIdMaranhao}'),
        ('Lago da Pedra', '${stateIdMaranhao}'),
        ('Lago do Junco', '${stateIdMaranhao}'),
        ('Lago dos Rodrigues', '${stateIdMaranhao}'),
        ('Lago Verde', '${stateIdMaranhao}'),
        ('Lagoa do Mato', '${stateIdMaranhao}'),
        ('Lagoa Grande do Maranhão', '${stateIdMaranhao}'),
        ('Lajeado Novo', '${stateIdMaranhao}'),
        ('Lima Campos', '${stateIdMaranhao}'),
        ('Loreto', '${stateIdMaranhao}'),
        ('Luís Domingues', '${stateIdMaranhao}'),
        ('Magalhães de Almeida', '${stateIdMaranhao}'),
        ('Maracaçumé', '${stateIdMaranhao}'),
        ('Marajá do Sena', '${stateIdMaranhao}'),
        ('Maranhãozinho', '${stateIdMaranhao}'),
        ('Mata Roma', '${stateIdMaranhao}'),
        ('Matinha', '${stateIdMaranhao}'),
        ('Matões', '${stateIdMaranhao}'),
        ('Matões do Norte', '${stateIdMaranhao}'),
        ('Milagres do Maranhão', '${stateIdMaranhao}'),
        ('Mirador', '${stateIdMaranhao}'),
        ('Miranda do Norte', '${stateIdMaranhao}'),
        ('Mirinzal', '${stateIdMaranhao}'),
        ('Monção', '${stateIdMaranhao}'),
        ('Montes Altos', '${stateIdMaranhao}'),
        ('Morros', '${stateIdMaranhao}'),
        ('Nina Rodrigues', '${stateIdMaranhao}'),
        ('Nova Colinas', '${stateIdMaranhao}'),
        ('Nova Iorque', '${stateIdMaranhao}'),
        ('Nova Olinda do Maranhão', '${stateIdMaranhao}'),
        ('Olho d\`Água das Cunhãs', '${stateIdMaranhao}'),
        ('Olinda Nova do Maranhão', '${stateIdMaranhao}'),
        ('Paço do Lumiar', '${stateIdMaranhao}'),
        ('Palmeirândia', '${stateIdMaranhao}'),
        ('Paraibano', '${stateIdMaranhao}'),
        ('Parnarama', '${stateIdMaranhao}'),
        ('Passagem Franca', '${stateIdMaranhao}'),
        ('Pastos Bons', '${stateIdMaranhao}'),
        ('Paulino Neves', '${stateIdMaranhao}'),
        ('Paulo Ramos', '${stateIdMaranhao}'),
        ('Pedreiras', '${stateIdMaranhao}'),
        ('Pedro do Rosário', '${stateIdMaranhao}'),
        ('Penalva', '${stateIdMaranhao}'),
        ('Peri Mirim', '${stateIdMaranhao}'),
        ('Peritoró', '${stateIdMaranhao}'),
        ('Pindaré-Mirim', '${stateIdMaranhao}'),
        ('Pinheiro', '${stateIdMaranhao}'),
        ('Pio XII', '${stateIdMaranhao}'),
        ('Pirapemas', '${stateIdMaranhao}'),
        ('Poção de Pedras', '${stateIdMaranhao}'),
        ('Porto Franco', '${stateIdMaranhao}'),
        ('Porto Rico do Maranhão', '${stateIdMaranhao}'),
        ('Presidente Dutra', '${stateIdMaranhao}'),
        ('Presidente Juscelino', '${stateIdMaranhao}'),
        ('Presidente Médici', '${stateIdMaranhao}'),
        ('Presidente Sarney', '${stateIdMaranhao}'),
        ('Presidente Vargas', '${stateIdMaranhao}'),
        ('Primeira Cruz', '${stateIdMaranhao}'),
        ('Raposa', '${stateIdMaranhao}'),
        ('Riachão', '${stateIdMaranhao}'),
        ('Ribamar Fiquene', '${stateIdMaranhao}'),
        ('Rosário', '${stateIdMaranhao}'),
        ('Sambaíba', '${stateIdMaranhao}'),
        ('Santa Filomena do Maranhão', '${stateIdMaranhao}'),
        ('Santa Helena', '${stateIdMaranhao}'),
        ('Santa Inês', '${stateIdMaranhao}'),
        ('Santa Luzia', '${stateIdMaranhao}'),
        ('Santa Luzia do Paruá', '${stateIdMaranhao}'),
        ('Santa Quitéria do Maranhão', '${stateIdMaranhao}'),
        ('Santa Rita', '${stateIdMaranhao}'),
        ('Santana do Maranhão', '${stateIdMaranhao}'),
        ('Santo Amaro do Maranhão', '${stateIdMaranhao}'),
        ('Santo Antônio dos Lopes', '${stateIdMaranhao}'),
        ('São Benedito do Rio Preto', '${stateIdMaranhao}'),
        ('São Bento', '${stateIdMaranhao}'),
        ('São Bernardo', '${stateIdMaranhao}'),
        ('São Domingos do Azeitão', '${stateIdMaranhao}'),
        ('São Domingos do Maranhão', '${stateIdMaranhao}'),
        ('São Félix de Balsas', '${stateIdMaranhao}'),
        ('São Francisco do Brejão', '${stateIdMaranhao}'),
        ('São Francisco do Maranhão', '${stateIdMaranhao}'),
        ('São João Batista', '${stateIdMaranhao}'),
        ('São João do Carú', '${stateIdMaranhao}'),
        ('São João do Paraíso', '${stateIdMaranhao}'),
        ('São João do Soter', '${stateIdMaranhao}'),
        ('São João dos Patos', '${stateIdMaranhao}'),
        ('São José de Ribamar', '${stateIdMaranhao}'),
        ('São José dos Basílios', '${stateIdMaranhao}'),
        ('São Luís', '${stateIdMaranhao}'),
        ('São Luís Gonzaga do Maranhão', '${stateIdMaranhao}'),
        ('São Mateus do Maranhão', '${stateIdMaranhao}'),
        ('São Pedro da Água Branca', '${stateIdMaranhao}'),
        ('São Pedro dos Crentes', '${stateIdMaranhao}'),
        ('São Raimundo das Mangabeiras', '${stateIdMaranhao}'),
        ('São Raimundo do Doca Bezerra', '${stateIdMaranhao}'),
        ('São Roberto', '${stateIdMaranhao}'),
        ('São Vicente Ferrer', '${stateIdMaranhao}'),
        ('Satubinha', '${stateIdMaranhao}'),
        ('Senador Alexandre Costa', '${stateIdMaranhao}'),
        ('Senador La Rocque', '${stateIdMaranhao}'),
        ('Serrano do Maranhão', '${stateIdMaranhao}'),
        ('Sítio Novo', '${stateIdMaranhao}'),
        ('Sucupira do Norte', '${stateIdMaranhao}'),
        ('Sucupira do Riachão', '${stateIdMaranhao}'),
        ('Tasso Fragoso', '${stateIdMaranhao}'),
        ('Timbiras', '${stateIdMaranhao}'),
        ('Timon', '${stateIdMaranhao}'),
        ('Trizidela do Vale', '${stateIdMaranhao}'),
        ('Tufilândia', '${stateIdMaranhao}'),
        ('Tuntum', '${stateIdMaranhao}'),
        ('Turiaçu', '${stateIdMaranhao}'),
        ('Turilândia', '${stateIdMaranhao}'),
        ('Tutóia', '${stateIdMaranhao}'),
        ('Urbano Santos', '${stateIdMaranhao}'),
        ('Vargem Grande', '${stateIdMaranhao}'),
        ('Viana', '${stateIdMaranhao}'),
        ('Vila Nova dos Martírios', '${stateIdMaranhao}'),
        ('Vitória do Mearim', '${stateIdMaranhao}'),
        ('Vitorino Freire', '${stateIdMaranhao}'),
        ('Zé Doca', '${stateIdMaranhao}');
      `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdMaranhao = 'adb2b4fa-e63a-4433-9cb0-bbdc3b33d0b5';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdMaranhao}';
    `);
  }
}
