import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateRioGrandeNorte1744511980746
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdRioGrandeNorte = '3e69f59d-79ec-41eb-8de5-f14e31c2ab3e';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Acari', '${stateIdRioGrandeNorte}'),
        ('Açu', '${stateIdRioGrandeNorte}'),
        ('Afonso Bezerra', '${stateIdRioGrandeNorte}'),
        ('Água Nova', '${stateIdRioGrandeNorte}'),
        ('Alexandria', '${stateIdRioGrandeNorte}'),
        ('Almino Afonso', '${stateIdRioGrandeNorte}'),
        ('Alto do Rodrigues', '${stateIdRioGrandeNorte}'),
        ('Angicos', '${stateIdRioGrandeNorte}'),
        ('Antônio Martins', '${stateIdRioGrandeNorte}'),
        ('Apodi', '${stateIdRioGrandeNorte}'),
        ('Areia Branca', '${stateIdRioGrandeNorte}'),
        ('Arês', '${stateIdRioGrandeNorte}'),
        ('Augusto Severo', '${stateIdRioGrandeNorte}'),
        ('Baía Formosa', '${stateIdRioGrandeNorte}'),
        ('Baraúna', '${stateIdRioGrandeNorte}'),
        ('Barcelona', '${stateIdRioGrandeNorte}'),
        ('Bento Fernandes', '${stateIdRioGrandeNorte}'),
        ('Bodó', '${stateIdRioGrandeNorte}'),
        ('Bom Jesus', '${stateIdRioGrandeNorte}'),
        ('Brejinho', '${stateIdRioGrandeNorte}'),
        ('Caiçara do Norte', '${stateIdRioGrandeNorte}'),
        ('Caiçara do Rio do Vento', '${stateIdRioGrandeNorte}'),
        ('Caicó', '${stateIdRioGrandeNorte}'),
        ('Campo Redondo', '${stateIdRioGrandeNorte}'),
        ('Canguaretama', '${stateIdRioGrandeNorte}'),
        ('Caraúbas', '${stateIdRioGrandeNorte}'),
        ('Carnaúba dos Dantas', '${stateIdRioGrandeNorte}'),
        ('Carnaubais', '${stateIdRioGrandeNorte}'),
        ('Ceará-Mirim', '${stateIdRioGrandeNorte}'),
        ('Cerro Corá', '${stateIdRioGrandeNorte}'),
        ('Coronel Ezequiel', '${stateIdRioGrandeNorte}'),
        ('Coronel João Pessoa', '${stateIdRioGrandeNorte}'),
        ('Cruzeta', '${stateIdRioGrandeNorte}'),
        ('Currais Novos', '${stateIdRioGrandeNorte}'),
        ('Doutor Severiano', '${stateIdRioGrandeNorte}'),
        ('Encanto', '${stateIdRioGrandeNorte}'),
        ('Equador', '${stateIdRioGrandeNorte}'),
        ('Espírito Santo', '${stateIdRioGrandeNorte}'),
        ('Extremoz', '${stateIdRioGrandeNorte}'),
        ('Felipe Guerra', '${stateIdRioGrandeNorte}'),
        ('Fernando Pedroza', '${stateIdRioGrandeNorte}'),
        ('Florânia', '${stateIdRioGrandeNorte}'),
        ('Francisco Dantas', '${stateIdRioGrandeNorte}'),
        ('Frutuoso Gomes', '${stateIdRioGrandeNorte}'),
        ('Galinhos', '${stateIdRioGrandeNorte}'),
        ('Goianinha', '${stateIdRioGrandeNorte}'),
        ('Governador Dix-Sept Rosado', '${stateIdRioGrandeNorte}'),
        ('Grossos', '${stateIdRioGrandeNorte}'),
        ('Guamaré', '${stateIdRioGrandeNorte}'),
        ('Ielmo Marinho', '${stateIdRioGrandeNorte}'),
        ('Ipanguaçu', '${stateIdRioGrandeNorte}'),
        ('Ipueira', '${stateIdRioGrandeNorte}'),
        ('Itajá', '${stateIdRioGrandeNorte}'),
        ('Itaú', '${stateIdRioGrandeNorte}'),
        ('Jaçanã', '${stateIdRioGrandeNorte}'),
        ('Jandaíra', '${stateIdRioGrandeNorte}'),
        ('Janduís', '${stateIdRioGrandeNorte}'),
        ('Januário Cicco', '${stateIdRioGrandeNorte}'),
        ('Japi', '${stateIdRioGrandeNorte}'),
        ('Jardim de Angicos', '${stateIdRioGrandeNorte}'),
        ('Jardim de Piranhas', '${stateIdRioGrandeNorte}'),
        ('Jardim do Seridó', '${stateIdRioGrandeNorte}'),
        ('João Câmara', '${stateIdRioGrandeNorte}'),
        ('João Dias', '${stateIdRioGrandeNorte}'),
        ('José da Penha', '${stateIdRioGrandeNorte}'),
        ('Jucurutu', '${stateIdRioGrandeNorte}'),
        ('Jundiá', '${stateIdRioGrandeNorte}'),
        ('Lagoa d\`Anta', '${stateIdRioGrandeNorte}'),
        ('Lagoa de Pedras', '${stateIdRioGrandeNorte}'),
        ('Lagoa de Velhos', '${stateIdRioGrandeNorte}'),
        ('Lagoa Nova', '${stateIdRioGrandeNorte}'),
        ('Lagoa Salgada', '${stateIdRioGrandeNorte}'),
        ('Lajes', '${stateIdRioGrandeNorte}'),
        ('Lajes Pintadas', '${stateIdRioGrandeNorte}'),
        ('Lucrécia', '${stateIdRioGrandeNorte}'),
        ('Luís Gomes', '${stateIdRioGrandeNorte}'),
        ('Macaíba', '${stateIdRioGrandeNorte}'),
        ('Macau', '${stateIdRioGrandeNorte}'),
        ('Major Sales', '${stateIdRioGrandeNorte}'),
        ('Marcelino Vieira', '${stateIdRioGrandeNorte}'),
        ('Martins', '${stateIdRioGrandeNorte}'),
        ('Maxaranguape', '${stateIdRioGrandeNorte}'),
        ('Messias Targino', '${stateIdRioGrandeNorte}'),
        ('Montanhas', '${stateIdRioGrandeNorte}'),
        ('Monte Alegre', '${stateIdRioGrandeNorte}'),
        ('Monte das Gameleiras', '${stateIdRioGrandeNorte}'),
        ('Mossoró', '${stateIdRioGrandeNorte}'),
        ('Natal', '${stateIdRioGrandeNorte}'),
        ('Nísia Floresta', '${stateIdRioGrandeNorte}'),
        ('Nova Cruz', '${stateIdRioGrandeNorte}'),
        ('Olho-d\`Água do Borges', '${stateIdRioGrandeNorte}'),
        ('Ouro Branco', '${stateIdRioGrandeNorte}'),
        ('Paraná', '${stateIdRioGrandeNorte}'),
        ('Paraú', '${stateIdRioGrandeNorte}'),
        ('Parazinho', '${stateIdRioGrandeNorte}'),
        ('Parelhas', '${stateIdRioGrandeNorte}'),
        ('Parnamirim', '${stateIdRioGrandeNorte}'),
        ('Passa e Fica', '${stateIdRioGrandeNorte}'),
        ('Passagem', '${stateIdRioGrandeNorte}'),
        ('Patu', '${stateIdRioGrandeNorte}'),
        ('Pau dos Ferros', '${stateIdRioGrandeNorte}'),
        ('Pedra Grande', '${stateIdRioGrandeNorte}'),
        ('Pedra Preta', '${stateIdRioGrandeNorte}'),
        ('Pedro Avelino', '${stateIdRioGrandeNorte}'),
        ('Pedro Velho', '${stateIdRioGrandeNorte}'),
        ('Pendências', '${stateIdRioGrandeNorte}'),
        ('Pilões', '${stateIdRioGrandeNorte}'),
        ('Poço Branco', '${stateIdRioGrandeNorte}'),
        ('Portalegre', '${stateIdRioGrandeNorte}'),
        ('Porto do Mangue', '${stateIdRioGrandeNorte}'),
        ('Presidente Juscelino', '${stateIdRioGrandeNorte}'),
        ('Pureza', '${stateIdRioGrandeNorte}'),
        ('Rafael Fernandes', '${stateIdRioGrandeNorte}'),
        ('Rafael Godeiro', '${stateIdRioGrandeNorte}'),
        ('Riacho da Cruz', '${stateIdRioGrandeNorte}'),
        ('Riacho de Santana', '${stateIdRioGrandeNorte}'),
        ('Riachuelo', '${stateIdRioGrandeNorte}'),
        ('Rio do Fogo', '${stateIdRioGrandeNorte}'),
        ('Rodolfo Fernandes', '${stateIdRioGrandeNorte}'),
        ('Ruy Barbosa', '${stateIdRioGrandeNorte}'),
        ('Santa Cruz', '${stateIdRioGrandeNorte}'),
        ('Santa Maria', '${stateIdRioGrandeNorte}'),
        ('Santana do Matos', '${stateIdRioGrandeNorte}'),
        ('Santana do Seridó', '${stateIdRioGrandeNorte}'),
        ('Santo Antônio', '${stateIdRioGrandeNorte}'),
        ('São Bento do Norte', '${stateIdRioGrandeNorte}'),
        ('São Bento do Trairí', '${stateIdRioGrandeNorte}'),
        ('São Fernando', '${stateIdRioGrandeNorte}'),
        ('São Francisco do Oeste', '${stateIdRioGrandeNorte}'),
        ('São Gonçalo do Amarante', '${stateIdRioGrandeNorte}'),
        ('São João do Sabugi', '${stateIdRioGrandeNorte}'),
        ('São José de Mipibu', '${stateIdRioGrandeNorte}'),
        ('São José do Campestre', '${stateIdRioGrandeNorte}'),
        ('São José do Seridó', '${stateIdRioGrandeNorte}'),
        ('São Miguel', '${stateIdRioGrandeNorte}'),
        ('São Miguel do Gostoso', '${stateIdRioGrandeNorte}'),
        ('São Paulo do Potengi', '${stateIdRioGrandeNorte}'),
        ('São Pedro', '${stateIdRioGrandeNorte}'),
        ('São Rafael', '${stateIdRioGrandeNorte}'),
        ('São Tomé', '${stateIdRioGrandeNorte}'),
        ('São Vicente', '${stateIdRioGrandeNorte}'),
        ('Senador Elói de Souza', '${stateIdRioGrandeNorte}'),
        ('Senador Georgino Avelino', '${stateIdRioGrandeNorte}'),
        ('Serra de São Bento', '${stateIdRioGrandeNorte}'),
        ('Serra do Mel', '${stateIdRioGrandeNorte}'),
        ('Serra Negra do Norte', '${stateIdRioGrandeNorte}'),
        ('Serrinha', '${stateIdRioGrandeNorte}'),
        ('Serrinha dos Pintos', '${stateIdRioGrandeNorte}'),
        ('Severiano Melo', '${stateIdRioGrandeNorte}'),
        ('Sítio Novo', '${stateIdRioGrandeNorte}'),
        ('Taboleiro Grande', '${stateIdRioGrandeNorte}'),
        ('Taipu', '${stateIdRioGrandeNorte}'),
        ('Tangará', '${stateIdRioGrandeNorte}'),
        ('Tenente Ananias', '${stateIdRioGrandeNorte}'),
        ('Tenente Laurentino Cruz', '${stateIdRioGrandeNorte}'),
        ('Tibau', '${stateIdRioGrandeNorte}'),
        ('Tibau do Sul', '${stateIdRioGrandeNorte}'),
        ('Timbaúba dos Batistas', '${stateIdRioGrandeNorte}'),
        ('Touros', '${stateIdRioGrandeNorte}'),
        ('Triunfo Potiguar', '${stateIdRioGrandeNorte}'),
        ('Umarizal', '${stateIdRioGrandeNorte}'),
        ('Upanema', '${stateIdRioGrandeNorte}'),
        ('Várzea', '${stateIdRioGrandeNorte}'),
        ('Venha-Ver', '${stateIdRioGrandeNorte}'),
        ('Vera Cruz', '${stateIdRioGrandeNorte}'),
        ('Viçosa', '${stateIdRioGrandeNorte}'),
        ('Vila Flor', '${stateIdRioGrandeNorte}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdRioGrandeNorte = '3e69f59d-79ec-41eb-8de5-f14e31c2ab3e';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdRioGrandeNorte}';
    `);
  }
}
