import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateParana1744510806862
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdParana = '926a897b-e272-473f-8c66-6c8dc0adddab';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Abatiá', '${stateIdParana}'),
        ('Adrianópolis', '${stateIdParana}'),
        ('Agudos do Sul', '${stateIdParana}'),
        ('Almirante Tamandaré', '${stateIdParana}'),
        ('Altamira do Paraná', '${stateIdParana}'),
        ('Alto Paraíso', '${stateIdParana}'),
        ('Alto Paraná', '${stateIdParana}'),
        ('Alto Piquiri', '${stateIdParana}'),
        ('Altônia', '${stateIdParana}'),
        ('Alvorada do Sul', '${stateIdParana}'),
        ('Amaporã', '${stateIdParana}'),
        ('Ampére', '${stateIdParana}'),
        ('Anahy', '${stateIdParana}'),
        ('Andirá', '${stateIdParana}'),
        ('Ângulo', '${stateIdParana}'),
        ('Antonina', '${stateIdParana}'),
        ('Antônio Olinto', '${stateIdParana}'),
        ('Apucarana', '${stateIdParana}'),
        ('Arapongas', '${stateIdParana}'),
        ('Arapoti', '${stateIdParana}'),
        ('Arapuã', '${stateIdParana}'),
        ('Araruna', '${stateIdParana}'),
        ('Araucária', '${stateIdParana}'),
        ('Ariranha do Ivaí', '${stateIdParana}'),
        ('Assaí', '${stateIdParana}'),
        ('Assis Chateaubriand', '${stateIdParana}'),
        ('Astorga', '${stateIdParana}'),
        ('Atalaia', '${stateIdParana}'),
        ('Balsa Nova', '${stateIdParana}'),
        ('Bandeirantes', '${stateIdParana}'),
        ('Barbosa Ferraz', '${stateIdParana}'),
        ('Barra do Jacaré', '${stateIdParana}'),
        ('Barracão', '${stateIdParana}'),
        ('Bela Vista da Caroba', '${stateIdParana}'),
        ('Bela Vista do Paraíso', '${stateIdParana}'),
        ('Bituruna', '${stateIdParana}'),
        ('Boa Esperança', '${stateIdParana}'),
        ('Boa Esperança do Iguaçu', '${stateIdParana}'),
        ('Boa Ventura de São Roque', '${stateIdParana}'),
        ('Boa Vista da Aparecida', '${stateIdParana}'),
        ('Bocaiúva do Sul', '${stateIdParana}'),
        ('Bom Jesus do Sul', '${stateIdParana}'),
        ('Bom Sucesso', '${stateIdParana}'),
        ('Bom Sucesso do Sul', '${stateIdParana}'),
        ('Borrazópolis', '${stateIdParana}'),
        ('Braganey', '${stateIdParana}'),
        ('Brasilândia do Sul', '${stateIdParana}'),
        ('Cafeara', '${stateIdParana}'),
        ('Cafelândia', '${stateIdParana}'),
        ('Cafezal do Sul', '${stateIdParana}'),
        ('Califórnia', '${stateIdParana}'),
        ('Cambará', '${stateIdParana}'),
        ('Cambé', '${stateIdParana}'),
        ('Cambira', '${stateIdParana}'),
        ('Campina da Lagoa', '${stateIdParana}'),
        ('Campina do Simão', '${stateIdParana}'),
        ('Campina Grande do Sul', '${stateIdParana}'),
        ('Campo Bonito', '${stateIdParana}'),
        ('Campo do Tenente', '${stateIdParana}'),
        ('Campo Largo', '${stateIdParana}'),
        ('Campo Magro', '${stateIdParana}'),
        ('Campo Mourão', '${stateIdParana}'),
        ('Cândido de Abreu', '${stateIdParana}'),
        ('Candói', '${stateIdParana}'),
        ('Cantagalo', '${stateIdParana}'),
        ('Capanema', '${stateIdParana}'),
        ('Capitão Leônidas Marques', '${stateIdParana}'),
        ('Carambeí', '${stateIdParana}'),
        ('Carlópolis', '${stateIdParana}'),
        ('Cascavel', '${stateIdParana}'),
        ('Castro', '${stateIdParana}'),
        ('Catanduvas', '${stateIdParana}'),
        ('Centenário do Sul', '${stateIdParana}'),
        ('Cerro Azul', '${stateIdParana}'),
        ('Céu Azul', '${stateIdParana}'),
        ('Chopinzinho', '${stateIdParana}'),
        ('Cianorte', '${stateIdParana}'),
        ('Cidade Gaúcha', '${stateIdParana}'),
        ('Clevelândia', '${stateIdParana}'),
        ('Colombo', '${stateIdParana}'),
        ('Colorado', '${stateIdParana}'),
        ('Congonhinhas', '${stateIdParana}'),
        ('Conselheiro Mairinck', '${stateIdParana}'),
        ('Contenda', '${stateIdParana}'),
        ('Corbélia', '${stateIdParana}'),
        ('Cornélio Procópio', '${stateIdParana}'),
        ('Coronel Domingos Soares', '${stateIdParana}'),
        ('Coronel Vivida', '${stateIdParana}'),
        ('Corumbataí do Sul', '${stateIdParana}'),
        ('Cruz Machado', '${stateIdParana}'),
        ('Cruzeiro do Iguaçu', '${stateIdParana}'),
        ('Cruzeiro do Oeste', '${stateIdParana}'),
        ('Cruzeiro do Sul', '${stateIdParana}'),
        ('Cruzmaltina', '${stateIdParana}'),
        ('Curitiba', '${stateIdParana}'),
        ('Curiúva', '${stateIdParana}'),
        ('Diamante d\`Oeste', '${stateIdParana}'),
        ('Diamante do Norte', '${stateIdParana}'),
        ('Diamante do Sul', '${stateIdParana}'),
        ('Dois Vizinhos', '${stateIdParana}'),
        ('Douradina', '${stateIdParana}'),
        ('Doutor Camargo', '${stateIdParana}'),
        ('Doutor Ulysses', '${stateIdParana}'),
        ('Enéas Marques', '${stateIdParana}'),
        ('Engenheiro Beltrão', '${stateIdParana}'),
        ('Entre Rios do Oeste', '${stateIdParana}'),
        ('Esperança Nova', '${stateIdParana}'),
        ('Espigão Alto do Iguaçu', '${stateIdParana}'),
        ('Farol', '${stateIdParana}'),
        ('Faxinal', '${stateIdParana}'),
        ('Fazenda Rio Grande', '${stateIdParana}'),
        ('Fênix', '${stateIdParana}'),
        ('Fernandes Pinheiro', '${stateIdParana}'),
        ('Figueira', '${stateIdParana}'),
        ('Flor da Serra do Sul', '${stateIdParana}'),
        ('Floraí', '${stateIdParana}'),
        ('Floresta', '${stateIdParana}'),
        ('Florestópolis', '${stateIdParana}'),
        ('Flórida', '${stateIdParana}'),
        ('Formosa do Oeste', '${stateIdParana}'),
        ('Foz do Iguaçu', '${stateIdParana}'),
        ('Foz do Jordão', '${stateIdParana}'),
        ('Francisco Alves', '${stateIdParana}'),
        ('Francisco Beltrão', '${stateIdParana}'),
        ('General Carneiro', '${stateIdParana}'),
        ('Godoy Moreira', '${stateIdParana}'),
        ('Goioerê', '${stateIdParana}'),
        ('Goioxim', '${stateIdParana}'),
        ('Grandes Rios', '${stateIdParana}'),
        ('Guaíra', '${stateIdParana}'),
        ('Guairaçá', '${stateIdParana}'),
        ('Guamiranga', '${stateIdParana}'),
        ('Guapirama', '${stateIdParana}'),
        ('Guaporema', '${stateIdParana}'),
        ('Guaraci', '${stateIdParana}'),
        ('Guaraniaçu', '${stateIdParana}'),
        ('Guarapuava', '${stateIdParana}'),
        ('Guaraqueçaba', '${stateIdParana}'),
        ('Guaratuba', '${stateIdParana}'),
        ('Honório Serpa', '${stateIdParana}'),
        ('Ibaiti', '${stateIdParana}'),
        ('Ibema', '${stateIdParana}'),
        ('Ibiporã', '${stateIdParana}'),
        ('Icaraíma', '${stateIdParana}'),
        ('Iguaraçu', '${stateIdParana}'),
        ('Iguatu', '${stateIdParana}'),
        ('Imbaú', '${stateIdParana}'),
        ('Imbituva', '${stateIdParana}'),
        ('Inácio Martins', '${stateIdParana}'),
        ('Inajá', '${stateIdParana}'),
        ('Indianópolis', '${stateIdParana}'),
        ('Ipiranga', '${stateIdParana}'),
        ('Iporã', '${stateIdParana}'),
        ('Iracema do Oeste', '${stateIdParana}'),
        ('Irati', '${stateIdParana}'),
        ('Iretama', '${stateIdParana}'),
        ('Itaguajé', '${stateIdParana}'),
        ('Itaipulândia', '${stateIdParana}'),
        ('Itambaracá', '${stateIdParana}'),
        ('Itambé', '${stateIdParana}'),
        ('Itapejara d\`Oeste', '${stateIdParana}'),
        ('Itaperuçu', '${stateIdParana}'),
        ('Itaúna do Sul', '${stateIdParana}'),
        ('Ivaí', '${stateIdParana}'),
        ('Ivaiporã', '${stateIdParana}'),
        ('Ivaté', '${stateIdParana}'),
        ('Ivatuba', '${stateIdParana}'),
        ('Jaboti', '${stateIdParana}'),
        ('Jacarezinho', '${stateIdParana}'),
        ('Jaguapitã', '${stateIdParana}'),
        ('Jaguariaíva', '${stateIdParana}'),
        ('Jandaia do Sul', '${stateIdParana}'),
        ('Janiópolis', '${stateIdParana}'),
        ('Japira', '${stateIdParana}'),
        ('Japurá', '${stateIdParana}'),
        ('Jardim Alegre', '${stateIdParana}'),
        ('Jardim Olinda', '${stateIdParana}'),
        ('Jataizinho', '${stateIdParana}'),
        ('Jesuítas', '${stateIdParana}'),
        ('Joaquim Távora', '${stateIdParana}'),
        ('Jundiaí do Sul', '${stateIdParana}'),
        ('Juranda', '${stateIdParana}'),
        ('Jussara', '${stateIdParana}'),
        ('Kaloré', '${stateIdParana}'),
        ('Lapa', '${stateIdParana}'),
        ('Laranjal', '${stateIdParana}'),
        ('Laranjeiras do Sul', '${stateIdParana}'),
        ('Leópolis', '${stateIdParana}'),
        ('Lidianópolis', '${stateIdParana}'),
        ('Lindoeste', '${stateIdParana}'),
        ('Loanda', '${stateIdParana}'),
        ('Lobato', '${stateIdParana}'),
        ('Londrina', '${stateIdParana}'),
        ('Luiziana', '${stateIdParana}'),
        ('Lunardelli', '${stateIdParana}'),
        ('Lupionópolis', '${stateIdParana}'),
        ('Mallet', '${stateIdParana}'),
        ('Mamborê', '${stateIdParana}'),
        ('Mandaguaçu', '${stateIdParana}'),
        ('Mandaguari', '${stateIdParana}'),
        ('Mandirituba', '${stateIdParana}'),
        ('Manfrinópolis', '${stateIdParana}'),
        ('Mangueirinha', '${stateIdParana}'),
        ('Manoel Ribas', '${stateIdParana}'),
        ('Marechal Cândido Rondon', '${stateIdParana}'),
        ('Maria Helena', '${stateIdParana}'),
        ('Marialva', '${stateIdParana}'),
        ('Marilândia do Sul', '${stateIdParana}'),
        ('Marilena', '${stateIdParana}'),
        ('Mariluz', '${stateIdParana}'),
        ('Maringá', '${stateIdParana}'),
        ('Mariópolis', '${stateIdParana}'),
        ('Maripá', '${stateIdParana}'),
        ('Marmeleiro', '${stateIdParana}'),
        ('Marquinho', '${stateIdParana}'),
        ('Marumbi', '${stateIdParana}'),
        ('Matelândia', '${stateIdParana}'),
        ('Matinhos', '${stateIdParana}'),
        ('Mato Rico', '${stateIdParana}'),
        ('Mauá da Serra', '${stateIdParana}'),
        ('Medianeira', '${stateIdParana}'),
        ('Mercedes', '${stateIdParana}'),
        ('Mirador', '${stateIdParana}'),
        ('Miraselva', '${stateIdParana}'),
        ('Missal', '${stateIdParana}'),
        ('Moreira Sales', '${stateIdParana}'),
        ('Morretes', '${stateIdParana}'),
        ('Munhoz de Melo', '${stateIdParana}'),
        ('Nossa Senhora das Graças', '${stateIdParana}'),
        ('Nova Aliança do Ivaí', '${stateIdParana}'),
        ('Nova América da Colina', '${stateIdParana}'),
        ('Nova Aurora', '${stateIdParana}'),
        ('Nova Cantu', '${stateIdParana}'),
        ('Nova Esperança', '${stateIdParana}'),
        ('Nova Esperança do Sudoeste', '${stateIdParana}'),
        ('Nova Fátima', '${stateIdParana}'),
        ('Nova Laranjeiras', '${stateIdParana}'),
        ('Nova Londrina', '${stateIdParana}'),
        ('Nova Olímpia', '${stateIdParana}'),
        ('Nova Prata do Iguaçu', '${stateIdParana}'),
        ('Nova Santa Bárbara', '${stateIdParana}'),
        ('Nova Santa Rosa', '${stateIdParana}'),
        ('Nova Tebas', '${stateIdParana}'),
        ('Novo Itacolomi', '${stateIdParana}'),
        ('Ortigueira', '${stateIdParana}'),
        ('Ourizona', '${stateIdParana}'),
        ('Ouro Verde do Oeste', '${stateIdParana}'),
        ('Paiçandu', '${stateIdParana}'),
        ('Palmas', '${stateIdParana}'),
        ('Palmeira', '${stateIdParana}'),
        ('Palmital', '${stateIdParana}'),
        ('Palotina', '${stateIdParana}'),
        ('Paraíso do Norte', '${stateIdParana}'),
        ('Paranacity', '${stateIdParana}'),
        ('Paranaguá', '${stateIdParana}'),
        ('Paranapoema', '${stateIdParana}'),
        ('Paranavaí', '${stateIdParana}'),
        ('Pato Bragado', '${stateIdParana}'),
        ('Pato Branco', '${stateIdParana}'),
        ('Paula Freitas', '${stateIdParana}'),
        ('Paulo Frontin', '${stateIdParana}'),
        ('Peabiru', '${stateIdParana}'),
        ('Perobal', '${stateIdParana}'),
        ('Pérola', '${stateIdParana}'),
        ('Pérola d\`Oeste', '${stateIdParana}'),
        ('Piên', '${stateIdParana}'),
        ('Pinhais', '${stateIdParana}'),
        ('Pinhal de São Bento', '${stateIdParana}'),
        ('Pinhalão', '${stateIdParana}'),
        ('Pinhão', '${stateIdParana}'),
        ('Piraí do Sul', '${stateIdParana}'),
        ('Piraquara', '${stateIdParana}'),
        ('Pitanga', '${stateIdParana}'),
        ('Pitangueiras', '${stateIdParana}'),
        ('Planaltina do Paraná', '${stateIdParana}'),
        ('Planalto', '${stateIdParana}'),
        ('Ponta Grossa', '${stateIdParana}'),
        ('Pontal do Paraná', '${stateIdParana}'),
        ('Porecatu', '${stateIdParana}'),
        ('Porto Amazonas', '${stateIdParana}'),
        ('Porto Barreiro', '${stateIdParana}'),
        ('Porto Rico', '${stateIdParana}'),
        ('Porto Vitória', '${stateIdParana}'),
        ('Prado Ferreira', '${stateIdParana}'),
        ('Pranchita', '${stateIdParana}'),
        ('Presidente Castelo Branco', '${stateIdParana}'),
        ('Primeiro de Maio', '${stateIdParana}'),
        ('Prudentópolis', '${stateIdParana}'),
        ('Quarto Centenário', '${stateIdParana}'),
        ('Quatiguá', '${stateIdParana}'),
        ('Quatro Barras', '${stateIdParana}'),
        ('Quatro Pontes', '${stateIdParana}'),
        ('Quedas do Iguaçu', '${stateIdParana}'),
        ('Querência do Norte', '${stateIdParana}'),
        ('Quinta do Sol', '${stateIdParana}'),
        ('Quitandinha', '${stateIdParana}'),
        ('Ramilândia', '${stateIdParana}'),
        ('Rancho Alegre', '${stateIdParana}'),
        ('Rancho Alegre d\`Oeste', '${stateIdParana}'),
        ('Realeza', '${stateIdParana}'),
        ('Rebouças', '${stateIdParana}'),
        ('Renascença', '${stateIdParana}'),
        ('Reserva', '${stateIdParana}'),
        ('Reserva do Iguaçu', '${stateIdParana}'),
        ('Ribeirão Claro', '${stateIdParana}'),
        ('Ribeirão do Pinhal', '${stateIdParana}'),
        ('Rio Azul', '${stateIdParana}'),
        ('Rio Bom', '${stateIdParana}'),
        ('Rio Bonito do Iguaçu', '${stateIdParana}'),
        ('Rio Branco do Ivaí', '${stateIdParana}'),
        ('Rio Branco do Sul', '${stateIdParana}'),
        ('Rio Negro', '${stateIdParana}'),
        ('Rolândia', '${stateIdParana}'),
        ('Roncador', '${stateIdParana}'),
        ('Rondon', '${stateIdParana}'),
        ('Rosário do Ivaí', '${stateIdParana}'),
        ('Sabáudia', '${stateIdParana}'),
        ('Salgado Filho', '${stateIdParana}'),
        ('Salto do Itararé', '${stateIdParana}'),
        ('Salto do Lontra', '${stateIdParana}'),
        ('Santa Amélia', '${stateIdParana}'),
        ('Santa Cecília do Pavão', '${stateIdParana}'),
        ('Santa Cruz de Monte Castelo', '${stateIdParana}'),
        ('Santa Fé', '${stateIdParana}'),
        ('Santa Helena', '${stateIdParana}'),
        ('Santa Inês', '${stateIdParana}'),
        ('Santa Isabel do Ivaí', '${stateIdParana}'),
        ('Santa Izabel do Oeste', '${stateIdParana}'),
        ('Santa Lúcia', '${stateIdParana}'),
        ('Santa Maria do Oeste', '${stateIdParana}'),
        ('Santa Mariana', '${stateIdParana}'),
        ('Santa Mônica', '${stateIdParana}'),
        ('Santa Tereza do Oeste', '${stateIdParana}'),
        ('Santa Terezinha de Itaipu', '${stateIdParana}'),
        ('Santana do Itararé', '${stateIdParana}'),
        ('Santo Antônio da Platina', '${stateIdParana}'),
        ('Santo Antônio do Caiuá', '${stateIdParana}'),
        ('Santo Antônio do Paraíso', '${stateIdParana}'),
        ('Santo Antônio do Sudoeste', '${stateIdParana}'),
        ('Santo Inácio', '${stateIdParana}'),
        ('São Carlos do Ivaí', '${stateIdParana}'),
        ('São Jerônimo da Serra', '${stateIdParana}'),
        ('São João', '${stateIdParana}'),
        ('São João do Caiuá', '${stateIdParana}'),
        ('São João do Ivaí', '${stateIdParana}'),
        ('São João do Triunfo', '${stateIdParana}'),
        ('São Jorge d\`Oeste', '${stateIdParana}'),
        ('São Jorge do Ivaí', '${stateIdParana}'),
        ('São Jorge do Patrocínio', '${stateIdParana}'),
        ('São José da Boa Vista', '${stateIdParana}'),
        ('São José das Palmeiras', '${stateIdParana}'),
        ('São José dos Pinhais', '${stateIdParana}'),
        ('São Manoel do Paraná', '${stateIdParana}'),
        ('São Mateus do Sul', '${stateIdParana}'),
        ('São Miguel do Iguaçu', '${stateIdParana}'),
        ('São Pedro do Iguaçu', '${stateIdParana}'),
        ('São Pedro do Ivaí', '${stateIdParana}'),
        ('São Pedro do Paraná', '${stateIdParana}'),
        ('São Sebastião da Amoreira', '${stateIdParana}'),
        ('São Tomé', '${stateIdParana}'),
        ('Sapopema', '${stateIdParana}'),
        ('Sarandi', '${stateIdParana}'),
        ('Saudade do Iguaçu', '${stateIdParana}'),
        ('Sengés', '${stateIdParana}'),
        ('Serranópolis do Iguaçu', '${stateIdParana}'),
        ('Sertaneja', '${stateIdParana}'),
        ('Sertanópolis', '${stateIdParana}'),
        ('Siqueira Campos', '${stateIdParana}'),
        ('Sulina', '${stateIdParana}'),
        ('Tamarana', '${stateIdParana}'),
        ('Tamboara', '${stateIdParana}'),
        ('Tapejara', '${stateIdParana}'),
        ('Tapira', '${stateIdParana}'),
        ('Teixeira Soares', '${stateIdParana}'),
        ('Telêmaco Borba', '${stateIdParana}'),
        ('Terra Boa', '${stateIdParana}'),
        ('Terra Rica', '${stateIdParana}'),
        ('Terra Roxa', '${stateIdParana}'),
        ('Tibagi', '${stateIdParana}'),
        ('Tijucas do Sul', '${stateIdParana}'),
        ('Toledo', '${stateIdParana}'),
        ('Tomazina', '${stateIdParana}'),
        ('Três Barras do Paraná', '${stateIdParana}'),
        ('Tunas do Paraná', '${stateIdParana}'),
        ('Tuneiras do Oeste', '${stateIdParana}'),
        ('Tupãssi', '${stateIdParana}'),
        ('Turvo', '${stateIdParana}'),
        ('Ubiratã', '${stateIdParana}'),
        ('Umuarama', '${stateIdParana}'),
        ('União da Vitória', '${stateIdParana}'),
        ('Uniflor', '${stateIdParana}'),
        ('Uraí', '${stateIdParana}'),
        ('Ventania', '${stateIdParana}'),
        ('Vera Cruz do Oeste', '${stateIdParana}'),
        ('Verê', '${stateIdParana}'),
        ('Virmond', '${stateIdParana}'),
        ('Vitorino', '${stateIdParana}'),
        ('Wenceslau Braz', '${stateIdParana}'),
        ('Xambrê', '${stateIdParana}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdParana = '926a897b-e272-473f-8c66-6c8dc0adddab';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdParana}';
    `);
  }
}
