import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateSergipe1744515287088
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdSergipe = '301fa5f0-8312-4bc6-a223-15569cfc8722';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Adamantina', '${stateIdSergipe}'),
        ('Adolfo', '${stateIdSergipe}'),
        ('Aguaí', '${stateIdSergipe}'),
        ('Águas da Prata', '${stateIdSergipe}'),
        ('Águas de Lindóia', '${stateIdSergipe}'),
        ('Águas de Santa Bárbara', '${stateIdSergipe}'),
        ('Águas de São Pedro', '${stateIdSergipe}'),
        ('Agudos', '${stateIdSergipe}'),
        ('Alambari', '${stateIdSergipe}'),
        ('Alfredo Marcondes', '${stateIdSergipe}'),
        ('Altair', '${stateIdSergipe}'),
        ('Altinópolis', '${stateIdSergipe}'),
        ('Alto Alegre', '${stateIdSergipe}'),
        ('Alumínio', '${stateIdSergipe}'),
        ('Álvares Florence', '${stateIdSergipe}'),
        ('Álvares Machado', '${stateIdSergipe}'),
        ('Álvaro de Carvalho', '${stateIdSergipe}'),
        ('Alvinlândia', '${stateIdSergipe}'),
        ('Americana', '${stateIdSergipe}'),
        ('Américo Brasiliense', '${stateIdSergipe}'),
        ('Américo de Campos', '${stateIdSergipe}'),
        ('Amparo', '${stateIdSergipe}'),
        ('Analândia', '${stateIdSergipe}'),
        ('Andradina', '${stateIdSergipe}'),
        ('Angatuba', '${stateIdSergipe}'),
        ('Anhembi', '${stateIdSergipe}'),
        ('Anhumas', '${stateIdSergipe}'),
        ('Aparecida', '${stateIdSergipe}'),
        ('Aparecida d\`Oeste', '${stateIdSergipe}'),
        ('Apiaí', '${stateIdSergipe}'),
        ('Araçariguama', '${stateIdSergipe}'),
        ('Araçatuba', '${stateIdSergipe}'),
        ('Araçoiaba da Serra', '${stateIdSergipe}'),
        ('Aramina', '${stateIdSergipe}'),
        ('Arandu', '${stateIdSergipe}'),
        ('Arapeí', '${stateIdSergipe}'),
        ('Araraquara', '${stateIdSergipe}'),
        ('Araras', '${stateIdSergipe}'),
        ('Arco-Íris', '${stateIdSergipe}'),
        ('Arealva', '${stateIdSergipe}'),
        ('Areias', '${stateIdSergipe}'),
        ('Areiópolis', '${stateIdSergipe}'),
        ('Ariranha', '${stateIdSergipe}'),
        ('Artur Nogueira', '${stateIdSergipe}'),
        ('Arujá', '${stateIdSergipe}'),
        ('Aspásia', '${stateIdSergipe}'),
        ('Assis', '${stateIdSergipe}'),
        ('Atibaia', '${stateIdSergipe}'),
        ('Auriflama', '${stateIdSergipe}'),
        ('Avaí', '${stateIdSergipe}'),
        ('Avanhandava', '${stateIdSergipe}'),
        ('Avaré', '${stateIdSergipe}'),
        ('Bady Bassitt', '${stateIdSergipe}'),
        ('Balbinos', '${stateIdSergipe}'),
        ('Bálsamo', '${stateIdSergipe}'),
        ('Bananal', '${stateIdSergipe}'),
        ('Barão de Antonina', '${stateIdSergipe}'),
        ('Barbosa', '${stateIdSergipe}'),
        ('Bariri', '${stateIdSergipe}'),
        ('Barra Bonita', '${stateIdSergipe}'),
        ('Barra do Chapéu', '${stateIdSergipe}'),
        ('Barra do Turvo', '${stateIdSergipe}'),
        ('Barretos', '${stateIdSergipe}'),
        ('Barrinha', '${stateIdSergipe}'),
        ('Barueri', '${stateIdSergipe}'),
        ('Bastos', '${stateIdSergipe}'),
        ('Batatais', '${stateIdSergipe}'),
        ('Bauru', '${stateIdSergipe}'),
        ('Bebedouro', '${stateIdSergipe}'),
        ('Bento de Abreu', '${stateIdSergipe}'),
        ('Bernardino de Campos', '${stateIdSergipe}'),
        ('Bertioga', '${stateIdSergipe}'),
        ('Bilac', '${stateIdSergipe}'),
        ('Birigui', '${stateIdSergipe}'),
        ('Biritiba-Mirim', '${stateIdSergipe}'),
        ('Boa Esperança do Sul', '${stateIdSergipe}'),
        ('Bocaina', '${stateIdSergipe}'),
        ('Bofete', '${stateIdSergipe}'),
        ('Boituva', '${stateIdSergipe}'),
        ('Bom Jesus dos Perdões', '${stateIdSergipe}'),
        ('Bom Sucesso de Itararé', '${stateIdSergipe}'),
        ('Borá', '${stateIdSergipe}'),
        ('Boracéia', '${stateIdSergipe}'),
        ('Borborema', '${stateIdSergipe}'),
        ('Borebi', '${stateIdSergipe}'),
        ('Botucatu', '${stateIdSergipe}'),
        ('Bragança Paulista', '${stateIdSergipe}'),
        ('Braúna', '${stateIdSergipe}'),
        ('Brejo Alegre', '${stateIdSergipe}'),
        ('Brodowski', '${stateIdSergipe}'),
        ('Brotas', '${stateIdSergipe}'),
        ('Buri', '${stateIdSergipe}'),
        ('Buritama', '${stateIdSergipe}'),
        ('Buritizal', '${stateIdSergipe}'),
        ('Cabrália Paulista', '${stateIdSergipe}'),
        ('Cabreúva', '${stateIdSergipe}'),
        ('Caçapava', '${stateIdSergipe}'),
        ('Cachoeira Paulista', '${stateIdSergipe}'),
        ('Caconde', '${stateIdSergipe}'),
        ('Cafelândia', '${stateIdSergipe}'),
        ('Caiabu', '${stateIdSergipe}'),
        ('Caieiras', '${stateIdSergipe}'),
        ('Caiuá', '${stateIdSergipe}'),
        ('Cajamar', '${stateIdSergipe}'),
        ('Cajati', '${stateIdSergipe}'),
        ('Cajobi', '${stateIdSergipe}'),
        ('Cajuru', '${stateIdSergipe}'),
        ('Campina do Monte Alegre', '${stateIdSergipe}'),
        ('Campinas', '${stateIdSergipe}'),
        ('Campo Limpo Paulista', '${stateIdSergipe}'),
        ('Campos do Jordão', '${stateIdSergipe}'),
        ('Campos Novos Paulista', '${stateIdSergipe}'),
        ('Cananéia', '${stateIdSergipe}'),
        ('Canas', '${stateIdSergipe}'),
        ('Cândido Mota', '${stateIdSergipe}'),
        ('Cândido Rodrigues', '${stateIdSergipe}'),
        ('Canitar', '${stateIdSergipe}'),
        ('Capão Bonito', '${stateIdSergipe}'),
        ('Capela do Alto', '${stateIdSergipe}'),
        ('Capivari', '${stateIdSergipe}'),
        ('Caraguatatuba', '${stateIdSergipe}'),
        ('Carapicuíba', '${stateIdSergipe}'),
        ('Cardoso', '${stateIdSergipe}'),
        ('Casa Branca', '${stateIdSergipe}'),
        ('Cássia dos Coqueiros', '${stateIdSergipe}'),
        ('Castilho', '${stateIdSergipe}'),
        ('Catanduva', '${stateIdSergipe}'),
        ('Catiguá', '${stateIdSergipe}'),
        ('Cedral', '${stateIdSergipe}'),
        ('Cerqueira César', '${stateIdSergipe}'),
        ('Cerquilho', '${stateIdSergipe}'),
        ('Cesário Lange', '${stateIdSergipe}'),
        ('Charqueada', '${stateIdSergipe}'),
        ('Chavantes', '${stateIdSergipe}'),
        ('Clementina', '${stateIdSergipe}'),
        ('Colina', '${stateIdSergipe}'),
        ('Colômbia', '${stateIdSergipe}'),
        ('Conchal', '${stateIdSergipe}'),
        ('Conchas', '${stateIdSergipe}'),
        ('Cordeirópolis', '${stateIdSergipe}'),
        ('Coroados', '${stateIdSergipe}'),
        ('Coronel Macedo', '${stateIdSergipe}'),
        ('Corumbataí', '${stateIdSergipe}'),
        ('Cosmópolis', '${stateIdSergipe}'),
        ('Cosmorama', '${stateIdSergipe}'),
        ('Cotia', '${stateIdSergipe}'),
        ('Cravinhos', '${stateIdSergipe}'),
        ('Cristais Paulista', '${stateIdSergipe}'),
        ('Cruzália', '${stateIdSergipe}'),
        ('Cruzeiro', '${stateIdSergipe}'),
        ('Cubatão', '${stateIdSergipe}'),
        ('Cunha', '${stateIdSergipe}'),
        ('Descalvado', '${stateIdSergipe}'),
        ('Diadema', '${stateIdSergipe}'),
        ('Dirce Reis', '${stateIdSergipe}'),
        ('Divinolândia', '${stateIdSergipe}'),
        ('Dobrada', '${stateIdSergipe}'),
        ('Dois Córregos', '${stateIdSergipe}'),
        ('Dolcinópolis', '${stateIdSergipe}'),
        ('Dourado', '${stateIdSergipe}'),
        ('Dracena', '${stateIdSergipe}'),
        ('Duartina', '${stateIdSergipe}'),
        ('Dumont', '${stateIdSergipe}'),
        ('Echaporã', '${stateIdSergipe}'),
        ('Eldorado', '${stateIdSergipe}'),
        ('Elias Fausto', '${stateIdSergipe}'),
        ('Elisiário', '${stateIdSergipe}'),
        ('Embaúba', '${stateIdSergipe}'),
        ('Embu', '${stateIdSergipe}'),
        ('Embu-Guaçu', '${stateIdSergipe}'),
        ('Emilianópolis', '${stateIdSergipe}'),
        ('Engenheiro Coelho', '${stateIdSergipe}'),
        ('Espírito Santo do Pinhal', '${stateIdSergipe}'),
        ('Espírito Santo do Turvo', '${stateIdSergipe}'),
        ('Estiva Gerbi', '${stateIdSergipe}'),
        ('Estrela d\`Oeste', '${stateIdSergipe}'),
        ('Estrela do Norte', '${stateIdSergipe}'),
        ('Euclides da Cunha Paulista', '${stateIdSergipe}'),
        ('Fartura', '${stateIdSergipe}'),
        ('Fernando Prestes', '${stateIdSergipe}'),
        ('Fernandópolis', '${stateIdSergipe}'),
        ('Fernão', '${stateIdSergipe}'),
        ('Ferraz de Vasconcelos', '${stateIdSergipe}'),
        ('Flora Rica', '${stateIdSergipe}'),
        ('Floreal', '${stateIdSergipe}'),
        ('Flórida Paulista', '${stateIdSergipe}'),
        ('Florínia', '${stateIdSergipe}'),
        ('Franca', '${stateIdSergipe}'),
        ('Francisco Morato', '${stateIdSergipe}'),
        ('Franco da Rocha', '${stateIdSergipe}'),
        ('Gabriel Monteiro', '${stateIdSergipe}'),
        ('Gália', '${stateIdSergipe}'),
        ('Garça', '${stateIdSergipe}'),
        ('Gastão Vidigal', '${stateIdSergipe}'),
        ('Gavião Peixoto', '${stateIdSergipe}'),
        ('General Salgado', '${stateIdSergipe}'),
        ('Getulina', '${stateIdSergipe}'),
        ('Glicério', '${stateIdSergipe}'),
        ('Guaiçara', '${stateIdSergipe}'),
        ('Guaimbê', '${stateIdSergipe}'),
        ('Guaíra', '${stateIdSergipe}'),
        ('Guapiaçu', '${stateIdSergipe}'),
        ('Guapiara', '${stateIdSergipe}'),
        ('Guará', '${stateIdSergipe}'),
        ('Guaraçaí', '${stateIdSergipe}'),
        ('Guaraci', '${stateIdSergipe}'),
        ('Guarani d\`Oeste', '${stateIdSergipe}'),
        ('Guarantã', '${stateIdSergipe}'),
        ('Guararapes', '${stateIdSergipe}'),
        ('Guararema', '${stateIdSergipe}'),
        ('Guaratinguetá', '${stateIdSergipe}'),
        ('Guareí', '${stateIdSergipe}'),
        ('Guariba', '${stateIdSergipe}'),
        ('Guarujá', '${stateIdSergipe}'),
        ('Guarulhos', '${stateIdSergipe}'),
        ('Guatapará', '${stateIdSergipe}'),
        ('Guzolândia', '${stateIdSergipe}'),
        ('Herculândia', '${stateIdSergipe}'),
        ('Holambra', '${stateIdSergipe}'),
        ('Hortolândia', '${stateIdSergipe}'),
        ('Iacanga', '${stateIdSergipe}'),
        ('Iacri', '${stateIdSergipe}'),
        ('Iaras', '${stateIdSergipe}'),
        ('Ibaté', '${stateIdSergipe}'),
        ('Ibirá', '${stateIdSergipe}'),
        ('Ibirarema', '${stateIdSergipe}'),
        ('Ibitinga', '${stateIdSergipe}'),
        ('Ibiúna', '${stateIdSergipe}'),
        ('Icém', '${stateIdSergipe}'),
        ('Iepê', '${stateIdSergipe}'),
        ('Igaraçu do Tietê', '${stateIdSergipe}'),
        ('Igarapava', '${stateIdSergipe}'),
        ('Igaratá', '${stateIdSergipe}'),
        ('Iguape', '${stateIdSergipe}'),
        ('Ilha Comprida', '${stateIdSergipe}'),
        ('Ilha Solteira', '${stateIdSergipe}'),
        ('Ilhabela', '${stateIdSergipe}'),
        ('Indaiatuba', '${stateIdSergipe}'),
        ('Indiana', '${stateIdSergipe}'),
        ('Indiaporã', '${stateIdSergipe}'),
        ('Inúbia Paulista', '${stateIdSergipe}'),
        ('Ipaussu', '${stateIdSergipe}'),
        ('Iperó', '${stateIdSergipe}'),
        ('Ipeúna', '${stateIdSergipe}'),
        ('Ipiguá', '${stateIdSergipe}'),
        ('Iporanga', '${stateIdSergipe}'),
        ('Ipuã', '${stateIdSergipe}'),
        ('Iracemápolis', '${stateIdSergipe}'),
        ('Irapuã', '${stateIdSergipe}'),
        ('Irapuru', '${stateIdSergipe}'),
        ('Itaberá', '${stateIdSergipe}'),
        ('Itaí', '${stateIdSergipe}'),
        ('Itajobi', '${stateIdSergipe}'),
        ('Itaju', '${stateIdSergipe}'),
        ('Itanhaém', '${stateIdSergipe}'),
        ('Itaóca', '${stateIdSergipe}'),
        ('Itapecerica da Serra', '${stateIdSergipe}'),
        ('Itapetininga', '${stateIdSergipe}'),
        ('Itapeva', '${stateIdSergipe}'),
        ('Itapevi', '${stateIdSergipe}'),
        ('Itapira', '${stateIdSergipe}'),
        ('Itapirapuã Paulista', '${stateIdSergipe}'),
        ('Itápolis', '${stateIdSergipe}'),
        ('Itaporanga', '${stateIdSergipe}'),
        ('Itapuí', '${stateIdSergipe}'),
        ('Itapura', '${stateIdSergipe}'),
        ('Itaquaquecetuba', '${stateIdSergipe}'),
        ('Itararé', '${stateIdSergipe}'),
        ('Itariri', '${stateIdSergipe}'),
        ('Itatiba', '${stateIdSergipe}'),
        ('Itatinga', '${stateIdSergipe}'),
        ('Itirapina', '${stateIdSergipe}'),
        ('Itirapuã', '${stateIdSergipe}'),
        ('Itobi', '${stateIdSergipe}'),
        ('Itu', '${stateIdSergipe}'),
        ('Itupeva', '${stateIdSergipe}'),
        ('Ituverava', '${stateIdSergipe}'),
        ('Jaborandi', '${stateIdSergipe}'),
        ('Jaboticabal', '${stateIdSergipe}'),
        ('Jacareí', '${stateIdSergipe}'),
        ('Jaci', '${stateIdSergipe}'),
        ('Jacupiranga', '${stateIdSergipe}'),
        ('Jaguariúna', '${stateIdSergipe}'),
        ('Jales', '${stateIdSergipe}'),
        ('Jambeiro', '${stateIdSergipe}'),
        ('Jandira', '${stateIdSergipe}'),
        ('Jardinópolis', '${stateIdSergipe}'),
        ('Jarinu', '${stateIdSergipe}'),
        ('Jaú', '${stateIdSergipe}'),
        ('Jeriquara', '${stateIdSergipe}'),
        ('Joanópolis', '${stateIdSergipe}'),
        ('João Ramalho', '${stateIdSergipe}'),
        ('José Bonifácio', '${stateIdSergipe}'),
        ('Júlio Mesquita', '${stateIdSergipe}'),
        ('Jumirim', '${stateIdSergipe}'),
        ('Jundiaí', '${stateIdSergipe}'),
        ('Junqueirópolis', '${stateIdSergipe}'),
        ('Juquiá', '${stateIdSergipe}'),
        ('Juquitiba', '${stateIdSergipe}'),
        ('Lagoinha', '${stateIdSergipe}'),
        ('Laranjal Paulista', '${stateIdSergipe}'),
        ('Lavínia', '${stateIdSergipe}'),
        ('Lavrinhas', '${stateIdSergipe}'),
        ('Leme', '${stateIdSergipe}'),
        ('Lençóis Paulista', '${stateIdSergipe}'),
        ('Limeira', '${stateIdSergipe}'),
        ('Lindóia', '${stateIdSergipe}'),
        ('Lins', '${stateIdSergipe}'),
        ('Lorena', '${stateIdSergipe}'),
        ('Lourdes', '${stateIdSergipe}'),
        ('Louveira', '${stateIdSergipe}'),
        ('Lucélia', '${stateIdSergipe}'),
        ('Lucianópolis', '${stateIdSergipe}'),
        ('Luís Antônio', '${stateIdSergipe}'),
        ('Luiziânia', '${stateIdSergipe}'),
        ('Lupércio', '${stateIdSergipe}'),
        ('Lutécia', '${stateIdSergipe}'),
        ('Macatuba', '${stateIdSergipe}'),
        ('Macaubal', '${stateIdSergipe}'),
        ('Macedônia', '${stateIdSergipe}'),
        ('Magda', '${stateIdSergipe}'),
        ('Mairinque', '${stateIdSergipe}'),
        ('Mairiporã', '${stateIdSergipe}'),
        ('Manduri', '${stateIdSergipe}'),
        ('Marabá Paulista', '${stateIdSergipe}'),
        ('Maracaí', '${stateIdSergipe}'),
        ('Marapoama', '${stateIdSergipe}'),
        ('Mariápolis', '${stateIdSergipe}'),
        ('Marília', '${stateIdSergipe}'),
        ('Marinópolis', '${stateIdSergipe}'),
        ('Martinópolis', '${stateIdSergipe}'),
        ('Matão', '${stateIdSergipe}'),
        ('Mauá', '${stateIdSergipe}'),
        ('Mendonça', '${stateIdSergipe}'),
        ('Meridiano', '${stateIdSergipe}'),
        ('Mesópolis', '${stateIdSergipe}'),
        ('Miguelópolis', '${stateIdSergipe}'),
        ('Mineiros do Tietê', '${stateIdSergipe}'),
        ('Mira Estrela', '${stateIdSergipe}'),
        ('Miracatu', '${stateIdSergipe}'),
        ('Mirandópolis', '${stateIdSergipe}'),
        ('Mirante do Paranapanema', '${stateIdSergipe}'),
        ('Mirassol', '${stateIdSergipe}'),
        ('Mirassolândia', '${stateIdSergipe}'),
        ('Mococa', '${stateIdSergipe}'),
        ('Mogi das Cruzes', '${stateIdSergipe}'),
        ('Mogi Guaçu', '${stateIdSergipe}'),
        ('Moji Mirim', '${stateIdSergipe}'),
        ('Mombuca', '${stateIdSergipe}'),
        ('Monções', '${stateIdSergipe}'),
        ('Mongaguá', '${stateIdSergipe}'),
        ('Monte Alegre do Sul', '${stateIdSergipe}'),
        ('Monte Alto', '${stateIdSergipe}'),
        ('Monte Aprazível', '${stateIdSergipe}'),
        ('Monte Azul Paulista', '${stateIdSergipe}'),
        ('Monte Castelo', '${stateIdSergipe}'),
        ('Monte Mor', '${stateIdSergipe}'),
        ('Monteiro Lobato', '${stateIdSergipe}'),
        ('Morro Agudo', '${stateIdSergipe}'),
        ('Morungaba', '${stateIdSergipe}'),
        ('Motuca', '${stateIdSergipe}'),
        ('Murutinga do Sul', '${stateIdSergipe}'),
        ('Nantes', '${stateIdSergipe}'),
        ('Narandiba', '${stateIdSergipe}'),
        ('Natividade da Serra', '${stateIdSergipe}'),
        ('Nazaré Paulista', '${stateIdSergipe}'),
        ('Neves Paulista', '${stateIdSergipe}'),
        ('Nhandeara', '${stateIdSergipe}'),
        ('Nipoã', '${stateIdSergipe}'),
        ('Nova Aliança', '${stateIdSergipe}'),
        ('Nova Campina', '${stateIdSergipe}'),
        ('Nova Canaã Paulista', '${stateIdSergipe}'),
        ('Nova Castilho', '${stateIdSergipe}'),
        ('Nova Europa', '${stateIdSergipe}'),
        ('Nova Granada', '${stateIdSergipe}'),
        ('Nova Guataporanga', '${stateIdSergipe}'),
        ('Nova Independência', '${stateIdSergipe}'),
        ('Nova Luzitânia', '${stateIdSergipe}'),
        ('Nova Odessa', '${stateIdSergipe}'),
        ('Novais', '${stateIdSergipe}'),
        ('Novo Horizonte', '${stateIdSergipe}'),
        ('Nuporanga', '${stateIdSergipe}'),
        ('Ocauçu', '${stateIdSergipe}'),
        ('Óleo', '${stateIdSergipe}'),
        ('Olímpia', '${stateIdSergipe}'),
        ('Onda Verde', '${stateIdSergipe}'),
        ('Oriente', '${stateIdSergipe}'),
        ('Orindiúva', '${stateIdSergipe}'),
        ('Orlândia', '${stateIdSergipe}'),
        ('Osasco', '${stateIdSergipe}'),
        ('Oscar Bressane', '${stateIdSergipe}'),
        ('Osvaldo Cruz', '${stateIdSergipe}'),
        ('Ourinhos', '${stateIdSergipe}'),
        ('Ouro Verde', '${stateIdSergipe}'),
        ('Ouroeste', '${stateIdSergipe}'),
        ('Pacaembu', '${stateIdSergipe}'),
        ('Palestina', '${stateIdSergipe}'),
        ('Palmares Paulista', '${stateIdSergipe}'),
        ('Palmeira d\`Oeste', '${stateIdSergipe}'),
        ('Palmital', '${stateIdSergipe}'),
        ('Panorama', '${stateIdSergipe}'),
        ('Paraguaçu Paulista', '${stateIdSergipe}'),
        ('Paraibuna', '${stateIdSergipe}'),
        ('Paraíso', '${stateIdSergipe}'),
        ('Paranapanema', '${stateIdSergipe}'),
        ('Paranapuã', '${stateIdSergipe}'),
        ('Parapuã', '${stateIdSergipe}'),
        ('Pardinho', '${stateIdSergipe}'),
        ('Pariquera-Açu', '${stateIdSergipe}'),
        ('Parisi', '${stateIdSergipe}'),
        ('Patrocínio Paulista', '${stateIdSergipe}'),
        ('Paulicéia', '${stateIdSergipe}'),
        ('Paulínia', '${stateIdSergipe}'),
        ('Paulistânia', '${stateIdSergipe}'),
        ('Paulo de Faria', '${stateIdSergipe}'),
        ('Pederneiras', '${stateIdSergipe}'),
        ('Pedra Bela', '${stateIdSergipe}'),
        ('Pedranópolis', '${stateIdSergipe}'),
        ('Pedregulho', '${stateIdSergipe}'),
        ('Pedreira', '${stateIdSergipe}'),
        ('Pedrinhas Paulista', '${stateIdSergipe}'),
        ('Pedro de Toledo', '${stateIdSergipe}'),
        ('Penápolis', '${stateIdSergipe}'),
        ('Pereira Barreto', '${stateIdSergipe}'),
        ('Pereiras', '${stateIdSergipe}'),
        ('Peruíbe', '${stateIdSergipe}'),
        ('Piacatu', '${stateIdSergipe}'),
        ('Piedade', '${stateIdSergipe}'),
        ('Pilar do Sul', '${stateIdSergipe}'),
        ('Pindamonhangaba', '${stateIdSergipe}'),
        ('Pindorama', '${stateIdSergipe}'),
        ('Pinhalzinho', '${stateIdSergipe}'),
        ('Piquerobi', '${stateIdSergipe}'),
        ('Piquete', '${stateIdSergipe}'),
        ('Piracaia', '${stateIdSergipe}'),
        ('Piracicaba', '${stateIdSergipe}'),
        ('Piraju', '${stateIdSergipe}'),
        ('Pirajuí', '${stateIdSergipe}'),
        ('Pirangi', '${stateIdSergipe}'),
        ('Pirapora do Bom Jesus', '${stateIdSergipe}'),
        ('Pirapozinho', '${stateIdSergipe}'),
        ('Pirassununga', '${stateIdSergipe}'),
        ('Piratininga', '${stateIdSergipe}'),
        ('Pitangueiras', '${stateIdSergipe}'),
        ('Planalto', '${stateIdSergipe}'),
        ('Platina', '${stateIdSergipe}'),
        ('Poá', '${stateIdSergipe}'),
        ('Poloni', '${stateIdSergipe}'),
        ('Pompéia', '${stateIdSergipe}'),
        ('Pongaí', '${stateIdSergipe}'),
        ('Pontal', '${stateIdSergipe}'),
        ('Pontalinda', '${stateIdSergipe}'),
        ('Pontes Gestal', '${stateIdSergipe}'),
        ('Populina', '${stateIdSergipe}'),
        ('Porangaba', '${stateIdSergipe}'),
        ('Porto Feliz', '${stateIdSergipe}'),
        ('Porto Ferreira', '${stateIdSergipe}'),
        ('Potim', '${stateIdSergipe}'),
        ('Potirendaba', '${stateIdSergipe}'),
        ('Pracinha', '${stateIdSergipe}'),
        ('Pradópolis', '${stateIdSergipe}'),
        ('Praia Grande', '${stateIdSergipe}'),
        ('Pratânia', '${stateIdSergipe}'),
        ('Presidente Alves', '${stateIdSergipe}'),
        ('Presidente Bernardes', '${stateIdSergipe}'),
        ('Presidente Epitácio', '${stateIdSergipe}'),
        ('Presidente Prudente', '${stateIdSergipe}'),
        ('Presidente Venceslau', '${stateIdSergipe}'),
        ('Promissão', '${stateIdSergipe}'),
        ('Quadra', '${stateIdSergipe}'),
        ('Quatá', '${stateIdSergipe}'),
        ('Queiroz', '${stateIdSergipe}'),
        ('Queluz', '${stateIdSergipe}'),
        ('Quintana', '${stateIdSergipe}'),
        ('Rafard', '${stateIdSergipe}'),
        ('Rancharia', '${stateIdSergipe}'),
        ('Redenção da Serra', '${stateIdSergipe}'),
        ('Regente Feijó', '${stateIdSergipe}'),
        ('Reginópolis', '${stateIdSergipe}'),
        ('Registro', '${stateIdSergipe}'),
        ('Restinga', '${stateIdSergipe}'),
        ('Ribeira', '${stateIdSergipe}'),
        ('Ribeirão Bonito', '${stateIdSergipe}'),
        ('Ribeirão Branco', '${stateIdSergipe}'),
        ('Ribeirão Corrente', '${stateIdSergipe}'),
        ('Ribeirão do Sul', '${stateIdSergipe}'),
        ('Ribeirão dos Índios', '${stateIdSergipe}'),
        ('Ribeirão Grande', '${stateIdSergipe}'),
        ('Ribeirão Pires', '${stateIdSergipe}'),
        ('Ribeirão Preto', '${stateIdSergipe}'),
        ('Rifaina', '${stateIdSergipe}'),
        ('Rincão', '${stateIdSergipe}'),
        ('Rinópolis', '${stateIdSergipe}'),
        ('Rio Claro', '${stateIdSergipe}'),
        ('Rio das Pedras', '${stateIdSergipe}'),
        ('Rio Grande da Serra', '${stateIdSergipe}'),
        ('Riolândia', '${stateIdSergipe}'),
        ('Riversul', '${stateIdSergipe}'),
        ('Rosana', '${stateIdSergipe}'),
        ('Roseira', '${stateIdSergipe}'),
        ('Rubiácea', '${stateIdSergipe}'),
        ('Rubinéia', '${stateIdSergipe}'),
        ('Sabino', '${stateIdSergipe}'),
        ('Sagres', '${stateIdSergipe}'),
        ('Sales', '${stateIdSergipe}'),
        ('Sales Oliveira', '${stateIdSergipe}'),
        ('Salesópolis', '${stateIdSergipe}'),
        ('Salmourão', '${stateIdSergipe}'),
        ('Saltinho', '${stateIdSergipe}'),
        ('Salto', '${stateIdSergipe}'),
        ('Salto de Pirapora', '${stateIdSergipe}'),
        ('Salto Grande', '${stateIdSergipe}'),
        ('Sandovalina', '${stateIdSergipe}'),
        ('Santa Adélia', '${stateIdSergipe}'),
        ('Santa Albertina', '${stateIdSergipe}'),
        ('Santa Bárbara d\`Oeste', '${stateIdSergipe}'),
        ('Santa Branca', '${stateIdSergipe}'),
        ('Santa Clara d\`Oeste', '${stateIdSergipe}'),
        ('Santa Cruz da Conceição', '${stateIdSergipe}'),
        ('Santa Cruz da Esperança', '${stateIdSergipe}'),
        ('Santa Cruz das Palmeiras', '${stateIdSergipe}'),
        ('Santa Cruz do Rio Pardo', '${stateIdSergipe}'),
        ('Santa Ernestina', '${stateIdSergipe}'),
        ('Santa Fé do Sul', '${stateIdSergipe}'),
        ('Santa Gertrudes', '${stateIdSergipe}'),
        ('Santa Isabel', '${stateIdSergipe}'),
        ('Santa Lúcia', '${stateIdSergipe}'),
        ('Santa Maria da Serra', '${stateIdSergipe}'),
        ('Santa Mercedes', '${stateIdSergipe}'),
        ('Santa Rita d\`Oeste', '${stateIdSergipe}'),
        ('Santa Rita do Passa Quatro', '${stateIdSergipe}'),
        ('Santa Rosa de Viterbo', '${stateIdSergipe}'),
        ('Santa Salete', '${stateIdSergipe}'),
        ('Santana da Ponte Pensa', '${stateIdSergipe}'),
        ('Santana de Parnaíba', '${stateIdSergipe}'),
        ('Santo Anastácio', '${stateIdSergipe}'),
        ('Santo André', '${stateIdSergipe}'),
        ('Santo Antônio da Alegria', '${stateIdSergipe}'),
        ('Santo Antônio de Posse', '${stateIdSergipe}'),
        ('Santo Antônio do Aracanguá', '${stateIdSergipe}'),
        ('Santo Antônio do Jardim', '${stateIdSergipe}'),
        ('Santo Antônio do Pinhal', '${stateIdSergipe}'),
        ('Santo Expedito', '${stateIdSergipe}'),
        ('Santópolis do Aguapeí', '${stateIdSergipe}'),
        ('Santos', '${stateIdSergipe}'),
        ('São Bento do Sapucaí', '${stateIdSergipe}'),
        ('São Bernardo do Campo', '${stateIdSergipe}'),
        ('São Caetano do Sul', '${stateIdSergipe}'),
        ('São Carlos', '${stateIdSergipe}'),
        ('São Francisco', '${stateIdSergipe}'),
        ('São João da Boa Vista', '${stateIdSergipe}'),
        ('São João das Duas Pontes', '${stateIdSergipe}'),
        ('São João de Iracema', '${stateIdSergipe}'),
        ('São João do Pau d\`Alho', '${stateIdSergipe}'),
        ('São Joaquim da Barra', '${stateIdSergipe}'),
        ('São José da Bela Vista', '${stateIdSergipe}'),
        ('São José do Barreiro', '${stateIdSergipe}'),
        ('São José do Rio Pardo', '${stateIdSergipe}'),
        ('São José do Rio Preto', '${stateIdSergipe}'),
        ('São José dos Campos', '${stateIdSergipe}'),
        ('São Lourenço da Serra', '${stateIdSergipe}'),
        ('São Luís do Paraitinga', '${stateIdSergipe}'),
        ('São Manuel', '${stateIdSergipe}'),
        ('São Miguel Arcanjo', '${stateIdSergipe}'),
        ('São Paulo', '${stateIdSergipe}'),
        ('São Pedro', '${stateIdSergipe}'),
        ('São Pedro do Turvo', '${stateIdSergipe}'),
        ('São Roque', '${stateIdSergipe}'),
        ('São Sebastião', '${stateIdSergipe}'),
        ('São Sebastião da Grama', '${stateIdSergipe}'),
        ('São Simão', '${stateIdSergipe}'),
        ('São Vicente', '${stateIdSergipe}'),
        ('Sarapuí', '${stateIdSergipe}'),
        ('Sarutaiá', '${stateIdSergipe}'),
        ('Sebastianópolis do Sul', '${stateIdSergipe}'),
        ('Serra Azul', '${stateIdSergipe}'),
        ('Serra Negra', '${stateIdSergipe}'),
        ('Serrana', '${stateIdSergipe}'),
        ('Sertãozinho', '${stateIdSergipe}'),
        ('Sete Barras', '${stateIdSergipe}'),
        ('Severínia', '${stateIdSergipe}'),
        ('Silveiras', '${stateIdSergipe}'),
        ('Socorro', '${stateIdSergipe}'),
        ('Sorocaba', '${stateIdSergipe}'),
        ('Sud Mennucci', '${stateIdSergipe}'),
        ('Sumaré', '${stateIdSergipe}'),
        ('Suzanápolis', '${stateIdSergipe}'),
        ('Suzano', '${stateIdSergipe}'),
        ('Tabapuã', '${stateIdSergipe}'),
        ('Tabatinga', '${stateIdSergipe}'),
        ('Taboão da Serra', '${stateIdSergipe}'),
        ('Taciba', '${stateIdSergipe}'),
        ('Taguaí', '${stateIdSergipe}'),
        ('Taiaçu', '${stateIdSergipe}'),
        ('Taiúva', '${stateIdSergipe}'),
        ('Tambaú', '${stateIdSergipe}'),
        ('Tanabi', '${stateIdSergipe}'),
        ('Tapiraí', '${stateIdSergipe}'),
        ('Tapiratiba', '${stateIdSergipe}'),
        ('Taquaral', '${stateIdSergipe}'),
        ('Taquaritinga', '${stateIdSergipe}'),
        ('Taquarituba', '${stateIdSergipe}'),
        ('Taquarivaí', '${stateIdSergipe}'),
        ('Tarabai', '${stateIdSergipe}'),
        ('Tarumã', '${stateIdSergipe}'),
        ('Tatuí', '${stateIdSergipe}'),
        ('Taubaté', '${stateIdSergipe}'),
        ('Tejupá', '${stateIdSergipe}'),
        ('Teodoro Sampaio', '${stateIdSergipe}'),
        ('Terra Roxa', '${stateIdSergipe}'),
        ('Tietê', '${stateIdSergipe}'),
        ('Timburi', '${stateIdSergipe}'),
        ('Torre de Pedra', '${stateIdSergipe}'),
        ('Torrinha', '${stateIdSergipe}'),
        ('Trabiju', '${stateIdSergipe}'),
        ('Tremembé', '${stateIdSergipe}'),
        ('Três Fronteiras', '${stateIdSergipe}'),
        ('Tuiuti', '${stateIdSergipe}'),
        ('Tupã', '${stateIdSergipe}'),
        ('Tupi Paulista', '${stateIdSergipe}'),
        ('Turiúba', '${stateIdSergipe}'),
        ('Turmalina', '${stateIdSergipe}'),
        ('Ubarana', '${stateIdSergipe}'),
        ('Ubatuba', '${stateIdSergipe}'),
        ('Ubirajara', '${stateIdSergipe}'),
        ('Uchoa', '${stateIdSergipe}'),
        ('União Paulista', '${stateIdSergipe}'),
        ('Urânia', '${stateIdSergipe}'),
        ('Uru', '${stateIdSergipe}'),
        ('Urupês', '${stateIdSergipe}'),
        ('Valentim Gentil', '${stateIdSergipe}'),
        ('Valinhos', '${stateIdSergipe}'),
        ('Valparaíso', '${stateIdSergipe}'),
        ('Vargem', '${stateIdSergipe}'),
        ('Vargem Grande do Sul', '${stateIdSergipe}'),
        ('Vargem Grande Paulista', '${stateIdSergipe}'),
        ('Várzea Paulista', '${stateIdSergipe}'),
        ('Vera Cruz', '${stateIdSergipe}'),
        ('Vinhedo', '${stateIdSergipe}'),
        ('Viradouro', '${stateIdSergipe}'),
        ('Vista Alegre do Alto', '${stateIdSergipe}'),
        ('Vitória Brasil', '${stateIdSergipe}'),
        ('Votorantim', '${stateIdSergipe}'),
        ('Votuporanga', '${stateIdSergipe}'),
        ('Zacarias', '${stateIdSergipe}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdSergipe = '301fa5f0-8312-4bc6-a223-15569cfc8722';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdSergipe}';
    `);
  }
}
