import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStatePiaui1744510489593
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdPiaui = '1e95ac7f-c3d3-4e4c-b1b3-7d65ae8bb2fd';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Acauã', '${stateIdPiaui}'),
        ('Agricolândia', '${stateIdPiaui}'),
        ('Água Branca', '${stateIdPiaui}'),
        ('Alagoinha do Piauí', '${stateIdPiaui}'),
        ('Alegrete do Piauí', '${stateIdPiaui}'),
        ('Alto Longá', '${stateIdPiaui}'),
        ('Altos', '${stateIdPiaui}'),
        ('Alvorada do Gurguéia', '${stateIdPiaui}'),
        ('Amarante', '${stateIdPiaui}'),
        ('Angical do Piauí', '${stateIdPiaui}'),
        ('Anísio de Abreu', '${stateIdPiaui}'),
        ('Antônio Almeida', '${stateIdPiaui}'),
        ('Aroazes', '${stateIdPiaui}'),
        ('Aroeiras do Itaim', '${stateIdPiaui}'),
        ('Arraial', '${stateIdPiaui}'),
        ('Assunção do Piauí', '${stateIdPiaui}'),
        ('Avelino Lopes', '${stateIdPiaui}'),
        ('Baixa Grande do Ribeiro', '${stateIdPiaui}'),
        ('Barra d\`Alcântara', '${stateIdPiaui}'),
        ('Barras', '${stateIdPiaui}'),
        ('Barreiras do Piauí', '${stateIdPiaui}'),
        ('Barro Duro', '${stateIdPiaui}'),
        ('Batalha', '${stateIdPiaui}'),
        ('Bela Vista do Piauí', '${stateIdPiaui}'),
        ('Belém do Piauí', '${stateIdPiaui}'),
        ('Beneditinos', '${stateIdPiaui}'),
        ('Bertolínia', '${stateIdPiaui}'),
        ('Betânia do Piauí', '${stateIdPiaui}'),
        ('Boa Hora', '${stateIdPiaui}'),
        ('Bocaina', '${stateIdPiaui}'),
        ('Bom Jesus', '${stateIdPiaui}'),
        ('Bom Princípio do Piauí', '${stateIdPiaui}'),
        ('Bonfim do Piauí', '${stateIdPiaui}'),
        ('Boqueirão do Piauí', '${stateIdPiaui}'),
        ('Brasileira', '${stateIdPiaui}'),
        ('Brejo do Piauí', '${stateIdPiaui}'),
        ('Buriti dos Lopes', '${stateIdPiaui}'),
        ('Buriti dos Montes', '${stateIdPiaui}'),
        ('Cabeceiras do Piauí', '${stateIdPiaui}'),
        ('Cajazeiras do Piauí', '${stateIdPiaui}'),
        ('Cajueiro da Praia', '${stateIdPiaui}'),
        ('Caldeirão Grande do Piauí', '${stateIdPiaui}'),
        ('Campinas do Piauí', '${stateIdPiaui}'),
        ('Campo Alegre do Fidalgo', '${stateIdPiaui}'),
        ('Campo Grande do Piauí', '${stateIdPiaui}'),
        ('Campo Largo do Piauí', '${stateIdPiaui}'),
        ('Campo Maior', '${stateIdPiaui}'),
        ('Canavieira', '${stateIdPiaui}'),
        ('Canto do Buriti', '${stateIdPiaui}'),
        ('Capitão de Campos', '${stateIdPiaui}'),
        ('Capitão Gervásio Oliveira', '${stateIdPiaui}'),
        ('Caracol', '${stateIdPiaui}'),
        ('Caraúbas do Piauí', '${stateIdPiaui}'),
        ('Caridade do Piauí', '${stateIdPiaui}'),
        ('Castelo do Piauí', '${stateIdPiaui}'),
        ('Caxingó', '${stateIdPiaui}'),
        ('Cocal', '${stateIdPiaui}'),
        ('Cocal de Telha', '${stateIdPiaui}'),
        ('Cocal dos Alves', '${stateIdPiaui}'),
        ('Coivaras', '${stateIdPiaui}'),
        ('Colônia do Gurguéia', '${stateIdPiaui}'),
        ('Colônia do Piauí', '${stateIdPiaui}'),
        ('Conceição do Canindé', '${stateIdPiaui}'),
        ('Coronel José Dias', '${stateIdPiaui}'),
        ('Corrente', '${stateIdPiaui}'),
        ('Cristalândia do Piauí', '${stateIdPiaui}'),
        ('Cristino Castro', '${stateIdPiaui}'),
        ('Curimatá', '${stateIdPiaui}'),
        ('Currais', '${stateIdPiaui}'),
        ('Curral Novo do Piauí', '${stateIdPiaui}'),
        ('Curralinhos', '${stateIdPiaui}'),
        ('Demerval Lobão', '${stateIdPiaui}'),
        ('Dirceu Arcoverde', '${stateIdPiaui}'),
        ('Dom Expedito Lopes', '${stateIdPiaui}'),
        ('Dom Inocêncio', '${stateIdPiaui}'),
        ('Domingos Mourão', '${stateIdPiaui}'),
        ('Elesbão Veloso', '${stateIdPiaui}'),
        ('Eliseu Martins', '${stateIdPiaui}'),
        ('Esperantina', '${stateIdPiaui}'),
        ('Fartura do Piauí', '${stateIdPiaui}'),
        ('Flores do Piauí', '${stateIdPiaui}'),
        ('Floresta do Piauí', '${stateIdPiaui}'),
        ('Floriano', '${stateIdPiaui}'),
        ('Francinópolis', '${stateIdPiaui}'),
        ('Francisco Ayres', '${stateIdPiaui}'),
        ('Francisco Macedo', '${stateIdPiaui}'),
        ('Francisco Santos', '${stateIdPiaui}'),
        ('Fronteiras', '${stateIdPiaui}'),
        ('Geminiano', '${stateIdPiaui}'),
        ('Gilbués', '${stateIdPiaui}'),
        ('Guadalupe', '${stateIdPiaui}'),
        ('Guaribas', '${stateIdPiaui}'),
        ('Hugo Napoleão', '${stateIdPiaui}'),
        ('Ilha Grande', '${stateIdPiaui}'),
        ('Inhuma', '${stateIdPiaui}'),
        ('Ipiranga do Piauí', '${stateIdPiaui}'),
        ('Isaías Coelho', '${stateIdPiaui}'),
        ('Itainópolis', '${stateIdPiaui}'),
        ('Itaueira', '${stateIdPiaui}'),
        ('Jacobina do Piauí', '${stateIdPiaui}'),
        ('Jaicós', '${stateIdPiaui}'),
        ('Jardim do Mulato', '${stateIdPiaui}'),
        ('Jatobá do Piauí', '${stateIdPiaui}'),
        ('Jerumenha', '${stateIdPiaui}'),
        ('João Costa', '${stateIdPiaui}'),
        ('Joaquim Pires', '${stateIdPiaui}'),
        ('Joca Marques', '${stateIdPiaui}'),
        ('José de Freitas', '${stateIdPiaui}'),
        ('Juazeiro do Piauí', '${stateIdPiaui}'),
        ('Júlio Borges', '${stateIdPiaui}'),
        ('Jurema', '${stateIdPiaui}'),
        ('Lagoa Alegre', '${stateIdPiaui}'),
        ('Lagoa de São Francisco', '${stateIdPiaui}'),
        ('Lagoa do Barro do Piauí', '${stateIdPiaui}'),
        ('Lagoa do Piauí', '${stateIdPiaui}'),
        ('Lagoa do Sítio', '${stateIdPiaui}'),
        ('Lagoinha do Piauí', '${stateIdPiaui}'),
        ('Landri Sales', '${stateIdPiaui}'),
        ('Luís Correia', '${stateIdPiaui}'),
        ('Luzilândia', '${stateIdPiaui}'),
        ('Madeiro', '${stateIdPiaui}'),
        ('Manoel Emídio', '${stateIdPiaui}'),
        ('Marcolândia', '${stateIdPiaui}'),
        ('Marcos Parente', '${stateIdPiaui}'),
        ('Massapê do Piauí', '${stateIdPiaui}'),
        ('Matias Olímpio', '${stateIdPiaui}'),
        ('Miguel Alves', '${stateIdPiaui}'),
        ('Miguel Leão', '${stateIdPiaui}'),
        ('Milton Brandão', '${stateIdPiaui}'),
        ('Monsenhor Gil', '${stateIdPiaui}'),
        ('Monsenhor Hipólito', '${stateIdPiaui}'),
        ('Monte Alegre do Piauí', '${stateIdPiaui}'),
        ('Morro Cabeça no Tempo', '${stateIdPiaui}'),
        ('Morro do Chapéu do Piauí', '${stateIdPiaui}'),
        ('Murici dos Portelas', '${stateIdPiaui}'),
        ('Nazaré do Piauí', '${stateIdPiaui}'),
        ('Nossa Senhora de Nazaré', '${stateIdPiaui}'),
        ('Nossa Senhora dos Remédios', '${stateIdPiaui}'),
        ('Nova Santa Rita', '${stateIdPiaui}'),
        ('Novo Oriente do Piauí', '${stateIdPiaui}'),
        ('Novo Santo Antônio', '${stateIdPiaui}'),
        ('Oeiras', '${stateIdPiaui}'),
        ('Olho d\`Água do Piauí', '${stateIdPiaui}'),
        ('Padre Marcos', '${stateIdPiaui}'),
        ('Paes Landim', '${stateIdPiaui}'),
        ('Pajeú do Piauí', '${stateIdPiaui}'),
        ('Palmeira do Piauí', '${stateIdPiaui}'),
        ('Palmeirais', '${stateIdPiaui}'),
        ('Paquetá', '${stateIdPiaui}'),
        ('Parnaguá', '${stateIdPiaui}'),
        ('Parnaíba', '${stateIdPiaui}'),
        ('Passagem Franca do Piauí', '${stateIdPiaui}'),
        ('Patos do Piauí', '${stateIdPiaui}'),
        ('Pau d\`Arco do Piauí', '${stateIdPiaui}'),
        ('Paulistana', '${stateIdPiaui}'),
        ('Pavussu', '${stateIdPiaui}'),
        ('Pedro II', '${stateIdPiaui}'),
        ('Pedro Laurentino', '${stateIdPiaui}'),
        ('Picos', '${stateIdPiaui}'),
        ('Pimenteiras', '${stateIdPiaui}'),
        ('Pio IX', '${stateIdPiaui}'),
        ('Piracuruca', '${stateIdPiaui}'),
        ('Piripiri', '${stateIdPiaui}'),
        ('Porto', '${stateIdPiaui}'),
        ('Porto Alegre do Piauí', '${stateIdPiaui}'),
        ('Prata do Piauí', '${stateIdPiaui}'),
        ('Queimada Nova', '${stateIdPiaui}'),
        ('Redenção do Gurguéia', '${stateIdPiaui}'),
        ('Regeneração', '${stateIdPiaui}'),
        ('Riacho Frio', '${stateIdPiaui}'),
        ('Ribeira do Piauí', '${stateIdPiaui}'),
        ('Ribeiro Gonçalves', '${stateIdPiaui}'),
        ('Rio Grande do Piauí', '${stateIdPiaui}'),
        ('Santa Cruz do Piauí', '${stateIdPiaui}'),
        ('Santa Cruz dos Milagres', '${stateIdPiaui}'),
        ('Santa Filomena', '${stateIdPiaui}'),
        ('Santa Luz', '${stateIdPiaui}'),
        ('Santa Rosa do Piauí', '${stateIdPiaui}'),
        ('Santana do Piauí', '${stateIdPiaui}'),
        ('Santo Antônio de Lisboa', '${stateIdPiaui}'),
        ('Santo Antônio dos Milagres', '${stateIdPiaui}'),
        ('Santo Inácio do Piauí', '${stateIdPiaui}'),
        ('São Braz do Piauí', '${stateIdPiaui}'),
        ('São Félix do Piauí', '${stateIdPiaui}'),
        ('São Francisco de Assis do Piauí', '${stateIdPiaui}'),
        ('São Francisco do Piauí', '${stateIdPiaui}'),
        ('São Gonçalo do Gurguéia', '${stateIdPiaui}'),
        ('São Gonçalo do Piauí', '${stateIdPiaui}'),
        ('São João da Canabrava', '${stateIdPiaui}'),
        ('São João da Fronteira', '${stateIdPiaui}'),
        ('São João da Serra', '${stateIdPiaui}'),
        ('São João da Varjota', '${stateIdPiaui}'),
        ('São João do Arraial', '${stateIdPiaui}'),
        ('São João do Piauí', '${stateIdPiaui}'),
        ('São José do Divino', '${stateIdPiaui}'),
        ('São José do Peixe', '${stateIdPiaui}'),
        ('São José do Piauí', '${stateIdPiaui}'),
        ('São Julião', '${stateIdPiaui}'),
        ('São Lourenço do Piauí', '${stateIdPiaui}'),
        ('São Luis do Piauí', '${stateIdPiaui}'),
        ('São Miguel da Baixa Grande', '${stateIdPiaui}'),
        ('São Miguel do Fidalgo', '${stateIdPiaui}'),
        ('São Miguel do Tapuio', '${stateIdPiaui}'),
        ('São Pedro do Piauí', '${stateIdPiaui}'),
        ('São Raimundo Nonato', '${stateIdPiaui}'),
        ('Sebastião Barros', '${stateIdPiaui}'),
        ('Sebastião Leal', '${stateIdPiaui}'),
        ('Sigefredo Pacheco', '${stateIdPiaui}'),
        ('Simões', '${stateIdPiaui}'),
        ('Simplício Mendes', '${stateIdPiaui}'),
        ('Socorro do Piauí', '${stateIdPiaui}'),
        ('Sussuapara', '${stateIdPiaui}'),
        ('Tamboril do Piauí', '${stateIdPiaui}'),
        ('Tanque do Piauí', '${stateIdPiaui}'),
        ('Teresina', '${stateIdPiaui}'),
        ('União', '${stateIdPiaui}'),
        ('Uruçuí', '${stateIdPiaui}'),
        ('Valença do Piauí', '${stateIdPiaui}'),
        ('Várzea Branca', '${stateIdPiaui}'),
        ('Várzea Grande', '${stateIdPiaui}'),
        ('Vera Mendes', '${stateIdPiaui}'),
        ('Vila Nova do Piauí', '${stateIdPiaui}'),
        ('Wall Ferraz', '${stateIdPiaui}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdPiaui = '1e95ac7f-c3d3-4e4c-b1b3-7d65ae8bb2fd';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdPiaui}';
    `);
  }
}
