import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateMatosGrosso1744502960984
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdMatoGrosso = '64a2b6c4-c020-4a86-b8a5-3fa92c0629fc';

    await queryRunner.query(`
      INSERT INTO cities (name, state_id) VALUES
        ('Acorizal', '${stateIdMatoGrosso}'),
        ('Água Boa', '${stateIdMatoGrosso}'),
        ('Alta Floresta', '${stateIdMatoGrosso}'),
        ('Alto Araguaia', '${stateIdMatoGrosso}'),
        ('Alto Boa Vista', '${stateIdMatoGrosso}'),
        ('Alto Garças', '${stateIdMatoGrosso}'),
        ('Alto Paraguai', '${stateIdMatoGrosso}'),
        ('Alto Taquari', '${stateIdMatoGrosso}'),
        ('Apiacás', '${stateIdMatoGrosso}'),
        ('Araguaiana', '${stateIdMatoGrosso}'),
        ('Araguainha', '${stateIdMatoGrosso}'),
        ('Araputanga', '${stateIdMatoGrosso}'),
        ('Arenápolis', '${stateIdMatoGrosso}'),
        ('Aripuanã', '${stateIdMatoGrosso}'),
        ('Barão de Melgaço', '${stateIdMatoGrosso}'),
        ('Barra do Bugres', '${stateIdMatoGrosso}'),
        ('Barra do Garças', '${stateIdMatoGrosso}'),
        ('Bom Jesus do Araguaia', '${stateIdMatoGrosso}'),
        ('Brasnorte', '${stateIdMatoGrosso}'),
        ('Cáceres', '${stateIdMatoGrosso}'),
        ('Campinápolis', '${stateIdMatoGrosso}'),
        ('Campo Novo do Parecis', '${stateIdMatoGrosso}'),
        ('Campo Verde', '${stateIdMatoGrosso}'),
        ('Campos de Júlio', '${stateIdMatoGrosso}'),
        ('Canabrava do Norte', '${stateIdMatoGrosso}'),
        ('Canarana', '${stateIdMatoGrosso}'),
        ('Carlinda', '${stateIdMatoGrosso}'),
        ('Castanheira', '${stateIdMatoGrosso}'),
        ('Chapada dos Guimarães', '${stateIdMatoGrosso}'),
        ('Cláudia', '${stateIdMatoGrosso}'),
        ('Cocalinho', '${stateIdMatoGrosso}'),
        ('Colíder', '${stateIdMatoGrosso}'),
        ('Colniza', '${stateIdMatoGrosso}'),
        ('Comodoro', '${stateIdMatoGrosso}'),
        ('Confresa', '${stateIdMatoGrosso}'),
        ('Conquista d''Oeste', '${stateIdMatoGrosso}'),
        ('Cotriguaçu', '${stateIdMatoGrosso}'),
        ('Cuiabá', '${stateIdMatoGrosso}'),
        ('Curvelândia', '${stateIdMatoGrosso}'),
        ('Denise', '${stateIdMatoGrosso}'),
        ('Diamantino', '${stateIdMatoGrosso}'),
        ('Dom Aquino', '${stateIdMatoGrosso}'),
        ('Feliz Natal', '${stateIdMatoGrosso}'),
        ('Figueirópolis d''Oeste', '${stateIdMatoGrosso}'),
        ('Gaúcha do Norte', '${stateIdMatoGrosso}'),
        ('General Carneiro', '${stateIdMatoGrosso}'),
        ('Glória d''Oeste', '${stateIdMatoGrosso}'),
        ('Guarantã do Norte', '${stateIdMatoGrosso}'),
        ('Guiratinga', '${stateIdMatoGrosso}'),
        ('Indiavaí', '${stateIdMatoGrosso}'),
        ('Ipiranga do Norte', '${stateIdMatoGrosso}'),
        ('Itanhangá', '${stateIdMatoGrosso}'),
        ('Itaúba', '${stateIdMatoGrosso}'),
        ('Itiquira', '${stateIdMatoGrosso}'),
        ('Jaciara', '${stateIdMatoGrosso}'),
        ('Jangada', '${stateIdMatoGrosso}'),
        ('Jauru', '${stateIdMatoGrosso}'),
        ('Juara', '${stateIdMatoGrosso}'),
        ('Juína', '${stateIdMatoGrosso}'),
        ('Juruena', '${stateIdMatoGrosso}'),
        ('Juscimeira', '${stateIdMatoGrosso}'),
        ('Lambari d''Oeste', '${stateIdMatoGrosso}'),
        ('Lucas do Rio Verde', '${stateIdMatoGrosso}'),
        ('Luciára', '${stateIdMatoGrosso}'),
        ('Marcelândia', '${stateIdMatoGrosso}'),
        ('Matupá', '${stateIdMatoGrosso}'),
        ('Mirassol d''Oeste', '${stateIdMatoGrosso}'),
        ('Nobres', '${stateIdMatoGrosso}'),
        ('Nortelândia', '${stateIdMatoGrosso}'),
        ('Nossa Senhora do Livramento', '${stateIdMatoGrosso}'),
        ('Nova Bandeirantes', '${stateIdMatoGrosso}'),
        ('Nova Brasilândia', '${stateIdMatoGrosso}'),
        ('Nova Canaã do Norte', '${stateIdMatoGrosso}'),
        ('Nova Guarita', '${stateIdMatoGrosso}'),
        ('Nova Lacerda', '${stateIdMatoGrosso}'),
        ('Nova Marilândia', '${stateIdMatoGrosso}'),
        ('Nova Maringá', '${stateIdMatoGrosso}'),
        ('Nova Monte verde', '${stateIdMatoGrosso}'),
        ('Nova Mutum', '${stateIdMatoGrosso}'),
        ('Nova Olímpia', '${stateIdMatoGrosso}'),
        ('Nova Santa Helena', '${stateIdMatoGrosso}'),
        ('Nova Ubiratã', '${stateIdMatoGrosso}'),
        ('Nova Xavantina', '${stateIdMatoGrosso}'),
        ('Novo Horizonte do Norte', '${stateIdMatoGrosso}'),
        ('Novo Mundo', '${stateIdMatoGrosso}'),
        ('Novo Santo Antônio', '${stateIdMatoGrosso}'),
        ('Novo São Joaquim', '${stateIdMatoGrosso}'),
        ('Paranaíta', '${stateIdMatoGrosso}'),
        ('Paranatinga', '${stateIdMatoGrosso}'),
        ('Pedra Preta', '${stateIdMatoGrosso}'),
        ('Peixoto de Azevedo', '${stateIdMatoGrosso}'),
        ('Planalto da Serra', '${stateIdMatoGrosso}'),
        ('Poconé', '${stateIdMatoGrosso}'),
        ('Pontal do Araguaia', '${stateIdMatoGrosso}'),
        ('Ponte Branca', '${stateIdMatoGrosso}'),
        ('Pontes e Lacerda', '${stateIdMatoGrosso}'),
        ('Porto Alegre do Norte', '${stateIdMatoGrosso}'),
        ('Porto dos Gaúchos', '${stateIdMatoGrosso}'),
        ('Porto Esperidião', '${stateIdMatoGrosso}'),
        ('Porto Estrela', '${stateIdMatoGrosso}'),
        ('Poxoréo', '${stateIdMatoGrosso}'),
        ('Primavera do Leste', '${stateIdMatoGrosso}'),
        ('Querência', '${stateIdMatoGrosso}'),
        ('Reserva do Cabaçal', '${stateIdMatoGrosso}'),
        ('Ribeirão Cascalheira', '${stateIdMatoGrosso}'),
        ('Ribeirãozinho', '${stateIdMatoGrosso}'),
        ('Rio Branco', '${stateIdMatoGrosso}'),
        ('Rondolândia', '${stateIdMatoGrosso}'),
        ('Rondonópolis', '${stateIdMatoGrosso}'),
        ('Rosário Oeste', '${stateIdMatoGrosso}'),
        ('Salto do Céu', '${stateIdMatoGrosso}'),
        ('Santa Carmem', '${stateIdMatoGrosso}'),
        ('Santa Cruz do Xingu', '${stateIdMatoGrosso}'),
        ('Santa Rita do Trivelato', '${stateIdMatoGrosso}'),
        ('Santa Terezinha', '${stateIdMatoGrosso}'),
        ('Santo Afonso', '${stateIdMatoGrosso}'),
        ('Santo Antônio do Leste', '${stateIdMatoGrosso}'),
        ('Santo Antônio do Leverger', '${stateIdMatoGrosso}'),
        ('São Félix do Araguaia', '${stateIdMatoGrosso}'),
        ('São José do Povo', '${stateIdMatoGrosso}'),
        ('São José do Rio Claro', '${stateIdMatoGrosso}'),
        ('São José do Xingu', '${stateIdMatoGrosso}'),
        ('São José dos Quatro Marcos', '${stateIdMatoGrosso}'),
        ('São Pedro da Cipa', '${stateIdMatoGrosso}'),
        ('Sapezal', '${stateIdMatoGrosso}'),
        ('Serra Nova Dourada', '${stateIdMatoGrosso}'),
        ('Sinop', '${stateIdMatoGrosso}'),
        ('Sorriso', '${stateIdMatoGrosso}'),
        ('Tabaporã', '${stateIdMatoGrosso}'),
        ('Tangará da Serra', '${stateIdMatoGrosso}'),
        ('Tapurah', '${stateIdMatoGrosso}'),
        ('Terra Nova do Norte', '${stateIdMatoGrosso}'),
        ('Tesouro', '${stateIdMatoGrosso}'),
        ('Torixoréu', '${stateIdMatoGrosso}'),
        ('União do Sul', '${stateIdMatoGrosso}'),
        ('Vale de São Domingos', '${stateIdMatoGrosso}'),
        ('Várzea Grande', '${stateIdMatoGrosso}'),
        ('Vera', '${stateIdMatoGrosso}'),
        ('Vila Bela da Santíssima Trindade', '${stateIdMatoGrosso}'),
        ('Vila Rica', '${stateIdMatoGrosso}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdMatoGrosso = '64a2b6c4-c020-4a86-b8a5-3fa92c0629fc';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdMatoGrosso}';
    `);
  }
}
