import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateMinasGerais1744498169014
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdMinasGerais = 'df6bc32a-92d4-4691-b8ba-ec3fa2b27c10';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Abadia dos Dourados', '${stateIdMinasGerais}'),
        ('Abaeté', '${stateIdMinasGerais}'),
        ('Abre Campo', '${stateIdMinasGerais}'),
        ('Acaiaca', '${stateIdMinasGerais}'),
        ('Açucena', '${stateIdMinasGerais}'),
        ('Água Boa', '${stateIdMinasGerais}'),
        ('Água Comprida', '${stateIdMinasGerais}'),
        ('Aguanil', '${stateIdMinasGerais}'),
        ('Águas Formosas', '${stateIdMinasGerais}'),
        ('Águas Vermelhas', '${stateIdMinasGerais}'),
        ('Aimorés', '${stateIdMinasGerais}'),
        ('Aiuruoca', '${stateIdMinasGerais}'),
        ('Alagoa', '${stateIdMinasGerais}'),
        ('Albertina', '${stateIdMinasGerais}'),
        ('Além Paraíba', '${stateIdMinasGerais}'),
        ('Alfenas', '${stateIdMinasGerais}'),
        ('Alfredo Vasconcelos', '${stateIdMinasGerais}'),
        ('Almenara', '${stateIdMinasGerais}'),
        ('Alpercata', '${stateIdMinasGerais}'),
        ('Alpinópolis', '${stateIdMinasGerais}'),
        ('Alterosa', '${stateIdMinasGerais}'),
        ('Alto Caparaó', '${stateIdMinasGerais}'),
        ('Alto Jequitibá', '${stateIdMinasGerais}'),
        ('Alto Rio Doce', '${stateIdMinasGerais}'),
        ('Alvarenga', '${stateIdMinasGerais}'),
        ('Alvinópolis', '${stateIdMinasGerais}'),
        ('Alvorada de Minas', '${stateIdMinasGerais}'),
        ('Amparo do Serra', '${stateIdMinasGerais}'),
        ('Andradas', '${stateIdMinasGerais}'),
        ('Andrelândia', '${stateIdMinasGerais}'),
        ('Angelândia', '${stateIdMinasGerais}'),
        ('Antônio Carlos', '${stateIdMinasGerais}'),
        ('Antônio Dias', '${stateIdMinasGerais}'),
        ('Antônio Prado de Minas', '${stateIdMinasGerais}'),
        ('Araçaí', '${stateIdMinasGerais}'),
        ('Aracitaba', '${stateIdMinasGerais}'),
        ('Araçuaí', '${stateIdMinasGerais}'),
        ('Araguari', '${stateIdMinasGerais}'),
        ('Arantina', '${stateIdMinasGerais}'),
        ('Araponga', '${stateIdMinasGerais}'),
        ('Araporã', '${stateIdMinasGerais}'),
        ('Arapuá', '${stateIdMinasGerais}'),
        ('Araújos', '${stateIdMinasGerais}'),
        ('Araxá', '${stateIdMinasGerais}'),
        ('Arceburgo', '${stateIdMinasGerais}'),
        ('Arcos', '${stateIdMinasGerais}'),
        ('Areado', '${stateIdMinasGerais}'),
        ('Argirita', '${stateIdMinasGerais}'),
        ('Aricanduva', '${stateIdMinasGerais}'),
        ('Arinos', '${stateIdMinasGerais}'),
        ('Astolfo Dutra', '${stateIdMinasGerais}'),
        ('Ataléia', '${stateIdMinasGerais}'),
        ('Augusto de Lima', '${stateIdMinasGerais}'),
        ('Baependi', '${stateIdMinasGerais}'),
        ('Baldim', '${stateIdMinasGerais}'),
        ('Bambuí', '${stateIdMinasGerais}'),
        ('Bandeira', '${stateIdMinasGerais}'),
        ('Bandeira do Sul', '${stateIdMinasGerais}'),
        ('Barão de Cocais', '${stateIdMinasGerais}'),
        ('Barão de Monte Alto', '${stateIdMinasGerais}'),
        ('Barbacena', '${stateIdMinasGerais}'),
        ('Barra Longa', '${stateIdMinasGerais}'),
        ('Barroso', '${stateIdMinasGerais}'),
        ('Bela Vista de Minas', '${stateIdMinasGerais}'),
        ('Belmiro Braga', '${stateIdMinasGerais}'),
        ('Belo Horizonte', '${stateIdMinasGerais}'),
        ('Belo Oriente', '${stateIdMinasGerais}'),
        ('Belo Vale', '${stateIdMinasGerais}'),
        ('Berilo', '${stateIdMinasGerais}'),
        ('Berizal', '${stateIdMinasGerais}'),
        ('Bertópolis', '${stateIdMinasGerais}'),
        ('Betim', '${stateIdMinasGerais}'),
        ('Bias Fortes', '${stateIdMinasGerais}'),
        ('Bicas', '${stateIdMinasGerais}'),
        ('Biquinhas', '${stateIdMinasGerais}'),
        ('Boa Esperança', '${stateIdMinasGerais}'),
        ('Bocaina de Minas', '${stateIdMinasGerais}'),
        ('Bocaiúva', '${stateIdMinasGerais}'),
        ('Bom Despacho', '${stateIdMinasGerais}'),
        ('Bom Jardim de Minas', '${stateIdMinasGerais}'),
        ('Bom Jesus da Penha', '${stateIdMinasGerais}'),
        ('Bom Jesus do Amparo', '${stateIdMinasGerais}'),
        ('Bom Jesus do Galho', '${stateIdMinasGerais}'),
        ('Bom Repouso', '${stateIdMinasGerais}'),
        ('Bom Sucesso', '${stateIdMinasGerais}'),
        ('Bonfim', '${stateIdMinasGerais}'),
        ('Bonfinópolis de Minas', '${stateIdMinasGerais}'),
        ('Bonito de Minas', '${stateIdMinasGerais}'),
        ('Borda da Mata', '${stateIdMinasGerais}'),
        ('Botelhos', '${stateIdMinasGerais}'),
        ('Botumirim', '${stateIdMinasGerais}'),
        ('Brás Pires', '${stateIdMinasGerais}'),
        ('Brasilândia de Minas', '${stateIdMinasGerais}'),
        ('Brasília de Minas', '${stateIdMinasGerais}'),
        ('Brasópolis', '${stateIdMinasGerais}'),
        ('Braúnas', '${stateIdMinasGerais}'),
        ('Brumadinho', '${stateIdMinasGerais}'),
        ('Bueno Brandão', '${stateIdMinasGerais}'),
        ('Buenópolis', '${stateIdMinasGerais}'),
        ('Bugre', '${stateIdMinasGerais}'),
        ('Buritis', '${stateIdMinasGerais}'),
        ('Buritizeiro', '${stateIdMinasGerais}'),
        ('Cabeceira Grande', '${stateIdMinasGerais}'),
        ('Cabo Verde', '${stateIdMinasGerais}'),
        ('Cachoeira da Prata', '${stateIdMinasGerais}'),
        ('Cachoeira de Minas', '${stateIdMinasGerais}'),
        ('Cachoeira de Pajeú', '${stateIdMinasGerais}'),
        ('Cachoeira Dourada', '${stateIdMinasGerais}'),
        ('Caetanópolis', '${stateIdMinasGerais}'),
        ('Caeté', '${stateIdMinasGerais}'),
        ('Caiana', '${stateIdMinasGerais}'),
        ('Cajuri', '${stateIdMinasGerais}'),
        ('Caldas', '${stateIdMinasGerais}'),
        ('Camacho', '${stateIdMinasGerais}'),
        ('Camanducaia', '${stateIdMinasGerais}'),
        ('Cambuí', '${stateIdMinasGerais}'),
        ('Cambuquira', '${stateIdMinasGerais}'),
        ('Campanário', '${stateIdMinasGerais}'),
        ('Campanha', '${stateIdMinasGerais}'),
        ('Campestre', '${stateIdMinasGerais}'),
        ('Campina Verde', '${stateIdMinasGerais}'),
        ('Campo Azul', '${stateIdMinasGerais}'),
        ('Campo Belo', '${stateIdMinasGerais}'),
        ('Campo do Meio', '${stateIdMinasGerais}'),
        ('Campo Florido', '${stateIdMinasGerais}'),
        ('Campos Altos', '${stateIdMinasGerais}'),
        ('Campos Gerais', '${stateIdMinasGerais}'),
        ('Cana Verde', '${stateIdMinasGerais}'),
        ('Canaã', '${stateIdMinasGerais}'),
        ('Canápolis', '${stateIdMinasGerais}'),
        ('Candeias', '${stateIdMinasGerais}'),
        ('Cantagalo', '${stateIdMinasGerais}'),
        ('Caparaó', '${stateIdMinasGerais}'),
        ('Capela Nova', '${stateIdMinasGerais}'),
        ('Capelinha', '${stateIdMinasGerais}'),
        ('Capetinga', '${stateIdMinasGerais}'),
        ('Capim Branco', '${stateIdMinasGerais}'),
        ('Capinópolis', '${stateIdMinasGerais}'),
        ('Capitão Andrade', '${stateIdMinasGerais}'),
        ('Capitão Enéas', '${stateIdMinasGerais}'),
        ('Capitólio', '${stateIdMinasGerais}'),
        ('Caputira', '${stateIdMinasGerais}'),
        ('Caraí', '${stateIdMinasGerais}'),
        ('Caranaíba', '${stateIdMinasGerais}'),
        ('Carandaí', '${stateIdMinasGerais}'),
        ('Carangola', '${stateIdMinasGerais}'),
        ('Caratinga', '${stateIdMinasGerais}'),
        ('Carbonita', '${stateIdMinasGerais}'),
        ('Careaçu', '${stateIdMinasGerais}'),
        ('Carlos Chagas', '${stateIdMinasGerais}'),
        ('Carmésia', '${stateIdMinasGerais}'),
        ('Carmo da Cachoeira', '${stateIdMinasGerais}'),
        ('Carmo da Mata', '${stateIdMinasGerais}'),
        ('Carmo de Minas', '${stateIdMinasGerais}'),
        ('Carmo do Cajuru', '${stateIdMinasGerais}'),
        ('Carmo do Paranaíba', '${stateIdMinasGerais}'),
        ('Carmo do Rio Claro', '${stateIdMinasGerais}'),
        ('Carmópolis de Minas', '${stateIdMinasGerais}'),
        ('Carneirinho', '${stateIdMinasGerais}'),
        ('Carrancas', '${stateIdMinasGerais}'),
        ('Carvalhópolis', '${stateIdMinasGerais}'),
        ('Carvalhos', '${stateIdMinasGerais}'),
        ('Casa Grande', '${stateIdMinasGerais}'),
        ('Cascalho Rico', '${stateIdMinasGerais}'),
        ('Cássia', '${stateIdMinasGerais}'),
        ('Cataguases', '${stateIdMinasGerais}'),
        ('Catas Altas', '${stateIdMinasGerais}'),
        ('Catas Altas da Noruega', '${stateIdMinasGerais}'),
        ('Catuji', '${stateIdMinasGerais}'),
        ('Catuti', '${stateIdMinasGerais}'),
        ('Caxambu', '${stateIdMinasGerais}'),
        ('Cedro do Abaeté', '${stateIdMinasGerais}'),
        ('Central de Minas', '${stateIdMinasGerais}'),
        ('Centralina', '${stateIdMinasGerais}'),
        ('Chácara', '${stateIdMinasGerais}'),
        ('Chalé', '${stateIdMinasGerais}'),
        ('Chapada do Norte', '${stateIdMinasGerais}'),
        ('Chapada Gaúcha', '${stateIdMinasGerais}'),
        ('Chiador', '${stateIdMinasGerais}'),
        ('Cipotânea', '${stateIdMinasGerais}'),
        ('Claraval', '${stateIdMinasGerais}'),
        ('Claro dos Poções', '${stateIdMinasGerais}'),
        ('Cláudio', '${stateIdMinasGerais}'),
        ('Coimbra', '${stateIdMinasGerais}'),
        ('Coluna', '${stateIdMinasGerais}'),
        ('Comendador Gomes', '${stateIdMinasGerais}'),
        ('Comercinho', '${stateIdMinasGerais}'),
        ('Conceição da Aparecida', '${stateIdMinasGerais}'),
        ('Conceição da Barra de Minas', '${stateIdMinasGerais}'),
        ('Conceição das Alagoas', '${stateIdMinasGerais}'),
        ('Conceição das Pedras', '${stateIdMinasGerais}'),
        ('Conceição de Ipanema', '${stateIdMinasGerais}'),
        ('Conceição do Mato Dentro', '${stateIdMinasGerais}'),
        ('Conceição do Pará', '${stateIdMinasGerais}'),
        ('Conceição do Rio Verde', '${stateIdMinasGerais}'),
        ('Conceição dos Ouros', '${stateIdMinasGerais}'),
        ('Cônego Marinho', '${stateIdMinasGerais}'),
        ('Confins', '${stateIdMinasGerais}'),
        ('Congonhal', '${stateIdMinasGerais}'),
        ('Congonhas', '${stateIdMinasGerais}'),
        ('Congonhas do Norte', '${stateIdMinasGerais}'),
        ('Conquista', '${stateIdMinasGerais}'),
        ('Conselheiro Lafaiete', '${stateIdMinasGerais}'),
        ('Conselheiro Pena', '${stateIdMinasGerais}'),
        ('Consolação', '${stateIdMinasGerais}'),
        ('Contagem', '${stateIdMinasGerais}'),
        ('Coqueiral', '${stateIdMinasGerais}'),
        ('Coração de Jesus', '${stateIdMinasGerais}'),
        ('Cordisburgo', '${stateIdMinasGerais}'),
        ('Cordislândia', '${stateIdMinasGerais}'),
        ('Corinto', '${stateIdMinasGerais}'),
        ('Coroaci', '${stateIdMinasGerais}'),
        ('Coromandel', '${stateIdMinasGerais}'),
        ('Coronel Fabriciano', '${stateIdMinasGerais}'),
        ('Coronel Murta', '${stateIdMinasGerais}'),
        ('Coronel Pacheco', '${stateIdMinasGerais}'),
        ('Coronel Xavier Chaves', '${stateIdMinasGerais}'),
        ('Córrego Danta', '${stateIdMinasGerais}'),
        ('Córrego do Bom Jesus', '${stateIdMinasGerais}'),
        ('Córrego Fundo', '${stateIdMinasGerais}'),
        ('Córrego Novo', '${stateIdMinasGerais}'),
        ('Couto de Magalhães de Minas', '${stateIdMinasGerais}'),
        ('Crisólita', '${stateIdMinasGerais}'),
        ('Cristais', '${stateIdMinasGerais}'),
        ('Cristália', '${stateIdMinasGerais}'),
        ('Cristiano Otoni', '${stateIdMinasGerais}'),
        ('Cristina', '${stateIdMinasGerais}'),
        ('Crucilândia', '${stateIdMinasGerais}'),
        ('Cruzeiro da Fortaleza', '${stateIdMinasGerais}'),
        ('Cruzília', '${stateIdMinasGerais}'),
        ('Cuparaque', '${stateIdMinasGerais}'),
        ('Curral de Dentro', '${stateIdMinasGerais}'),
        ('Curvelo', '${stateIdMinasGerais}'),
        ('Datas', '${stateIdMinasGerais}'),
        ('Delfim Moreira', '${stateIdMinasGerais}'),
        ('Delfinópolis', '${stateIdMinasGerais}'),
        ('Delta', '${stateIdMinasGerais}'),
        ('Descoberto', '${stateIdMinasGerais}'),
        ('Desterro de Entre Rios', '${stateIdMinasGerais}'),
        ('Desterro do Melo', '${stateIdMinasGerais}'),
        ('Diamantina', '${stateIdMinasGerais}'),
        ('Diogo de Vasconcelos', '${stateIdMinasGerais}'),
        ('Dionísio', '${stateIdMinasGerais}'),
        ('Divinésia', '${stateIdMinasGerais}'),
        ('Divino', '${stateIdMinasGerais}'),
        ('Divino das Laranjeiras', '${stateIdMinasGerais}'),
        ('Divinolândia de Minas', '${stateIdMinasGerais}'),
        ('Divinópolis', '${stateIdMinasGerais}'),
        ('Divisa Alegre', '${stateIdMinasGerais}'),
        ('Divisa Nova', '${stateIdMinasGerais}'),
        ('Divisópolis', '${stateIdMinasGerais}'),
        ('Dom Bosco', '${stateIdMinasGerais}'),
        ('Dom Cavati', '${stateIdMinasGerais}'),
        ('Dom Joaquim', '${stateIdMinasGerais}'),
        ('Dom Silvério', '${stateIdMinasGerais}'),
        ('Dom Viçoso', '${stateIdMinasGerais}'),
        ('Dona Eusébia', '${stateIdMinasGerais}'),
        ('Dores de Campos', '${stateIdMinasGerais}'),
        ('Dores de Guanhães', '${stateIdMinasGerais}'),
        ('Dores do Indaiá', '${stateIdMinasGerais}'),
        ('Dores do Turvo', '${stateIdMinasGerais}'),
        ('Doresópolis', '${stateIdMinasGerais}'),
        ('Douradoquara', '${stateIdMinasGerais}'),
        ('Durandé', '${stateIdMinasGerais}'),
        ('Elói Mendes', '${stateIdMinasGerais}'),
        ('Engenheiro Caldas', '${stateIdMinasGerais}'),
        ('Engenheiro Navarro', '${stateIdMinasGerais}'),
        ('Entre Folhas', '${stateIdMinasGerais}'),
        ('Entre Rios de Minas', '${stateIdMinasGerais}'),
        ('Ervália', '${stateIdMinasGerais}'),
        ('Esmeraldas', '${stateIdMinasGerais}'),
        ('Espera Feliz', '${stateIdMinasGerais}'),
        ('Espinosa', '${stateIdMinasGerais}'),
        ('Espírito Santo do Dourado', '${stateIdMinasGerais}'),
        ('Estiva', '${stateIdMinasGerais}'),
        ('Estrela Dalva', '${stateIdMinasGerais}'),
        ('Estrela do Indaiá', '${stateIdMinasGerais}'),
        ('Estrela do Sul', '${stateIdMinasGerais}'),
        ('Eugenópolis', '${stateIdMinasGerais}'),
        ('Ewbank da Câmara', '${stateIdMinasGerais}'),
        ('Extrema', '${stateIdMinasGerais}'),
        ('Fama', '${stateIdMinasGerais}'),
        ('Faria Lemos', '${stateIdMinasGerais}'),
        ('Felício dos Santos', '${stateIdMinasGerais}'),
        ('Felisburgo', '${stateIdMinasGerais}'),
        ('Felixlândia', '${stateIdMinasGerais}'),
        ('Fernandes Tourinho', '${stateIdMinasGerais}'),
        ('Ferros', '${stateIdMinasGerais}'),
        ('Fervedouro', '${stateIdMinasGerais}'),
        ('Florestal', '${stateIdMinasGerais}'),
        ('Formiga', '${stateIdMinasGerais}'),
        ('Formoso', '${stateIdMinasGerais}'),
        ('Fortaleza de Minas', '${stateIdMinasGerais}'),
        ('Fortuna de Minas', '${stateIdMinasGerais}'),
        ('Francisco Badaró', '${stateIdMinasGerais}'),
        ('Francisco Dumont', '${stateIdMinasGerais}'),
        ('Francisco Sá', '${stateIdMinasGerais}'),
        ('Franciscópolis', '${stateIdMinasGerais}'),
        ('Frei Gaspar', '${stateIdMinasGerais}'),
        ('Frei Inocêncio', '${stateIdMinasGerais}'),
        ('Frei Lagonegro', '${stateIdMinasGerais}'),
        ('Fronteira', '${stateIdMinasGerais}'),
        ('Fronteira dos Vales', '${stateIdMinasGerais}'),
        ('Fruta de Leite', '${stateIdMinasGerais}'),
        ('Frutal', '${stateIdMinasGerais}'),
        ('Funilândia', '${stateIdMinasGerais}'),
        ('Galiléia', '${stateIdMinasGerais}'),
        ('Gameleiras', '${stateIdMinasGerais}'),
        ('Glaucilândia', '${stateIdMinasGerais}'),
        ('Goiabeira', '${stateIdMinasGerais}'),
        ('Goianá', '${stateIdMinasGerais}'),
        ('Gonçalves', '${stateIdMinasGerais}'),
        ('Gonzaga', '${stateIdMinasGerais}'),
        ('Gouveia', '${stateIdMinasGerais}'),
        ('Governador Valadares', '${stateIdMinasGerais}'),
        ('Grão Mogol', '${stateIdMinasGerais}'),
        ('Grupiara', '${stateIdMinasGerais}'),
        ('Guanhães', '${stateIdMinasGerais}'),
        ('Guapé', '${stateIdMinasGerais}'),
        ('Guaraciaba', '${stateIdMinasGerais}'),
        ('Guaraciama', '${stateIdMinasGerais}'),
        ('Guaranésia', '${stateIdMinasGerais}'),
        ('Guarani', '${stateIdMinasGerais}'),
        ('Guarará', '${stateIdMinasGerais}'),
        ('Guarda-Mor', '${stateIdMinasGerais}'),
        ('Guaxupé', '${stateIdMinasGerais}'),
        ('Guidoval', '${stateIdMinasGerais}'),
        ('Guimarânia', '${stateIdMinasGerais}'),
        ('Guiricema', '${stateIdMinasGerais}'),
        ('Gurinhatã', '${stateIdMinasGerais}'),
        ('Heliodora', '${stateIdMinasGerais}'),
        ('Iapu', '${stateIdMinasGerais}'),
        ('Ibertioga', '${stateIdMinasGerais}'),
        ('Ibiá', '${stateIdMinasGerais}'),
        ('Ibiaí', '${stateIdMinasGerais}'),
        ('Ibiracatu', '${stateIdMinasGerais}'),
        ('Ibiraci', '${stateIdMinasGerais}'),
        ('Ibirité', '${stateIdMinasGerais}'),
        ('Ibitiúra de Minas', '${stateIdMinasGerais}'),
        ('Ibituruna', '${stateIdMinasGerais}'),
        ('Icaraí de Minas', '${stateIdMinasGerais}'),
        ('Igarapé', '${stateIdMinasGerais}'),
        ('Igaratinga', '${stateIdMinasGerais}'),
        ('Iguatama', '${stateIdMinasGerais}'),
        ('Ijaci', '${stateIdMinasGerais}'),
        ('Ilicínea', '${stateIdMinasGerais}'),
        ('Imbé de Minas', '${stateIdMinasGerais}'),
        ('Inconfidentes', '${stateIdMinasGerais}'),
        ('Indaiabira', '${stateIdMinasGerais}'),
        ('Indianópolis', '${stateIdMinasGerais}'),
        ('Ingaí', '${stateIdMinasGerais}'),
        ('Inhapim', '${stateIdMinasGerais}'),
        ('Inhaúma', '${stateIdMinasGerais}'),
        ('Inimutaba', '${stateIdMinasGerais}'),
        ('Ipaba', '${stateIdMinasGerais}'),
        ('Ipanema', '${stateIdMinasGerais}'),
        ('Ipatinga', '${stateIdMinasGerais}'),
        ('Ipiaçu', '${stateIdMinasGerais}'),
        ('Ipuiúna', '${stateIdMinasGerais}'),
        ('Iraí de Minas', '${stateIdMinasGerais}'),
        ('Itabira', '${stateIdMinasGerais}'),
        ('Itabirinha de Mantena', '${stateIdMinasGerais}'),
        ('Itabirito', '${stateIdMinasGerais}'),
        ('Itacambira', '${stateIdMinasGerais}'),
        ('Itacarambi', '${stateIdMinasGerais}'),
        ('Itaguara', '${stateIdMinasGerais}'),
        ('Itaipé', '${stateIdMinasGerais}'),
        ('Itajubá', '${stateIdMinasGerais}'),
        ('Itamarandiba', '${stateIdMinasGerais}'),
        ('Itamarati de Minas', '${stateIdMinasGerais}'),
        ('Itambacuri', '${stateIdMinasGerais}'),
        ('Itambé do Mato Dentro', '${stateIdMinasGerais}'),
        ('Itamogi', '${stateIdMinasGerais}'),
        ('Itamonte', '${stateIdMinasGerais}'),
        ('Itanhandu', '${stateIdMinasGerais}'),
        ('Itanhomi', '${stateIdMinasGerais}'),
        ('Itaobim', '${stateIdMinasGerais}'),
        ('Itapagipe', '${stateIdMinasGerais}'),
        ('Itapecerica', '${stateIdMinasGerais}'),
        ('Itapeva', '${stateIdMinasGerais}'),
        ('Itatiaiuçu', '${stateIdMinasGerais}'),
        ('Itaú de Minas', '${stateIdMinasGerais}'),
        ('Itaúna', '${stateIdMinasGerais}'),
        ('Itaverava', '${stateIdMinasGerais}'),
        ('Itinga', '${stateIdMinasGerais}'),
        ('Itueta', '${stateIdMinasGerais}'),
        ('Ituiutaba', '${stateIdMinasGerais}'),
        ('Itumirim', '${stateIdMinasGerais}'),
        ('Iturama', '${stateIdMinasGerais}'),
        ('Itutinga', '${stateIdMinasGerais}'),
        ('Jaboticatubas', '${stateIdMinasGerais}'),
        ('Jacinto', '${stateIdMinasGerais}'),
        ('Jacuí', '${stateIdMinasGerais}'),
        ('Jacutinga', '${stateIdMinasGerais}'),
        ('Jaguaraçu', '${stateIdMinasGerais}'),
        ('Jaíba', '${stateIdMinasGerais}'),
        ('Jampruca', '${stateIdMinasGerais}'),
        ('Janaúba', '${stateIdMinasGerais}'),
        ('Januária', '${stateIdMinasGerais}'),
        ('Japaraíba', '${stateIdMinasGerais}'),
        ('Japonvar', '${stateIdMinasGerais}'),
        ('Jeceaba', '${stateIdMinasGerais}'),
        ('Jenipapo de Minas', '${stateIdMinasGerais}'),
        ('Jequeri', '${stateIdMinasGerais}'),
        ('Jequitaí', '${stateIdMinasGerais}'),
        ('Jequitibá', '${stateIdMinasGerais}'),
        ('Jequitinhonha', '${stateIdMinasGerais}'),
        ('Jesuânia', '${stateIdMinasGerais}'),
        ('Joaíma', '${stateIdMinasGerais}'),
        ('Joanésia', '${stateIdMinasGerais}'),
        ('João Monlevade', '${stateIdMinasGerais}'),
        ('João Pinheiro', '${stateIdMinasGerais}'),
        ('Joaquim Felício', '${stateIdMinasGerais}'),
        ('Jordânia', '${stateIdMinasGerais}'),
        ('José Gonçalves de Minas', '${stateIdMinasGerais}'),
        ('José Raydan', '${stateIdMinasGerais}'),
        ('Josenópolis', '${stateIdMinasGerais}'),
        ('Juatuba', '${stateIdMinasGerais}'),
        ('Juiz de Fora', '${stateIdMinasGerais}'),
        ('Juramento', '${stateIdMinasGerais}'),
        ('Juruaia', '${stateIdMinasGerais}'),
        ('Juvenília', '${stateIdMinasGerais}'),
        ('Ladainha', '${stateIdMinasGerais}'),
        ('Lagamar', '${stateIdMinasGerais}'),
        ('Lagoa da Prata', '${stateIdMinasGerais}'),
        ('Lagoa dos Patos', '${stateIdMinasGerais}'),
        ('Lagoa Dourada', '${stateIdMinasGerais}'),
        ('Lagoa Formosa', '${stateIdMinasGerais}'),
        ('Lagoa Grande', '${stateIdMinasGerais}'),
        ('Lagoa Santa', '${stateIdMinasGerais}'),
        ('Lajinha', '${stateIdMinasGerais}'),
        ('Lambari', '${stateIdMinasGerais}'),
        ('Lamim', '${stateIdMinasGerais}'),
        ('Laranjal', '${stateIdMinasGerais}'),
        ('Lassance', '${stateIdMinasGerais}'),
        ('Lavras', '${stateIdMinasGerais}'),
        ('Leandro Ferreira', '${stateIdMinasGerais}'),
        ('Leme do Prado', '${stateIdMinasGerais}'),
        ('Leopoldina', '${stateIdMinasGerais}'),
        ('Liberdade', '${stateIdMinasGerais}'),
        ('Lima Duarte', '${stateIdMinasGerais}'),
        ('Limeira do Oeste', '${stateIdMinasGerais}'),
        ('Lontra', '${stateIdMinasGerais}'),
        ('Luisburgo', '${stateIdMinasGerais}'),
        ('Luislândia', '${stateIdMinasGerais}'),
        ('Luminárias', '${stateIdMinasGerais}'),
        ('Luz', '${stateIdMinasGerais}'),
        ('Machacalis', '${stateIdMinasGerais}'),
        ('Machado', '${stateIdMinasGerais}'),
        ('Madre de Deus de Minas', '${stateIdMinasGerais}'),
        ('Malacacheta', '${stateIdMinasGerais}'),
        ('Mamonas', '${stateIdMinasGerais}'),
        ('Manga', '${stateIdMinasGerais}'),
        ('Manhuaçu', '${stateIdMinasGerais}'),
        ('Manhumirim', '${stateIdMinasGerais}'),
        ('Mantena', '${stateIdMinasGerais}'),
        ('Mar de Espanha', '${stateIdMinasGerais}'),
        ('Maravilhas', '${stateIdMinasGerais}'),
        ('Maria da Fé', '${stateIdMinasGerais}'),
        ('Mariana', '${stateIdMinasGerais}'),
        ('Marilac', '${stateIdMinasGerais}'),
        ('Mário Campos', '${stateIdMinasGerais}'),
        ('Maripá de Minas', '${stateIdMinasGerais}'),
        ('Marliéria', '${stateIdMinasGerais}'),
        ('Marmelópolis', '${stateIdMinasGerais}'),
        ('Martinho Campos', '${stateIdMinasGerais}'),
        ('Martins Soares', '${stateIdMinasGerais}'),
        ('Mata Verde', '${stateIdMinasGerais}'),
        ('Materlândia', '${stateIdMinasGerais}'),
        ('Mateus Leme', '${stateIdMinasGerais}'),
        ('Mathias Lobato', '${stateIdMinasGerais}'),
        ('Matias Barbosa', '${stateIdMinasGerais}'),
        ('Matias Cardoso', '${stateIdMinasGerais}'),
        ('Matipó', '${stateIdMinasGerais}'),
        ('Mato Verde', '${stateIdMinasGerais}'),
        ('Matozinhos', '${stateIdMinasGerais}'),
        ('Matutina', '${stateIdMinasGerais}'),
        ('Medeiros', '${stateIdMinasGerais}'),
        ('Medina', '${stateIdMinasGerais}'),
        ('Mendes Pimentel', '${stateIdMinasGerais}'),
        ('Mercês', '${stateIdMinasGerais}'),
        ('Mesquita', '${stateIdMinasGerais}'),
        ('Minas Novas', '${stateIdMinasGerais}'),
        ('Minduri', '${stateIdMinasGerais}'),
        ('Mirabela', '${stateIdMinasGerais}'),
        ('Miradouro', '${stateIdMinasGerais}'),
        ('Miraí', '${stateIdMinasGerais}'),
        ('Miravânia', '${stateIdMinasGerais}'),
        ('Moeda', '${stateIdMinasGerais}'),
        ('Moema', '${stateIdMinasGerais}'),
        ('Monjolos', '${stateIdMinasGerais}'),
        ('Monsenhor Paulo', '${stateIdMinasGerais}'),
        ('Montalvânia', '${stateIdMinasGerais}'),
        ('Monte Alegre de Minas', '${stateIdMinasGerais}'),
        ('Monte Azul', '${stateIdMinasGerais}'),
        ('Monte Belo', '${stateIdMinasGerais}'),
        ('Monte Carmelo', '${stateIdMinasGerais}'),
        ('Monte Formoso', '${stateIdMinasGerais}'),
        ('Monte Santo de Minas', '${stateIdMinasGerais}'),
        ('Monte Sião', '${stateIdMinasGerais}'),
        ('Montes Claros', '${stateIdMinasGerais}'),
        ('Montezuma', '${stateIdMinasGerais}'),
        ('Morada Nova de Minas', '${stateIdMinasGerais}'),
        ('Morro da Garça', '${stateIdMinasGerais}'),
        ('Morro do Pilar', '${stateIdMinasGerais}'),
        ('Munhoz', '${stateIdMinasGerais}'),
        ('Muriaé', '${stateIdMinasGerais}'),
        ('Mutum', '${stateIdMinasGerais}'),
        ('Muzambinho', '${stateIdMinasGerais}'),
        ('Nacip Raydan', '${stateIdMinasGerais}'),
        ('Nanuque', '${stateIdMinasGerais}'),
        ('Naque', '${stateIdMinasGerais}'),
        ('Natalândia', '${stateIdMinasGerais}'),
        ('Natércia', '${stateIdMinasGerais}'),
        ('Nazareno', '${stateIdMinasGerais}'),
        ('Nepomuceno', '${stateIdMinasGerais}'),
        ('Ninheira', '${stateIdMinasGerais}'),
        ('Nova Belém', '${stateIdMinasGerais}'),
        ('Nova Era', '${stateIdMinasGerais}'),
        ('Nova Lima', '${stateIdMinasGerais}'),
        ('Nova Módica', '${stateIdMinasGerais}'),
        ('Nova Ponte', '${stateIdMinasGerais}'),
        ('Nova Porteirinha', '${stateIdMinasGerais}'),
        ('Nova Resende', '${stateIdMinasGerais}'),
        ('Nova Serrana', '${stateIdMinasGerais}'),
        ('Nova União', '${stateIdMinasGerais}'),
        ('Novo Cruzeiro', '${stateIdMinasGerais}'),
        ('Novo Oriente de Minas', '${stateIdMinasGerais}'),
        ('Novorizonte', '${stateIdMinasGerais}'),
        ('Olaria', '${stateIdMinasGerais}'),
        ('Olhos-d\`Água', '${stateIdMinasGerais}'),
        ('Olímpio Noronha', '${stateIdMinasGerais}'),
        ('Oliveira', '${stateIdMinasGerais}'),
        ('Oliveira Fortes', '${stateIdMinasGerais}'),
        ('Onça de Pitangui', '${stateIdMinasGerais}'),
        ('Oratórios', '${stateIdMinasGerais}'),
        ('Orizânia', '${stateIdMinasGerais}'),
        ('Ouro Branco', '${stateIdMinasGerais}'),
        ('Ouro Fino', '${stateIdMinasGerais}'),
        ('Ouro Preto', '${stateIdMinasGerais}'),
        ('Ouro Verde de Minas', '${stateIdMinasGerais}'),
        ('Padre Carvalho', '${stateIdMinasGerais}'),
        ('Padre Paraíso', '${stateIdMinasGerais}'),
        ('Pai Pedro', '${stateIdMinasGerais}'),
        ('Paineiras', '${stateIdMinasGerais}'),
        ('Pains', '${stateIdMinasGerais}'),
        ('Paiva', '${stateIdMinasGerais}'),
        ('Palma', '${stateIdMinasGerais}'),
        ('Palmópolis', '${stateIdMinasGerais}'),
        ('Papagaios', '${stateIdMinasGerais}'),
        ('Pará de Minas', '${stateIdMinasGerais}'),
        ('Paracatu', '${stateIdMinasGerais}'),
        ('Paraguaçu', '${stateIdMinasGerais}'),
        ('Paraisópolis', '${stateIdMinasGerais}'),
        ('Paraopeba', '${stateIdMinasGerais}'),
        ('Passa Quatro', '${stateIdMinasGerais}'),
        ('Passa Tempo', '${stateIdMinasGerais}'),
        ('Passabém', '${stateIdMinasGerais}'),
        ('Passa-Vinte', '${stateIdMinasGerais}'),
        ('Passos', '${stateIdMinasGerais}'),
        ('Patis', '${stateIdMinasGerais}'),
        ('Patos de Minas', '${stateIdMinasGerais}'),
        ('Patrocínio', '${stateIdMinasGerais}'),
        ('Patrocínio do Muriaé', '${stateIdMinasGerais}'),
        ('Paula Cândido', '${stateIdMinasGerais}'),
        ('Paulistas', '${stateIdMinasGerais}'),
        ('Pavão', '${stateIdMinasGerais}'),
        ('Peçanha', '${stateIdMinasGerais}'),
        ('Pedra Azul', '${stateIdMinasGerais}'),
        ('Pedra Bonita', '${stateIdMinasGerais}'),
        ('Pedra do Anta', '${stateIdMinasGerais}'),
        ('Pedra do Indaiá', '${stateIdMinasGerais}'),
        ('Pedra Dourada', '${stateIdMinasGerais}'),
        ('Pedralva', '${stateIdMinasGerais}'),
        ('Pedras de Maria da Cruz', '${stateIdMinasGerais}'),
        ('Pedrinópolis', '${stateIdMinasGerais}'),
        ('Pedro Leopoldo', '${stateIdMinasGerais}'),
        ('Pedro Teixeira', '${stateIdMinasGerais}'),
        ('Pequeri', '${stateIdMinasGerais}'),
        ('Pequi', '${stateIdMinasGerais}'),
        ('Perdigão', '${stateIdMinasGerais}'),
        ('Perdizes', '${stateIdMinasGerais}'),
        ('Perdões', '${stateIdMinasGerais}'),
        ('Periquito', '${stateIdMinasGerais}'),
        ('Pescador', '${stateIdMinasGerais}'),
        ('Piau', '${stateIdMinasGerais}'),
        ('Piedade de Caratinga', '${stateIdMinasGerais}'),
        ('Piedade de Ponte Nova', '${stateIdMinasGerais}'),
        ('Piedade do Rio Grande', '${stateIdMinasGerais}'),
        ('Piedade dos Gerais', '${stateIdMinasGerais}'),
        ('Pimenta', '${stateIdMinasGerais}'),
        ('Pingo-d\`Água', '${stateIdMinasGerais}'),
        ('Pintópolis', '${stateIdMinasGerais}'),
        ('Piracema', '${stateIdMinasGerais}'),
        ('Pirajuba', '${stateIdMinasGerais}'),
        ('Piranga', '${stateIdMinasGerais}'),
        ('Piranguçu', '${stateIdMinasGerais}'),
        ('Piranguinho', '${stateIdMinasGerais}'),
        ('Pirapetinga', '${stateIdMinasGerais}'),
        ('Pirapora', '${stateIdMinasGerais}'),
        ('Piraúba', '${stateIdMinasGerais}'),
        ('Pitangui', '${stateIdMinasGerais}'),
        ('Piumhi', '${stateIdMinasGerais}'),
        ('Planura', '${stateIdMinasGerais}'),
        ('Poço Fundo', '${stateIdMinasGerais}'),
        ('Poços de Caldas', '${stateIdMinasGerais}'),
        ('Pocrane', '${stateIdMinasGerais}'),
        ('Pompéu', '${stateIdMinasGerais}'),
        ('Ponte Nova', '${stateIdMinasGerais}'),
        ('Ponto Chique', '${stateIdMinasGerais}'),
        ('Ponto dos Volantes', '${stateIdMinasGerais}'),
        ('Porteirinha', '${stateIdMinasGerais}'),
        ('Porto Firme', '${stateIdMinasGerais}'),
        ('Poté', '${stateIdMinasGerais}'),
        ('Pouso Alegre', '${stateIdMinasGerais}'),
        ('Pouso Alto', '${stateIdMinasGerais}'),
        ('Prados', '${stateIdMinasGerais}'),
        ('Prata', '${stateIdMinasGerais}'),
        ('Pratápolis', '${stateIdMinasGerais}'),
        ('Pratinha', '${stateIdMinasGerais}'),
        ('Presidente Bernardes', '${stateIdMinasGerais}'),
        ('Presidente Juscelino', '${stateIdMinasGerais}'),
        ('Presidente Kubitschek', '${stateIdMinasGerais}'),
        ('Presidente Olegário', '${stateIdMinasGerais}'),
        ('Prudente de Morais', '${stateIdMinasGerais}'),
        ('Quartel Geral', '${stateIdMinasGerais}'),
        ('Queluzito', '${stateIdMinasGerais}'),
        ('Raposos', '${stateIdMinasGerais}'),
        ('Raul Soares', '${stateIdMinasGerais}'),
        ('Recreio', '${stateIdMinasGerais}'),
        ('Reduto', '${stateIdMinasGerais}'),
        ('Resende Costa', '${stateIdMinasGerais}'),
        ('Resplendor', '${stateIdMinasGerais}'),
        ('Ressaquinha', '${stateIdMinasGerais}'),
        ('Riachinho', '${stateIdMinasGerais}'),
        ('Riacho dos Machados', '${stateIdMinasGerais}'),
        ('Ribeirão das Neves', '${stateIdMinasGerais}'),
        ('Ribeirão Vermelho', '${stateIdMinasGerais}'),
        ('Rio Acima', '${stateIdMinasGerais}'),
        ('Rio Casca', '${stateIdMinasGerais}'),
        ('Rio do Prado', '${stateIdMinasGerais}'),
        ('Rio Doce', '${stateIdMinasGerais}'),
        ('Rio Espera', '${stateIdMinasGerais}'),
        ('Rio Manso', '${stateIdMinasGerais}'),
        ('Rio Novo', '${stateIdMinasGerais}'),
        ('Rio Paranaíba', '${stateIdMinasGerais}'),
        ('Rio Pardo de Minas', '${stateIdMinasGerais}'),
        ('Rio Piracicaba', '${stateIdMinasGerais}'),
        ('Rio Pomba', '${stateIdMinasGerais}'),
        ('Rio Preto', '${stateIdMinasGerais}'),
        ('Rio Vermelho', '${stateIdMinasGerais}'),
        ('Ritápolis', '${stateIdMinasGerais}'),
        ('Rochedo de Minas', '${stateIdMinasGerais}'),
        ('Rodeiro', '${stateIdMinasGerais}'),
        ('Romaria', '${stateIdMinasGerais}'),
        ('Rosário da Limeira', '${stateIdMinasGerais}'),
        ('Rubelita', '${stateIdMinasGerais}'),
        ('Rubim', '${stateIdMinasGerais}'),
        ('Sabará', '${stateIdMinasGerais}'),
        ('Sabinópolis', '${stateIdMinasGerais}'),
        ('Sacramento', '${stateIdMinasGerais}'),
        ('Salinas', '${stateIdMinasGerais}'),
        ('Salto da Divisa', '${stateIdMinasGerais}'),
        ('Santa Bárbara', '${stateIdMinasGerais}'),
        ('Santa Bárbara do Leste', '${stateIdMinasGerais}'),
        ('Santa Bárbara do Monte Verde', '${stateIdMinasGerais}'),
        ('Santa Bárbara do Tugúrio', '${stateIdMinasGerais}'),
        ('Santa Cruz de Minas', '${stateIdMinasGerais}'),
        ('Santa Cruz de Salinas', '${stateIdMinasGerais}'),
        ('Santa Cruz do Escalvado', '${stateIdMinasGerais}'),
        ('Santa Efigênia de Minas', '${stateIdMinasGerais}'),
        ('Santa Fé de Minas', '${stateIdMinasGerais}'),
        ('Santa Helena de Minas', '${stateIdMinasGerais}'),
        ('Santa Juliana', '${stateIdMinasGerais}'),
        ('Santa Luzia', '${stateIdMinasGerais}'),
        ('Santa Margarida', '${stateIdMinasGerais}'),
        ('Santa Maria de Itabira', '${stateIdMinasGerais}'),
        ('Santa Maria do Salto', '${stateIdMinasGerais}'),
        ('Santa Maria do Suaçuí', '${stateIdMinasGerais}'),
        ('Santa Rita de Caldas', '${stateIdMinasGerais}'),
        ('Santa Rita de Ibitipoca', '${stateIdMinasGerais}'),
        ('Santa Rita de Jacutinga', '${stateIdMinasGerais}'),
        ('Santa Rita de Minas', '${stateIdMinasGerais}'),
        ('Santa Rita do Itueto', '${stateIdMinasGerais}'),
        ('Santa Rita do Sapucaí', '${stateIdMinasGerais}'),
        ('Santa Rosa da Serra', '${stateIdMinasGerais}'),
        ('Santa Vitória', '${stateIdMinasGerais}'),
        ('Santana da Vargem', '${stateIdMinasGerais}'),
        ('Santana de Cataguases', '${stateIdMinasGerais}'),
        ('Santana de Pirapama', '${stateIdMinasGerais}'),
        ('Santana do Deserto', '${stateIdMinasGerais}'),
        ('Santana do Garambéu', '${stateIdMinasGerais}'),
        ('Santana do Jacaré', '${stateIdMinasGerais}'),
        ('Santana do Manhuaçu', '${stateIdMinasGerais}'),
        ('Santana do Paraíso', '${stateIdMinasGerais}'),
        ('Santana do Riacho', '${stateIdMinasGerais}'),
        ('Santana dos Montes', '${stateIdMinasGerais}'),
        ('Santo Antônio do Amparo', '${stateIdMinasGerais}'),
        ('Santo Antônio do Aventureiro', '${stateIdMinasGerais}'),
        ('Santo Antônio do Grama', '${stateIdMinasGerais}'),
        ('Santo Antônio do Itambé', '${stateIdMinasGerais}'),
        ('Santo Antônio do Jacinto', '${stateIdMinasGerais}'),
        ('Santo Antônio do Monte', '${stateIdMinasGerais}'),
        ('Santo Antônio do Retiro', '${stateIdMinasGerais}'),
        ('Santo Antônio do Rio Abaixo', '${stateIdMinasGerais}'),
        ('Santo Hipólito', '${stateIdMinasGerais}'),
        ('Santos Dumont', '${stateIdMinasGerais}'),
        ('São Bento Abade', '${stateIdMinasGerais}'),
        ('São Brás do Suaçuí', '${stateIdMinasGerais}'),
        ('São Domingos das Dores', '${stateIdMinasGerais}'),
        ('São Domingos do Prata', '${stateIdMinasGerais}'),
        ('São Félix de Minas', '${stateIdMinasGerais}'),
        ('São Francisco', '${stateIdMinasGerais}'),
        ('São Francisco de Paula', '${stateIdMinasGerais}'),
        ('São Francisco de Sales', '${stateIdMinasGerais}'),
        ('São Francisco do Glória', '${stateIdMinasGerais}'),
        ('São Geraldo', '${stateIdMinasGerais}'),
        ('São Geraldo da Piedade', '${stateIdMinasGerais}'),
        ('São Geraldo do Baixio', '${stateIdMinasGerais}'),
        ('São Gonçalo do Abaeté', '${stateIdMinasGerais}'),
        ('São Gonçalo do Pará', '${stateIdMinasGerais}'),
        ('São Gonçalo do Rio Abaixo', '${stateIdMinasGerais}'),
        ('São Gonçalo do Rio Preto', '${stateIdMinasGerais}'),
        ('São Gonçalo do Sapucaí', '${stateIdMinasGerais}'),
        ('São Gotardo', '${stateIdMinasGerais}'),
        ('São João Batista do Glória', '${stateIdMinasGerais}'),
        ('São João da Lagoa', '${stateIdMinasGerais}'),
        ('São João da Mata', '${stateIdMinasGerais}'),
        ('São João da Ponte', '${stateIdMinasGerais}'),
        ('São João das Missões', '${stateIdMinasGerais}'),
        ('São João del Rei', '${stateIdMinasGerais}'),
        ('São João do Manhuaçu', '${stateIdMinasGerais}'),
        ('São João do Manteninha', '${stateIdMinasGerais}'),
        ('São João do Oriente', '${stateIdMinasGerais}'),
        ('São João do Pacuí', '${stateIdMinasGerais}'),
        ('São João do Paraíso', '${stateIdMinasGerais}'),
        ('São João Evangelista', '${stateIdMinasGerais}'),
        ('São João Nepomuceno', '${stateIdMinasGerais}'),
        ('São Joaquim de Bicas', '${stateIdMinasGerais}'),
        ('São José da Barra', '${stateIdMinasGerais}'),
        ('São José da Lapa', '${stateIdMinasGerais}'),
        ('São José da Safira', '${stateIdMinasGerais}'),
        ('São José da Varginha', '${stateIdMinasGerais}'),
        ('São José do Alegre', '${stateIdMinasGerais}'),
        ('São José do Divino', '${stateIdMinasGerais}'),
        ('São José do Goiabal', '${stateIdMinasGerais}'),
        ('São José do Jacuri', '${stateIdMinasGerais}'),
        ('São José do Mantimento', '${stateIdMinasGerais}'),
        ('São Lourenço', '${stateIdMinasGerais}'),
        ('São Miguel do Anta', '${stateIdMinasGerais}'),
        ('São Pedro da União', '${stateIdMinasGerais}'),
        ('São Pedro do Suaçuí', '${stateIdMinasGerais}'),
        ('São Pedro dos Ferros', '${stateIdMinasGerais}'),
        ('São Romão', '${stateIdMinasGerais}'),
        ('São Roque de Minas', '${stateIdMinasGerais}'),
        ('São Sebastião da Bela Vista', '${stateIdMinasGerais}'),
        ('São Sebastião da Vargem Alegre', '${stateIdMinasGerais}'),
        ('São Sebastião do Anta', '${stateIdMinasGerais}'),
        ('São Sebastião do Maranhão', '${stateIdMinasGerais}'),
        ('São Sebastião do Oeste', '${stateIdMinasGerais}'),
        ('São Sebastião do Paraíso', '${stateIdMinasGerais}'),
        ('São Sebastião do Rio Preto', '${stateIdMinasGerais}'),
        ('São Sebastião do Rio Verde', '${stateIdMinasGerais}'),
        ('São Thomé das Letras', '${stateIdMinasGerais}'),
        ('São Tiago', '${stateIdMinasGerais}'),
        ('São Tomás de Aquino', '${stateIdMinasGerais}'),
        ('São Vicente de Minas', '${stateIdMinasGerais}'),
        ('Sapucaí-Mirim', '${stateIdMinasGerais}'),
        ('Sardoá', '${stateIdMinasGerais}'),
        ('Sarzedo', '${stateIdMinasGerais}'),
        ('Sem-Peixe', '${stateIdMinasGerais}'),
        ('Senador Amaral', '${stateIdMinasGerais}'),
        ('Senador Cortes', '${stateIdMinasGerais}'),
        ('Senador Firmino', '${stateIdMinasGerais}'),
        ('Senador José Bento', '${stateIdMinasGerais}'),
        ('Senador Modestino Gonçalves', '${stateIdMinasGerais}'),
        ('Senhora de Oliveira', '${stateIdMinasGerais}'),
        ('Senhora do Porto', '${stateIdMinasGerais}'),
        ('Senhora dos Remédios', '${stateIdMinasGerais}'),
        ('Sericita', '${stateIdMinasGerais}'),
        ('Seritinga', '${stateIdMinasGerais}'),
        ('Serra Azul de Minas', '${stateIdMinasGerais}'),
        ('Serra da Saudade', '${stateIdMinasGerais}'),
        ('Serra do Salitre', '${stateIdMinasGerais}'),
        ('Serra dos Aimorés', '${stateIdMinasGerais}'),
        ('Serrania', '${stateIdMinasGerais}'),
        ('Serranópolis de Minas', '${stateIdMinasGerais}'),
        ('Serranos', '${stateIdMinasGerais}'),
        ('Serro', '${stateIdMinasGerais}'),
        ('Sete Lagoas', '${stateIdMinasGerais}'),
        ('Setubinha', '${stateIdMinasGerais}'),
        ('Silveirânia', '${stateIdMinasGerais}'),
        ('Silvianópolis', '${stateIdMinasGerais}'),
        ('Simão Pereira', '${stateIdMinasGerais}'),
        ('Simonésia', '${stateIdMinasGerais}'),
        ('Sobrália', '${stateIdMinasGerais}'),
        ('Soledade de Minas', '${stateIdMinasGerais}'),
        ('Tabuleiro', '${stateIdMinasGerais}'),
        ('Taiobeiras', '${stateIdMinasGerais}'),
        ('Taparuba', '${stateIdMinasGerais}'),
        ('Tapira', '${stateIdMinasGerais}'),
        ('Tapiraí', '${stateIdMinasGerais}'),
        ('Taquaraçu de Minas', '${stateIdMinasGerais}'),
        ('Tarumirim', '${stateIdMinasGerais}'),
        ('Teixeiras', '${stateIdMinasGerais}'),
        ('Teófilo Otoni', '${stateIdMinasGerais}'),
        ('Timóteo', '${stateIdMinasGerais}'),
        ('Tiradentes', '${stateIdMinasGerais}'),
        ('Tiros', '${stateIdMinasGerais}'),
        ('Tocantins', '${stateIdMinasGerais}'),
        ('Tocos do Moji', '${stateIdMinasGerais}'),
        ('Toledo', '${stateIdMinasGerais}'),
        ('Tombos', '${stateIdMinasGerais}'),
        ('Três Corações', '${stateIdMinasGerais}'),
        ('Três Marias', '${stateIdMinasGerais}'),
        ('Três Pontas', '${stateIdMinasGerais}'),
        ('Tumiritinga', '${stateIdMinasGerais}'),
        ('Tupaciguara', '${stateIdMinasGerais}'),
        ('Turmalina', '${stateIdMinasGerais}'),
        ('Turvolândia', '${stateIdMinasGerais}'),
        ('Ubá', '${stateIdMinasGerais}'),
        ('Ubaí', '${stateIdMinasGerais}'),
        ('Ubaporanga', '${stateIdMinasGerais}'),
        ('Uberaba', '${stateIdMinasGerais}'),
        ('Uberlândia', '${stateIdMinasGerais}'),
        ('Umburatiba', '${stateIdMinasGerais}'),
        ('Unaí', '${stateIdMinasGerais}'),
        ('União de Minas', '${stateIdMinasGerais}'),
        ('Uruana de Minas', '${stateIdMinasGerais}'),
        ('Urucânia', '${stateIdMinasGerais}'),
        ('Urucuia', '${stateIdMinasGerais}'),
        ('Vargem Alegre', '${stateIdMinasGerais}'),
        ('Vargem Bonita', '${stateIdMinasGerais}'),
        ('Vargem Grande do Rio Pardo', '${stateIdMinasGerais}'),
        ('Varginha', '${stateIdMinasGerais}'),
        ('Varjão de Minas', '${stateIdMinasGerais}'),
        ('Várzea da Palma', '${stateIdMinasGerais}'),
        ('Varzelândia', '${stateIdMinasGerais}'),
        ('Vazante', '${stateIdMinasGerais}'),
        ('Verdelândia', '${stateIdMinasGerais}'),
        ('Veredinha', '${stateIdMinasGerais}'),
        ('Veríssimo', '${stateIdMinasGerais}'),
        ('Vermelho Novo', '${stateIdMinasGerais}'),
        ('Vespasiano', '${stateIdMinasGerais}'),
        ('Viçosa', '${stateIdMinasGerais}'),
        ('Vieiras', '${stateIdMinasGerais}'),
        ('Virgem da Lapa', '${stateIdMinasGerais}'),
        ('Virgínia', '${stateIdMinasGerais}'),
        ('Virginópolis', '${stateIdMinasGerais}'),
        ('Virgolândia', '${stateIdMinasGerais}'),
        ('Visconde do Rio Branco', '${stateIdMinasGerais}'),
        ('Volta Grande', '${stateIdMinasGerais}'),
        ('Wenceslau Braz', '${stateIdMinasGerais}');
      `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdMinasGerais = 'df6bc32a-92d4-4691-b8ba-ec3fa2b27c10';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdMinasGerais}';
    `);
  }
}
