import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateSantaCatarina1744515004457
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdSantaCatarina = '5279a78c-2706-4e84-bd0b-5b5c994de0d5';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Abdon Batista', '${stateIdSantaCatarina}'),
        ('Abelardo Luz', '${stateIdSantaCatarina}'),
        ('Agrolândia', '${stateIdSantaCatarina}'),
        ('Agronômica', '${stateIdSantaCatarina}'),
        ('Água Doce', '${stateIdSantaCatarina}'),
        ('Águas de Chapecó', '${stateIdSantaCatarina}'),
        ('Águas Frias', '${stateIdSantaCatarina}'),
        ('Águas Mornas', '${stateIdSantaCatarina}'),
        ('Alfredo Wagner', '${stateIdSantaCatarina}'),
        ('Alto Bela Vista', '${stateIdSantaCatarina}'),
        ('Anchieta', '${stateIdSantaCatarina}'),
        ('Angelina', '${stateIdSantaCatarina}'),
        ('Anita Garibaldi', '${stateIdSantaCatarina}'),
        ('Anitápolis', '${stateIdSantaCatarina}'),
        ('Antônio Carlos', '${stateIdSantaCatarina}'),
        ('Apiúna', '${stateIdSantaCatarina}'),
        ('Arabutã', '${stateIdSantaCatarina}'),
        ('Araquari', '${stateIdSantaCatarina}'),
        ('Araranguá', '${stateIdSantaCatarina}'),
        ('Armazém', '${stateIdSantaCatarina}'),
        ('Arroio Trinta', '${stateIdSantaCatarina}'),
        ('Arvoredo', '${stateIdSantaCatarina}'),
        ('Ascurra', '${stateIdSantaCatarina}'),
        ('Atalanta', '${stateIdSantaCatarina}'),
        ('Aurora', '${stateIdSantaCatarina}'),
        ('Balneário Arroio do Silva', '${stateIdSantaCatarina}'),
        ('Balneário Barra do Sul', '${stateIdSantaCatarina}'),
        ('Balneário Camboriú', '${stateIdSantaCatarina}'),
        ('Balneário Gaivota', '${stateIdSantaCatarina}'),
        ('Bandeirante', '${stateIdSantaCatarina}'),
        ('Barra Bonita', '${stateIdSantaCatarina}'),
        ('Barra Velha', '${stateIdSantaCatarina}'),
        ('Bela Vista do Toldo', '${stateIdSantaCatarina}'),
        ('Belmonte', '${stateIdSantaCatarina}'),
        ('Benedito Novo', '${stateIdSantaCatarina}'),
        ('Biguaçu', '${stateIdSantaCatarina}'),
        ('Blumenau', '${stateIdSantaCatarina}'),
        ('Bocaina do Sul', '${stateIdSantaCatarina}'),
        ('Bom Jardim da Serra', '${stateIdSantaCatarina}'),
        ('Bom Jesus', '${stateIdSantaCatarina}'),
        ('Bom Jesus do Oeste', '${stateIdSantaCatarina}'),
        ('Bom Retiro', '${stateIdSantaCatarina}'),
        ('Bombinhas', '${stateIdSantaCatarina}'),
        ('Botuverá', '${stateIdSantaCatarina}'),
        ('Braço do Norte', '${stateIdSantaCatarina}'),
        ('Braço do Trombudo', '${stateIdSantaCatarina}'),
        ('Brunópolis', '${stateIdSantaCatarina}'),
        ('Brusque', '${stateIdSantaCatarina}'),
        ('Caçador', '${stateIdSantaCatarina}'),
        ('Caibi', '${stateIdSantaCatarina}'),
        ('Calmon', '${stateIdSantaCatarina}'),
        ('Camboriú', '${stateIdSantaCatarina}'),
        ('Campo Alegre', '${stateIdSantaCatarina}'),
        ('Campo Belo do Sul', '${stateIdSantaCatarina}'),
        ('Campo Erê', '${stateIdSantaCatarina}'),
        ('Campos Novos', '${stateIdSantaCatarina}'),
        ('Canelinha', '${stateIdSantaCatarina}'),
        ('Canoinhas', '${stateIdSantaCatarina}'),
        ('Capão Alto', '${stateIdSantaCatarina}'),
        ('Capinzal', '${stateIdSantaCatarina}'),
        ('Capivari de Baixo', '${stateIdSantaCatarina}'),
        ('Catanduvas', '${stateIdSantaCatarina}'),
        ('Caxambu do Sul', '${stateIdSantaCatarina}'),
        ('Celso Ramos', '${stateIdSantaCatarina}'),
        ('Cerro Negro', '${stateIdSantaCatarina}'),
        ('Chapadão do Lageado', '${stateIdSantaCatarina}'),
        ('Chapecó', '${stateIdSantaCatarina}'),
        ('Cocal do Sul', '${stateIdSantaCatarina}'),
        ('Concórdia', '${stateIdSantaCatarina}'),
        ('Cordilheira Alta', '${stateIdSantaCatarina}'),
        ('Coronel Freitas', '${stateIdSantaCatarina}'),
        ('Coronel Martins', '${stateIdSantaCatarina}'),
        ('Correia Pinto', '${stateIdSantaCatarina}'),
        ('Corupá', '${stateIdSantaCatarina}'),
        ('Criciúma', '${stateIdSantaCatarina}'),
        ('Cunha Porã', '${stateIdSantaCatarina}'),
        ('Cunhataí', '${stateIdSantaCatarina}'),
        ('Curitibanos', '${stateIdSantaCatarina}'),
        ('Descanso', '${stateIdSantaCatarina}'),
        ('Dionísio Cerqueira', '${stateIdSantaCatarina}'),
        ('Dona Emma', '${stateIdSantaCatarina}'),
        ('Doutor Pedrinho', '${stateIdSantaCatarina}'),
        ('Entre Rios', '${stateIdSantaCatarina}'),
        ('Ermo', '${stateIdSantaCatarina}'),
        ('Erval Velho', '${stateIdSantaCatarina}'),
        ('Faxinal dos Guedes', '${stateIdSantaCatarina}'),
        ('Flor do Sertão', '${stateIdSantaCatarina}'),
        ('Florianópolis', '${stateIdSantaCatarina}'),
        ('Formosa do Sul', '${stateIdSantaCatarina}'),
        ('Forquilhinha', '${stateIdSantaCatarina}'),
        ('Fraiburgo', '${stateIdSantaCatarina}'),
        ('Frei Rogério', '${stateIdSantaCatarina}'),
        ('Galvão', '${stateIdSantaCatarina}'),
        ('Garopaba', '${stateIdSantaCatarina}'),
        ('Garuva', '${stateIdSantaCatarina}'),
        ('Gaspar', '${stateIdSantaCatarina}'),
        ('Governador Celso Ramos', '${stateIdSantaCatarina}'),
        ('Grão Pará', '${stateIdSantaCatarina}'),
        ('Gravatal', '${stateIdSantaCatarina}'),
        ('Guabiruba', '${stateIdSantaCatarina}'),
        ('Guaraciaba', '${stateIdSantaCatarina}'),
        ('Guaramirim', '${stateIdSantaCatarina}'),
        ('Guarujá do Sul', '${stateIdSantaCatarina}'),
        ('Guatambú', '${stateIdSantaCatarina}'),
        ('Herval d\`Oeste', '${stateIdSantaCatarina}'),
        ('Ibiam', '${stateIdSantaCatarina}'),
        ('Ibicaré', '${stateIdSantaCatarina}'),
        ('Ibirama', '${stateIdSantaCatarina}'),
        ('Içara', '${stateIdSantaCatarina}'),
        ('Ilhota', '${stateIdSantaCatarina}'),
        ('Imaruí', '${stateIdSantaCatarina}'),
        ('Imbituba', '${stateIdSantaCatarina}'),
        ('Imbuia', '${stateIdSantaCatarina}'),
        ('Indaial', '${stateIdSantaCatarina}'),
        ('Iomerê', '${stateIdSantaCatarina}'),
        ('Ipira', '${stateIdSantaCatarina}'),
        ('Iporã do Oeste', '${stateIdSantaCatarina}'),
        ('Ipuaçu', '${stateIdSantaCatarina}'),
        ('Ipumirim', '${stateIdSantaCatarina}'),
        ('Iraceminha', '${stateIdSantaCatarina}'),
        ('Irani', '${stateIdSantaCatarina}'),
        ('Irati', '${stateIdSantaCatarina}'),
        ('Irineópolis', '${stateIdSantaCatarina}'),
        ('Itá', '${stateIdSantaCatarina}'),
        ('Itaiópolis', '${stateIdSantaCatarina}'),
        ('Itajaí', '${stateIdSantaCatarina}'),
        ('Itapema', '${stateIdSantaCatarina}'),
        ('Itapiranga', '${stateIdSantaCatarina}'),
        ('Itapoá', '${stateIdSantaCatarina}'),
        ('Ituporanga', '${stateIdSantaCatarina}'),
        ('Jaborá', '${stateIdSantaCatarina}'),
        ('Jacinto Machado', '${stateIdSantaCatarina}'),
        ('Jaguaruna', '${stateIdSantaCatarina}'),
        ('Jaraguá do Sul', '${stateIdSantaCatarina}'),
        ('Jardinópolis', '${stateIdSantaCatarina}'),
        ('Joaçaba', '${stateIdSantaCatarina}'),
        ('Joinville', '${stateIdSantaCatarina}'),
        ('José Boiteux', '${stateIdSantaCatarina}'),
        ('Jupiá', '${stateIdSantaCatarina}'),
        ('Lacerdópolis', '${stateIdSantaCatarina}'),
        ('Lages', '${stateIdSantaCatarina}'),
        ('Laguna', '${stateIdSantaCatarina}'),
        ('Lajeado Grande', '${stateIdSantaCatarina}'),
        ('Laurentino', '${stateIdSantaCatarina}'),
        ('Lauro Muller', '${stateIdSantaCatarina}'),
        ('Lebon Régis', '${stateIdSantaCatarina}'),
        ('Leoberto Leal', '${stateIdSantaCatarina}'),
        ('Lindóia do Sul', '${stateIdSantaCatarina}'),
        ('Lontras', '${stateIdSantaCatarina}'),
        ('Luiz Alves', '${stateIdSantaCatarina}'),
        ('Luzerna', '${stateIdSantaCatarina}'),
        ('Macieira', '${stateIdSantaCatarina}'),
        ('Mafra', '${stateIdSantaCatarina}'),
        ('Major Gercino', '${stateIdSantaCatarina}'),
        ('Major Vieira', '${stateIdSantaCatarina}'),
        ('Maracajá', '${stateIdSantaCatarina}'),
        ('Maravilha', '${stateIdSantaCatarina}'),
        ('Marema', '${stateIdSantaCatarina}'),
        ('Massaranduba', '${stateIdSantaCatarina}'),
        ('Matos Costa', '${stateIdSantaCatarina}'),
        ('Meleiro', '${stateIdSantaCatarina}'),
        ('Mirim Doce', '${stateIdSantaCatarina}'),
        ('Modelo', '${stateIdSantaCatarina}'),
        ('Mondaí', '${stateIdSantaCatarina}'),
        ('Monte Carlo', '${stateIdSantaCatarina}'),
        ('Monte Castelo', '${stateIdSantaCatarina}'),
        ('Morro da Fumaça', '${stateIdSantaCatarina}'),
        ('Morro Grande', '${stateIdSantaCatarina}'),
        ('Navegantes', '${stateIdSantaCatarina}'),
        ('Nova Erechim', '${stateIdSantaCatarina}'),
        ('Nova Itaberaba', '${stateIdSantaCatarina}'),
        ('Nova Trento', '${stateIdSantaCatarina}'),
        ('Nova Veneza', '${stateIdSantaCatarina}'),
        ('Novo Horizonte', '${stateIdSantaCatarina}'),
        ('Orleans', '${stateIdSantaCatarina}'),
        ('Otacílio Costa', '${stateIdSantaCatarina}'),
        ('Ouro', '${stateIdSantaCatarina}'),
        ('Ouro Verde', '${stateIdSantaCatarina}'),
        ('Paial', '${stateIdSantaCatarina}'),
        ('Painel', '${stateIdSantaCatarina}'),
        ('Palhoça', '${stateIdSantaCatarina}'),
        ('Palma Sola', '${stateIdSantaCatarina}'),
        ('Palmeira', '${stateIdSantaCatarina}'),
        ('Palmitos', '${stateIdSantaCatarina}'),
        ('Papanduva', '${stateIdSantaCatarina}'),
        ('Paraíso', '${stateIdSantaCatarina}'),
        ('Passo de Torres', '${stateIdSantaCatarina}'),
        ('Passos Maia', '${stateIdSantaCatarina}'),
        ('Paulo Lopes', '${stateIdSantaCatarina}'),
        ('Pedras Grandes', '${stateIdSantaCatarina}'),
        ('Penha', '${stateIdSantaCatarina}'),
        ('Peritiba', '${stateIdSantaCatarina}'),
        ('Petrolândia', '${stateIdSantaCatarina}'),
        ('Piçarras', '${stateIdSantaCatarina}'),
        ('Pinhalzinho', '${stateIdSantaCatarina}'),
        ('Pinheiro Preto', '${stateIdSantaCatarina}'),
        ('Piratuba', '${stateIdSantaCatarina}'),
        ('Planalto Alegre', '${stateIdSantaCatarina}'),
        ('Pomerode', '${stateIdSantaCatarina}'),
        ('Ponte Alta', '${stateIdSantaCatarina}'),
        ('Ponte Alta do Norte', '${stateIdSantaCatarina}'),
        ('Ponte Serrada', '${stateIdSantaCatarina}'),
        ('Porto Belo', '${stateIdSantaCatarina}'),
        ('Porto União', '${stateIdSantaCatarina}'),
        ('Pouso Redondo', '${stateIdSantaCatarina}'),
        ('Praia Grande', '${stateIdSantaCatarina}'),
        ('Presidente Castelo Branco', '${stateIdSantaCatarina}'),
        ('Presidente Getúlio', '${stateIdSantaCatarina}'),
        ('Presidente Nereu', '${stateIdSantaCatarina}'),
        ('Princesa', '${stateIdSantaCatarina}'),
        ('Quilombo', '${stateIdSantaCatarina}'),
        ('Rancho Queimado', '${stateIdSantaCatarina}'),
        ('Rio das Antas', '${stateIdSantaCatarina}'),
        ('Rio do Campo', '${stateIdSantaCatarina}'),
        ('Rio do Oeste', '${stateIdSantaCatarina}'),
        ('Rio do Sul', '${stateIdSantaCatarina}'),
        ('Rio dos Cedros', '${stateIdSantaCatarina}'),
        ('Rio Fortuna', '${stateIdSantaCatarina}'),
        ('Rio Negrinho', '${stateIdSantaCatarina}'),
        ('Rio Rufino', '${stateIdSantaCatarina}'),
        ('Riqueza', '${stateIdSantaCatarina}'),
        ('Rodeio', '${stateIdSantaCatarina}'),
        ('Romelândia', '${stateIdSantaCatarina}'),
        ('Salete', '${stateIdSantaCatarina}'),
        ('Saltinho', '${stateIdSantaCatarina}'),
        ('Salto Veloso', '${stateIdSantaCatarina}'),
        ('Sangão', '${stateIdSantaCatarina}'),
        ('Santa Cecília', '${stateIdSantaCatarina}'),
        ('Santa Helena', '${stateIdSantaCatarina}'),
        ('Santa Rosa de Lima', '${stateIdSantaCatarina}'),
        ('Santa Rosa do Sul', '${stateIdSantaCatarina}'),
        ('Santa Terezinha', '${stateIdSantaCatarina}'),
        ('Santa Terezinha do Progresso', '${stateIdSantaCatarina}'),
        ('Santiago do Sul', '${stateIdSantaCatarina}'),
        ('Santo Amaro da Imperatriz', '${stateIdSantaCatarina}'),
        ('São Bento do Sul', '${stateIdSantaCatarina}'),
        ('São Bernardino', '${stateIdSantaCatarina}'),
        ('São Bonifácio', '${stateIdSantaCatarina}'),
        ('São Carlos', '${stateIdSantaCatarina}'),
        ('São Cristovão do Sul', '${stateIdSantaCatarina}'),
        ('São Domingos', '${stateIdSantaCatarina}'),
        ('São Francisco do Sul', '${stateIdSantaCatarina}'),
        ('São João Batista', '${stateIdSantaCatarina}'),
        ('São João do Itaperiú', '${stateIdSantaCatarina}'),
        ('São João do Oeste', '${stateIdSantaCatarina}'),
        ('São João do Sul', '${stateIdSantaCatarina}'),
        ('São Joaquim', '${stateIdSantaCatarina}'),
        ('São José', '${stateIdSantaCatarina}'),
        ('São José do Cedro', '${stateIdSantaCatarina}'),
        ('São José do Cerrito', '${stateIdSantaCatarina}'),
        ('São Lourenço do Oeste', '${stateIdSantaCatarina}'),
        ('São Ludgero', '${stateIdSantaCatarina}'),
        ('São Martinho', '${stateIdSantaCatarina}'),
        ('São Miguel da Boa Vista', '${stateIdSantaCatarina}'),
        ('São Miguel do Oeste', '${stateIdSantaCatarina}'),
        ('São Pedro de Alcântara', '${stateIdSantaCatarina}'),
        ('Saudades', '${stateIdSantaCatarina}'),
        ('Schroeder', '${stateIdSantaCatarina}'),
        ('Seara', '${stateIdSantaCatarina}'),
        ('Serra Alta', '${stateIdSantaCatarina}'),
        ('Siderópolis', '${stateIdSantaCatarina}'),
        ('Sombrio', '${stateIdSantaCatarina}'),
        ('Sul Brasil', '${stateIdSantaCatarina}'),
        ('Taió', '${stateIdSantaCatarina}'),
        ('Tangará', '${stateIdSantaCatarina}'),
        ('Tigrinhos', '${stateIdSantaCatarina}'),
        ('Tijucas', '${stateIdSantaCatarina}'),
        ('Timbé do Sul', '${stateIdSantaCatarina}'),
        ('Timbó', '${stateIdSantaCatarina}'),
        ('Timbó Grande', '${stateIdSantaCatarina}'),
        ('Três Barras', '${stateIdSantaCatarina}'),
        ('Treviso', '${stateIdSantaCatarina}'),
        ('Treze de Maio', '${stateIdSantaCatarina}'),
        ('Treze Tílias', '${stateIdSantaCatarina}'),
        ('Trombudo Central', '${stateIdSantaCatarina}'),
        ('Tubarão', '${stateIdSantaCatarina}'),
        ('Tunápolis', '${stateIdSantaCatarina}'),
        ('Turvo', '${stateIdSantaCatarina}'),
        ('União do Oeste', '${stateIdSantaCatarina}'),
        ('Urubici', '${stateIdSantaCatarina}'),
        ('Urupema', '${stateIdSantaCatarina}'),
        ('Urussanga', '${stateIdSantaCatarina}'),
        ('Vargeão', '${stateIdSantaCatarina}'),
        ('Vargem', '${stateIdSantaCatarina}'),
        ('Vargem Bonita', '${stateIdSantaCatarina}'),
        ('Vidal Ramos', '${stateIdSantaCatarina}'),
        ('Videira', '${stateIdSantaCatarina}'),
        ('Vitor Meireles', '${stateIdSantaCatarina}'),
        ('Witmarsum', '${stateIdSantaCatarina}'),
        ('Xanxerê', '${stateIdSantaCatarina}'),
        ('Xavantina', '${stateIdSantaCatarina}'),
        ('Xaxim', '${stateIdSantaCatarina}'),
        ('Zortéa', '${stateIdSantaCatarina}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdSantaCatarina = '5279a78c-2706-4e84-bd0b-5b5c994de0d5';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdSantaCatarina}';
    `);
  }
}
