import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStatePara1744505476506
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdPara = 'c185c45e-3f6d-4f20-857a-70b1f358c370';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Abaetetuba', '${stateIdPara}'),
        ('Abel Figueiredo', '${stateIdPara}'),
        ('Acará', '${stateIdPara}'),
        ('Afuá', '${stateIdPara}'),
        ('Água Azul do Norte', '${stateIdPara}'),
        ('Alenquer', '${stateIdPara}'),
        ('Almeirim', '${stateIdPara}'),
        ('Altamira', '${stateIdPara}'),
        ('Anajás', '${stateIdPara}'),
        ('Ananindeua', '${stateIdPara}'),
        ('Anapu', '${stateIdPara}'),
        ('Augusto Corrêa', '${stateIdPara}'),
        ('Aurora do Pará', '${stateIdPara}'),
        ('Aveiro', '${stateIdPara}'),
        ('Bagre', '${stateIdPara}'),
        ('Baião', '${stateIdPara}'),
        ('Bannach', '${stateIdPara}'),
        ('Barcarena', '${stateIdPara}'),
        ('Belém', '${stateIdPara}'),
        ('Belterra', '${stateIdPara}'),
        ('Benevides', '${stateIdPara}'),
        ('Bom Jesus do Tocantins', '${stateIdPara}'),
        ('Bonito', '${stateIdPara}'),
        ('Bragança', '${stateIdPara}'),
        ('Brasil Novo', '${stateIdPara}'),
        ('Brejo Grande do Araguaia', '${stateIdPara}'),
        ('Breu Branco', '${stateIdPara}'),
        ('Breves', '${stateIdPara}'),
        ('Bujaru', '${stateIdPara}'),
        ('Cachoeira do Arari', '${stateIdPara}'),
        ('Cachoeira do Piriá', '${stateIdPara}'),
        ('Cametá', '${stateIdPara}'),
        ('Canaã dos Carajás', '${stateIdPara}'),
        ('Capanema', '${stateIdPara}'),
        ('Capitão Poço', '${stateIdPara}'),
        ('Castanhal', '${stateIdPara}'),
        ('Chaves', '${stateIdPara}'),
        ('Colares', '${stateIdPara}'),
        ('Conceição do Araguaia', '${stateIdPara}'),
        ('Concórdia do Pará', '${stateIdPara}'),
        ('Cumaru do Norte', '${stateIdPara}'),
        ('Curionópolis', '${stateIdPara}'),
        ('Curralinho', '${stateIdPara}'),
        ('Curuá', '${stateIdPara}'),
        ('Curuçá', '${stateIdPara}'),
        ('Dom Eliseu', '${stateIdPara}'),
        ('Eldorado dos Carajás', '${stateIdPara}'),
        ('Faro', '${stateIdPara}'),
        ('Floresta do Araguaia', '${stateIdPara}'),
        ('Garrafão do Norte', '${stateIdPara}'),
        ('Goianésia do Pará', '${stateIdPara}'),
        ('Gurupá', '${stateIdPara}'),
        ('Igarapé-Açu', '${stateIdPara}'),
        ('Igarapé-Miri', '${stateIdPara}'),
        ('Inhangapi', '${stateIdPara}'),
        ('Ipixuna do Pará', '${stateIdPara}'),
        ('Irituia', '${stateIdPara}'),
        ('Itaituba', '${stateIdPara}'),
        ('Itupiranga', '${stateIdPara}'),
        ('Jacareacanga', '${stateIdPara}'),
        ('Jacundá', '${stateIdPara}'),
        ('Juruti', '${stateIdPara}'),
        ('Limoeiro do Ajuru', '${stateIdPara}'),
        ('Mãe do Rio', '${stateIdPara}'),
        ('Magalhães Barata', '${stateIdPara}'),
        ('Marabá', '${stateIdPara}'),
        ('Maracanã', '${stateIdPara}'),
        ('Marapanim', '${stateIdPara}'),
        ('Marituba', '${stateIdPara}'),
        ('Medicilândia', '${stateIdPara}'),
        ('Melgaço', '${stateIdPara}'),
        ('Mocajuba', '${stateIdPara}'),
        ('Moju', '${stateIdPara}'),
        ('Monte Alegre', '${stateIdPara}'),
        ('Muaná', '${stateIdPara}'),
        ('Nova Esperança do Piriá', '${stateIdPara}'),
        ('Nova Ipixuna', '${stateIdPara}'),
        ('Nova Timboteua', '${stateIdPara}'),
        ('Novo Progresso', '${stateIdPara}'),
        ('Novo Repartimento', '${stateIdPara}'),
        ('Óbidos', '${stateIdPara}'),
        ('Oeiras do Pará', '${stateIdPara}'),
        ('Oriximiná', '${stateIdPara}'),
        ('Ourém', '${stateIdPara}'),
        ('Ourilândia do Norte', '${stateIdPara}'),
        ('Pacajá', '${stateIdPara}'),
        ('Palestina do Pará', '${stateIdPara}'),
        ('Paragominas', '${stateIdPara}'),
        ('Parauapebas', '${stateIdPara}'),
        ('Pau d\`Arco', '${stateIdPara}'),
        ('Peixe-Boi', '${stateIdPara}'),
        ('Piçarra', '${stateIdPara}'),
        ('Placas', '${stateIdPara}'),
        ('Ponta de Pedras', '${stateIdPara}'),
        ('Portel', '${stateIdPara}'),
        ('Porto de Moz', '${stateIdPara}'),
        ('Prainha', '${stateIdPara}'),
        ('Primavera', '${stateIdPara}'),
        ('Quatipuru', '${stateIdPara}'),
        ('Redenção', '${stateIdPara}'),
        ('Rio Maria', '${stateIdPara}'),
        ('Rondon do Pará', '${stateIdPara}'),
        ('Rurópolis', '${stateIdPara}'),
        ('Salinópolis', '${stateIdPara}'),
        ('Salvaterra', '${stateIdPara}'),
        ('Santa Bárbara do Pará', '${stateIdPara}'),
        ('Santa Cruz do Arari', '${stateIdPara}'),
        ('Santa Isabel do Pará', '${stateIdPara}'),
        ('Santa Luzia do Pará', '${stateIdPara}'),
        ('Santa Maria das Barreiras', '${stateIdPara}'),
        ('Santa Maria do Pará', '${stateIdPara}'),
        ('Santana do Araguaia', '${stateIdPara}'),
        ('Santarém', '${stateIdPara}'),
        ('Santarém Novo', '${stateIdPara}'),
        ('Santo Antônio do Tauá', '${stateIdPara}'),
        ('São Caetano de Odivelas', '${stateIdPara}'),
        ('São Domingos do Araguaia', '${stateIdPara}'),
        ('São Domingos do Capim', '${stateIdPara}'),
        ('São Félix do Xingu', '${stateIdPara}'),
        ('São Francisco do Pará', '${stateIdPara}'),
        ('São Geraldo do Araguaia', '${stateIdPara}'),
        ('São João da Ponta', '${stateIdPara}'),
        ('São João de Pirabas', '${stateIdPara}'),
        ('São João do Araguaia', '${stateIdPara}'),
        ('São Miguel do Guamá', '${stateIdPara}'),
        ('São Sebastião da Boa Vista', '${stateIdPara}'),
        ('Sapucaia', '${stateIdPara}'),
        ('Senador José Porfírio', '${stateIdPara}'),
        ('Soure', '${stateIdPara}'),
        ('Tailândia', '${stateIdPara}'),
        ('Terra Alta', '${stateIdPara}'),
        ('Terra Santa', '${stateIdPara}'),
        ('Tomé-Açu', '${stateIdPara}'),
        ('Tracuateua', '${stateIdPara}'),
        ('Trairão', '${stateIdPara}'),
        ('Tucumã', '${stateIdPara}'),
        ('Tucuruí', '${stateIdPara}'),
        ('Ulianópolis', '${stateIdPara}'),
        ('Uruará', '${stateIdPara}'),
        ('Vigia', '${stateIdPara}'),
        ('Viseu', '${stateIdPara}'),
        ('Vitória do Xingu', '${stateIdPara}'),
        ('Xinguara', '${stateIdPara}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdPara = 'c185c45e-3f6d-4f20-857a-70b1f358c370';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdPara}';
    `);
  }
}
