import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateParaiba1744507520573
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdParaiba = 'b6de0e29-8660-4e58-9dfb-c3172a9079e6';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Água Branca', '${stateIdParaiba}'),
        ('Aguiar', '${stateIdParaiba}'),
        ('Alagoa Grande', '${stateIdParaiba}'),
        ('Alagoa Nova', '${stateIdParaiba}'),
        ('Alagoinha', '${stateIdParaiba}'),
        ('Alcantil', '${stateIdParaiba}'),
        ('Algodão de Jandaíra', '${stateIdParaiba}'),
        ('Alhandra', '${stateIdParaiba}'),
        ('Amparo', '${stateIdParaiba}'),
        ('Aparecida', '${stateIdParaiba}'),
        ('Araçagi', '${stateIdParaiba}'),
        ('Arara', '${stateIdParaiba}'),
        ('Araruna', '${stateIdParaiba}'),
        ('Areia', '${stateIdParaiba}'),
        ('Areia de Baraúnas', '${stateIdParaiba}'),
        ('Areial', '${stateIdParaiba}'),
        ('Aroeiras', '${stateIdParaiba}'),
        ('Assunção', '${stateIdParaiba}'),
        ('Baía da Traição', '${stateIdParaiba}'),
        ('Bananeiras', '${stateIdParaiba}'),
        ('Baraúna', '${stateIdParaiba}'),
        ('Barra de Santa Rosa', '${stateIdParaiba}'),
        ('Barra de Santana', '${stateIdParaiba}'),
        ('Barra de São Miguel', '${stateIdParaiba}'),
        ('Bayeux', '${stateIdParaiba}'),
        ('Belém', '${stateIdParaiba}'),
        ('Belém do Brejo do Cruz', '${stateIdParaiba}'),
        ('Bernardino Batista', '${stateIdParaiba}'),
        ('Boa Ventura', '${stateIdParaiba}'),
        ('Boa Vista', '${stateIdParaiba}'),
        ('Bom Jesus', '${stateIdParaiba}'),
        ('Bom Sucesso', '${stateIdParaiba}'),
        ('Bonito de Santa Fé', '${stateIdParaiba}'),
        ('Boqueirão', '${stateIdParaiba}'),
        ('Borborema', '${stateIdParaiba}'),
        ('Brejo do Cruz', '${stateIdParaiba}'),
        ('Brejo dos Santos', '${stateIdParaiba}'),
        ('Caaporã', '${stateIdParaiba}'),
        ('Cabaceiras', '${stateIdParaiba}'),
        ('Cabedelo', '${stateIdParaiba}'),
        ('Cachoeira dos Índios', '${stateIdParaiba}'),
        ('Cacimba de Areia', '${stateIdParaiba}'),
        ('Cacimba de Dentro', '${stateIdParaiba}'),
        ('Cacimbas', '${stateIdParaiba}'),
        ('Caiçara', '${stateIdParaiba}'),
        ('Cajazeiras', '${stateIdParaiba}'),
        ('Cajazeirinhas', '${stateIdParaiba}'),
        ('Caldas Brandão', '${stateIdParaiba}'),
        ('Camalaú', '${stateIdParaiba}'),
        ('Campina Grande', '${stateIdParaiba}'),
        ('Campo de Santana', '${stateIdParaiba}'),
        ('Capim', '${stateIdParaiba}'),
        ('Caraúbas', '${stateIdParaiba}'),
        ('Carrapateira', '${stateIdParaiba}'),
        ('Casserengue', '${stateIdParaiba}'),
        ('Catingueira', '${stateIdParaiba}'),
        ('Catolé do Rocha', '${stateIdParaiba}'),
        ('Caturité', '${stateIdParaiba}'),
        ('Conceição', '${stateIdParaiba}'),
        ('Condado', '${stateIdParaiba}'),
        ('Conde', '${stateIdParaiba}'),
        ('Congo', '${stateIdParaiba}'),
        ('Coremas', '${stateIdParaiba}'),
        ('Coxixola', '${stateIdParaiba}'),
        ('Cruz do Espírito Santo', '${stateIdParaiba}'),
        ('Cubati', '${stateIdParaiba}'),
        ('Cuité', '${stateIdParaiba}'),
        ('Cuité de Mamanguape', '${stateIdParaiba}'),
        ('Cuitegi', '${stateIdParaiba}'),
        ('Curral de Cima', '${stateIdParaiba}'),
        ('Curral Velho', '${stateIdParaiba}'),
        ('Damião', '${stateIdParaiba}'),
        ('Desterro', '${stateIdParaiba}'),
        ('Diamante', '${stateIdParaiba}'),
        ('Dona Inês', '${stateIdParaiba}'),
        ('Duas Estradas', '${stateIdParaiba}'),
        ('Emas', '${stateIdParaiba}'),
        ('Esperança', '${stateIdParaiba}'),
        ('Fagundes', '${stateIdParaiba}'),
        ('Frei Martinho', '${stateIdParaiba}'),
        ('Gado Bravo', '${stateIdParaiba}'),
        ('Guarabira', '${stateIdParaiba}'),
        ('Gurinhém', '${stateIdParaiba}'),
        ('Gurjão', '${stateIdParaiba}'),
        ('Ibiara', '${stateIdParaiba}'),
        ('Igaracy', '${stateIdParaiba}'),
        ('Imaculada', '${stateIdParaiba}'),
        ('Ingá', '${stateIdParaiba}'),
        ('Itabaiana', '${stateIdParaiba}'),
        ('Itaporanga', '${stateIdParaiba}'),
        ('Itapororoca', '${stateIdParaiba}'),
        ('Itatuba', '${stateIdParaiba}'),
        ('Jacaraú', '${stateIdParaiba}'),
        ('Jericó', '${stateIdParaiba}'),
        ('João Pessoa', '${stateIdParaiba}'),
        ('Juarez Távora', '${stateIdParaiba}'),
        ('Juazeirinho', '${stateIdParaiba}'),
        ('Junco do Seridó', '${stateIdParaiba}'),
        ('Juripiranga', '${stateIdParaiba}'),
        ('Juru', '${stateIdParaiba}'),
        ('Lagoa', '${stateIdParaiba}'),
        ('Lagoa de Dentro', '${stateIdParaiba}'),
        ('Lagoa Seca', '${stateIdParaiba}'),
        ('Lastro', '${stateIdParaiba}'),
        ('Livramento', '${stateIdParaiba}'),
        ('Logradouro', '${stateIdParaiba}'),
        ('Lucena', '${stateIdParaiba}'),
        ('Mãe d\`Água', '${stateIdParaiba}'),
        ('Malta', '${stateIdParaiba}'),
        ('Mamanguape', '${stateIdParaiba}'),
        ('Manaíra', '${stateIdParaiba}'),
        ('Marcação', '${stateIdParaiba}'),
        ('Mari', '${stateIdParaiba}'),
        ('Marizópolis', '${stateIdParaiba}'),
        ('Massaranduba', '${stateIdParaiba}'),
        ('Mataraca', '${stateIdParaiba}'),
        ('Matinhas', '${stateIdParaiba}'),
        ('Mato Grosso', '${stateIdParaiba}'),
        ('Maturéia', '${stateIdParaiba}'),
        ('Mogeiro', '${stateIdParaiba}'),
        ('Montadas', '${stateIdParaiba}'),
        ('Monte Horebe', '${stateIdParaiba}'),
        ('Monteiro', '${stateIdParaiba}'),
        ('Mulungu', '${stateIdParaiba}'),
        ('Natuba', '${stateIdParaiba}'),
        ('Nazarezinho', '${stateIdParaiba}'),
        ('Nova Floresta', '${stateIdParaiba}'),
        ('Nova Olinda', '${stateIdParaiba}'),
        ('Nova Palmeira', '${stateIdParaiba}'),
        ('Olho d\`Água', '${stateIdParaiba}'),
        ('Olivedos', '${stateIdParaiba}'),
        ('Ouro Velho', '${stateIdParaiba}'),
        ('Parari', '${stateIdParaiba}'),
        ('Passagem', '${stateIdParaiba}'),
        ('Patos', '${stateIdParaiba}'),
        ('Paulista', '${stateIdParaiba}'),
        ('Pedra Branca', '${stateIdParaiba}'),
        ('Pedra Lavrada', '${stateIdParaiba}'),
        ('Pedras de Fogo', '${stateIdParaiba}'),
        ('Pedro Régis', '${stateIdParaiba}'),
        ('Piancó', '${stateIdParaiba}'),
        ('Picuí', '${stateIdParaiba}'),
        ('Pilar', '${stateIdParaiba}'),
        ('Pilões', '${stateIdParaiba}'),
        ('Pilõezinhos', '${stateIdParaiba}'),
        ('Pirpirituba', '${stateIdParaiba}'),
        ('Pitimbu', '${stateIdParaiba}'),
        ('Pocinhos', '${stateIdParaiba}'),
        ('Poço Dantas', '${stateIdParaiba}'),
        ('Poço de José de Moura', '${stateIdParaiba}'),
        ('Pombal', '${stateIdParaiba}'),
        ('Prata', '${stateIdParaiba}'),
        ('Princesa Isabel', '${stateIdParaiba}'),
        ('Puxinanã', '${stateIdParaiba}'),
        ('Queimadas', '${stateIdParaiba}'),
        ('Quixabá', '${stateIdParaiba}'),
        ('Remígio', '${stateIdParaiba}'),
        ('Riachão', '${stateIdParaiba}'),
        ('Riachão do Bacamarte', '${stateIdParaiba}'),
        ('Riachão do Poço', '${stateIdParaiba}'),
        ('Riacho de Santo Antônio', '${stateIdParaiba}'),
        ('Riacho dos Cavalos', '${stateIdParaiba}'),
        ('Rio Tinto', '${stateIdParaiba}'),
        ('Salgadinho', '${stateIdParaiba}'),
        ('Salgado de São Félix', '${stateIdParaiba}'),
        ('Santa Cecília', '${stateIdParaiba}'),
        ('Santa Cruz', '${stateIdParaiba}'),
        ('Santa Helena', '${stateIdParaiba}'),
        ('Santa Inês', '${stateIdParaiba}'),
        ('Santa Luzia', '${stateIdParaiba}'),
        ('Santa Rita', '${stateIdParaiba}'),
        ('Santa Teresinha', '${stateIdParaiba}'),
        ('Santana de Mangueira', '${stateIdParaiba}'),
        ('Santana dos Garrotes', '${stateIdParaiba}'),
        ('Santarém', '${stateIdParaiba}'),
        ('Santo André', '${stateIdParaiba}'),
        ('São Bentinho', '${stateIdParaiba}'),
        ('São Bento', '${stateIdParaiba}'),
        ('São Domingos de Pombal', '${stateIdParaiba}'),
        ('São Domingos do Cariri', '${stateIdParaiba}'),
        ('São Francisco', '${stateIdParaiba}'),
        ('São João do Cariri', '${stateIdParaiba}'),
        ('São João do Rio do Peixe', '${stateIdParaiba}'),
        ('São João do Tigre', '${stateIdParaiba}'),
        ('São José da Lagoa Tapada', '${stateIdParaiba}'),
        ('São José de Caiana', '${stateIdParaiba}'),
        ('São José de Espinharas', '${stateIdParaiba}'),
        ('São José de Piranhas', '${stateIdParaiba}'),
        ('São José de Princesa', '${stateIdParaiba}'),
        ('São José do Bonfim', '${stateIdParaiba}'),
        ('São José do Brejo do Cruz', '${stateIdParaiba}'),
        ('São José do Sabugi', '${stateIdParaiba}'),
        ('São José dos Cordeiros', '${stateIdParaiba}'),
        ('São José dos Ramos', '${stateIdParaiba}'),
        ('São Mamede', '${stateIdParaiba}'),
        ('São Miguel de Taipu', '${stateIdParaiba}'),
        ('São Sebastião de Lagoa de Roça', '${stateIdParaiba}'),
        ('São Sebastião do Umbuzeiro', '${stateIdParaiba}'),
        ('Sapé', '${stateIdParaiba}'),
        ('Seridó', '${stateIdParaiba}'),
        ('Serra Branca', '${stateIdParaiba}'),
        ('Serra da Raiz', '${stateIdParaiba}'),
        ('Serra Grande', '${stateIdParaiba}'),
        ('Serra Redonda', '${stateIdParaiba}'),
        ('Serraria', '${stateIdParaiba}'),
        ('Sertãozinho', '${stateIdParaiba}'),
        ('Sobrado', '${stateIdParaiba}'),
        ('Solânea', '${stateIdParaiba}'),
        ('Soledade', '${stateIdParaiba}'),
        ('Sossêgo', '${stateIdParaiba}'),
        ('Sousa', '${stateIdParaiba}'),
        ('Sumé', '${stateIdParaiba}'),
        ('Taperoá', '${stateIdParaiba}'),
        ('Tavares', '${stateIdParaiba}'),
        ('Teixeira', '${stateIdParaiba}'),
        ('Tenório', '${stateIdParaiba}'),
        ('Triunfo', '${stateIdParaiba}'),
        ('Uiraúna', '${stateIdParaiba}'),
        ('Umbuzeiro', '${stateIdParaiba}'),
        ('Várzea', '${stateIdParaiba}'),
        ('Vieirópolis', '${stateIdParaiba}'),
        ('Vista Serrana', '${stateIdParaiba}'),
        ('Zabelê', '${stateIdParaiba}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdParaiba = 'b6de0e29-8660-4e58-9dfb-c3172a9079e6';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdParaiba}';
    `);
  }
}
