import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateTocantins1744517275314
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdTocantins = '5fa749ef-9d9a-4037-97c6-f145e3809a7d';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Abreulândia', '${stateIdTocantins}'),
        ('Aguiarnópolis', '${stateIdTocantins}'),
        ('Aliança do Tocantins', '${stateIdTocantins}'),
        ('Almas', '${stateIdTocantins}'),
        ('Alvorada', '${stateIdTocantins}'),
        ('Ananás', '${stateIdTocantins}'),
        ('Angico', '${stateIdTocantins}'),
        ('Aparecida do Rio Negro', '${stateIdTocantins}'),
        ('Aragominas', '${stateIdTocantins}'),
        ('Araguacema', '${stateIdTocantins}'),
        ('Araguaçu', '${stateIdTocantins}'),
        ('Araguaína', '${stateIdTocantins}'),
        ('Araguanã', '${stateIdTocantins}'),
        ('Araguatins', '${stateIdTocantins}'),
        ('Arapoema', '${stateIdTocantins}'),
        ('Arraias', '${stateIdTocantins}'),
        ('Augustinópolis', '${stateIdTocantins}'),
        ('Aurora do Tocantins', '${stateIdTocantins}'),
        ('Axixá do Tocantins', '${stateIdTocantins}'),
        ('Babaçulândia', '${stateIdTocantins}'),
        ('Bandeirantes do Tocantins', '${stateIdTocantins}'),
        ('Barra do Ouro', '${stateIdTocantins}'),
        ('Barrolândia', '${stateIdTocantins}'),
        ('Bernardo Sayão', '${stateIdTocantins}'),
        ('Bom Jesus do Tocantins', '${stateIdTocantins}'),
        ('Brasilândia do Tocantins', '${stateIdTocantins}'),
        ('Brejinho de Nazaré', '${stateIdTocantins}'),
        ('Buriti do Tocantins', '${stateIdTocantins}'),
        ('Cachoeirinha', '${stateIdTocantins}'),
        ('Campos Lindos', '${stateIdTocantins}'),
        ('Cariri do Tocantins', '${stateIdTocantins}'),
        ('Carmolândia', '${stateIdTocantins}'),
        ('Carrasco Bonito', '${stateIdTocantins}'),
        ('Caseara', '${stateIdTocantins}'),
        ('Centenário', '${stateIdTocantins}'),
        ('Chapada da Natividade', '${stateIdTocantins}'),
        ('Chapada de Areia', '${stateIdTocantins}'),
        ('Colinas do Tocantins', '${stateIdTocantins}'),
        ('Colméia', '${stateIdTocantins}'),
        ('Combinado', '${stateIdTocantins}'),
        ('Conceição do Tocantins', '${stateIdTocantins}'),
        ('Couto de Magalhães', '${stateIdTocantins}'),
        ('Cristalândia', '${stateIdTocantins}'),
        ('Crixás do Tocantins', '${stateIdTocantins}'),
        ('Darcinópolis', '${stateIdTocantins}'),
        ('Dianópolis', '${stateIdTocantins}'),
        ('Divinópolis do Tocantins', '${stateIdTocantins}'),
        ('Dois Irmãos do Tocantins', '${stateIdTocantins}'),
        ('Dueré', '${stateIdTocantins}'),
        ('Esperantina', '${stateIdTocantins}'),
        ('Fátima', '${stateIdTocantins}'),
        ('Figueirópolis', '${stateIdTocantins}'),
        ('Filadélfia', '${stateIdTocantins}'),
        ('Formoso do Araguaia', '${stateIdTocantins}'),
        ('Fortaleza do Tabocão', '${stateIdTocantins}'),
        ('Goianorte', '${stateIdTocantins}'),
        ('Goiatins', '${stateIdTocantins}'),
        ('Guaraí', '${stateIdTocantins}'),
        ('Gurupi', '${stateIdTocantins}'),
        ('Ipueiras', '${stateIdTocantins}'),
        ('Itacajá', '${stateIdTocantins}'),
        ('Itaguatins', '${stateIdTocantins}'),
        ('Itapiratins', '${stateIdTocantins}'),
        ('Itaporã do Tocantins', '${stateIdTocantins}'),
        ('Jaú do Tocantins', '${stateIdTocantins}'),
        ('Juarina', '${stateIdTocantins}'),
        ('Lagoa da Confusão', '${stateIdTocantins}'),
        ('Lagoa do Tocantins', '${stateIdTocantins}'),
        ('Lajeado', '${stateIdTocantins}'),
        ('Lavandeira', '${stateIdTocantins}'),
        ('Lizarda', '${stateIdTocantins}'),
        ('Luzinópolis', '${stateIdTocantins}'),
        ('Marianópolis do Tocantins', '${stateIdTocantins}'),
        ('Mateiros', '${stateIdTocantins}'),
        ('Maurilândia do Tocantins', '${stateIdTocantins}'),
        ('Miracema do Tocantins', '${stateIdTocantins}'),
        ('Miranorte', '${stateIdTocantins}'),
        ('Monte do Carmo', '${stateIdTocantins}'),
        ('Monte Santo do Tocantins', '${stateIdTocantins}'),
        ('Muricilândia', '${stateIdTocantins}'),
        ('Natividade', '${stateIdTocantins}'),
        ('Nazaré', '${stateIdTocantins}'),
        ('Nova Olinda', '${stateIdTocantins}'),
        ('Nova Rosalândia', '${stateIdTocantins}'),
        ('Novo Acordo', '${stateIdTocantins}'),
        ('Novo Alegre', '${stateIdTocantins}'),
        ('Novo Jardim', '${stateIdTocantins}'),
        ('Oliveira de Fátima', '${stateIdTocantins}'),
        ('Palmas', '${stateIdTocantins}'),
        ('Palmeirante', '${stateIdTocantins}'),
        ('Palmeiras do Tocantins', '${stateIdTocantins}'),
        ('Palmeirópolis', '${stateIdTocantins}'),
        ('Paraíso do Tocantins', '${stateIdTocantins}'),
        ('Paranã', '${stateIdTocantins}'),
        ('Pau d\`Arco', '${stateIdTocantins}'),
        ('Pedro Afonso', '${stateIdTocantins}'),
        ('Peixe', '${stateIdTocantins}'),
        ('Pequizeiro', '${stateIdTocantins}'),
        ('Pindorama do Tocantins', '${stateIdTocantins}'),
        ('Piraquê', '${stateIdTocantins}'),
        ('Pium', '${stateIdTocantins}'),
        ('Ponte Alta do Bom Jesus', '${stateIdTocantins}'),
        ('Ponte Alta do Tocantins', '${stateIdTocantins}'),
        ('Porto Alegre do Tocantins', '${stateIdTocantins}'),
        ('Porto Nacional', '${stateIdTocantins}'),
        ('Praia Norte', '${stateIdTocantins}'),
        ('Presidente Kennedy', '${stateIdTocantins}'),
        ('Pugmil', '${stateIdTocantins}'),
        ('Recursolândia', '${stateIdTocantins}'),
        ('Riachinho', '${stateIdTocantins}'),
        ('Rio da Conceição', '${stateIdTocantins}'),
        ('Rio dos Bois', '${stateIdTocantins}'),
        ('Rio Sono', '${stateIdTocantins}'),
        ('Sampaio', '${stateIdTocantins}'),
        ('Sandolândia', '${stateIdTocantins}'),
        ('Santa Fé do Araguaia', '${stateIdTocantins}'),
        ('Santa Maria do Tocantins', '${stateIdTocantins}'),
        ('Santa Rita do Tocantins', '${stateIdTocantins}'),
        ('Santa Rosa do Tocantins', '${stateIdTocantins}'),
        ('Santa Tereza do Tocantins', '${stateIdTocantins}'),
        ('Santa Terezinha do Tocantins', '${stateIdTocantins}'),
        ('São Bento do Tocantins', '${stateIdTocantins}'),
        ('São Félix do Tocantins', '${stateIdTocantins}'),
        ('São Miguel do Tocantins', '${stateIdTocantins}'),
        ('São Salvador do Tocantins', '${stateIdTocantins}'),
        ('São Sebastião do Tocantins', '${stateIdTocantins}'),
        ('São Valério da Natividade', '${stateIdTocantins}'),
        ('Silvanópolis', '${stateIdTocantins}'),
        ('Sítio Novo do Tocantins', '${stateIdTocantins}'),
        ('Sucupira', '${stateIdTocantins}'),
        ('Taguatinga', '${stateIdTocantins}'),
        ('Taipas do Tocantins', '${stateIdTocantins}'),
        ('Talismã', '${stateIdTocantins}'),
        ('Tocantínia', '${stateIdTocantins}'),
        ('Tocantinópolis', '${stateIdTocantins}'),
        ('Tupirama', '${stateIdTocantins}'),
        ('Tupiratins', '${stateIdTocantins}'),
        ('Wanderlândia', '${stateIdTocantins}'),
        ('Xambioá', '${stateIdTocantins}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdTocantins = '5fa749ef-9d9a-4037-97c6-f145e3809a7d';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdTocantins}';
    `);
  }
}
