import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateRioGrandeSul1744512910192
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdRioGrandeSul = 'c2394216-c1dc-4d42-9fe1-1444e57ff9d9';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Aceguá', '${stateIdRioGrandeSul}'),
        ('Água Santa', '${stateIdRioGrandeSul}'),
        ('Agudo', '${stateIdRioGrandeSul}'),
        ('Ajuricaba', '${stateIdRioGrandeSul}'),
        ('Alecrim', '${stateIdRioGrandeSul}'),
        ('Alegrete', '${stateIdRioGrandeSul}'),
        ('Alegria', '${stateIdRioGrandeSul}'),
        ('Almirante Tamandaré do Sul', '${stateIdRioGrandeSul}'),
        ('Alpestre', '${stateIdRioGrandeSul}'),
        ('Alto Alegre', '${stateIdRioGrandeSul}'),
        ('Alto Feliz', '${stateIdRioGrandeSul}'),
        ('Alvorada', '${stateIdRioGrandeSul}'),
        ('Amaral Ferrador', '${stateIdRioGrandeSul}'),
        ('Ametista do Sul', '${stateIdRioGrandeSul}'),
        ('André da Rocha', '${stateIdRioGrandeSul}'),
        ('Anta Gorda', '${stateIdRioGrandeSul}'),
        ('Antônio Prado', '${stateIdRioGrandeSul}'),
        ('Arambaré', '${stateIdRioGrandeSul}'),
        ('Araricá', '${stateIdRioGrandeSul}'),
        ('Aratiba', '${stateIdRioGrandeSul}'),
        ('Arroio do Meio', '${stateIdRioGrandeSul}'),
        ('Arroio do Padre', '${stateIdRioGrandeSul}'),
        ('Arroio do Sal', '${stateIdRioGrandeSul}'),
        ('Arroio do Tigre', '${stateIdRioGrandeSul}'),
        ('Arroio dos Ratos', '${stateIdRioGrandeSul}'),
        ('Arroio Grande', '${stateIdRioGrandeSul}'),
        ('Arvorezinha', '${stateIdRioGrandeSul}'),
        ('Augusto Pestana', '${stateIdRioGrandeSul}'),
        ('Áurea', '${stateIdRioGrandeSul}'),
        ('Bagé', '${stateIdRioGrandeSul}'),
        ('Balneário Pinhal', '${stateIdRioGrandeSul}'),
        ('Barão', '${stateIdRioGrandeSul}'),
        ('Barão de Cotegipe', '${stateIdRioGrandeSul}'),
        ('Barão do Triunfo', '${stateIdRioGrandeSul}'),
        ('Barra do Guarita', '${stateIdRioGrandeSul}'),
        ('Barra do Quaraí', '${stateIdRioGrandeSul}'),
        ('Barra do Ribeiro', '${stateIdRioGrandeSul}'),
        ('Barra do Rio Azul', '${stateIdRioGrandeSul}'),
        ('Barra Funda', '${stateIdRioGrandeSul}'),
        ('Barracão', '${stateIdRioGrandeSul}'),
        ('Barros Cassal', '${stateIdRioGrandeSul}'),
        ('Benjamin Constant do Sul', '${stateIdRioGrandeSul}'),
        ('Bento Gonçalves', '${stateIdRioGrandeSul}'),
        ('Boa Vista das Missões', '${stateIdRioGrandeSul}'),
        ('Boa Vista do Buricá', '${stateIdRioGrandeSul}'),
        ('Boa Vista do Cadeado', '${stateIdRioGrandeSul}'),
        ('Boa Vista do Incra', '${stateIdRioGrandeSul}'),
        ('Boa Vista do Sul', '${stateIdRioGrandeSul}'),
        ('Bom Jesus', '${stateIdRioGrandeSul}'),
        ('Bom Princípio', '${stateIdRioGrandeSul}'),
        ('Bom Progresso', '${stateIdRioGrandeSul}'),
        ('Bom Retiro do Sul', '${stateIdRioGrandeSul}'),
        ('Boqueirão do Leão', '${stateIdRioGrandeSul}'),
        ('Bossoroca', '${stateIdRioGrandeSul}'),
        ('Bozano', '${stateIdRioGrandeSul}'),
        ('Braga', '${stateIdRioGrandeSul}'),
        ('Brochier', '${stateIdRioGrandeSul}'),
        ('Butiá', '${stateIdRioGrandeSul}'),
        ('Caçapava do Sul', '${stateIdRioGrandeSul}'),
        ('Cacequi', '${stateIdRioGrandeSul}'),
        ('Cachoeira do Sul', '${stateIdRioGrandeSul}'),
        ('Cachoeirinha', '${stateIdRioGrandeSul}'),
        ('Cacique Doble', '${stateIdRioGrandeSul}'),
        ('Caibaté', '${stateIdRioGrandeSul}'),
        ('Caiçara', '${stateIdRioGrandeSul}'),
        ('Camaquã', '${stateIdRioGrandeSul}'),
        ('Camargo', '${stateIdRioGrandeSul}'),
        ('Cambará do Sul', '${stateIdRioGrandeSul}'),
        ('Campestre da Serra', '${stateIdRioGrandeSul}'),
        ('Campina das Missões', '${stateIdRioGrandeSul}'),
        ('Campinas do Sul', '${stateIdRioGrandeSul}'),
        ('Campo Bom', '${stateIdRioGrandeSul}'),
        ('Campo Novo', '${stateIdRioGrandeSul}'),
        ('Campos Borges', '${stateIdRioGrandeSul}'),
        ('Candelária', '${stateIdRioGrandeSul}'),
        ('Cândido Godói', '${stateIdRioGrandeSul}'),
        ('Candiota', '${stateIdRioGrandeSul}'),
        ('Canela', '${stateIdRioGrandeSul}'),
        ('Canguçu', '${stateIdRioGrandeSul}'),
        ('Canoas', '${stateIdRioGrandeSul}'),
        ('Canudos do Vale', '${stateIdRioGrandeSul}'),
        ('Capão Bonito do Sul', '${stateIdRioGrandeSul}'),
        ('Capão da Canoa', '${stateIdRioGrandeSul}'),
        ('Capão do Cipó', '${stateIdRioGrandeSul}'),
        ('Capão do Leão', '${stateIdRioGrandeSul}'),
        ('Capela de Santana', '${stateIdRioGrandeSul}'),
        ('Capitão', '${stateIdRioGrandeSul}'),
        ('Capivari do Sul', '${stateIdRioGrandeSul}'),
        ('Caraá', '${stateIdRioGrandeSul}'),
        ('Carazinho', '${stateIdRioGrandeSul}'),
        ('Carlos Barbosa', '${stateIdRioGrandeSul}'),
        ('Carlos Gomes', '${stateIdRioGrandeSul}'),
        ('Casca', '${stateIdRioGrandeSul}'),
        ('Caseiros', '${stateIdRioGrandeSul}'),
        ('Catuípe', '${stateIdRioGrandeSul}'),
        ('Caxias do Sul', '${stateIdRioGrandeSul}'),
        ('Centenário', '${stateIdRioGrandeSul}'),
        ('Cerrito', '${stateIdRioGrandeSul}'),
        ('Cerro Branco', '${stateIdRioGrandeSul}'),
        ('Cerro Grande', '${stateIdRioGrandeSul}'),
        ('Cerro Grande do Sul', '${stateIdRioGrandeSul}'),
        ('Cerro Largo', '${stateIdRioGrandeSul}'),
        ('Chapada', '${stateIdRioGrandeSul}'),
        ('Charqueadas', '${stateIdRioGrandeSul}'),
        ('Charrua', '${stateIdRioGrandeSul}'),
        ('Chiapeta', '${stateIdRioGrandeSul}'),
        ('Chuí', '${stateIdRioGrandeSul}'),
        ('Chuvisca', '${stateIdRioGrandeSul}'),
        ('Cidreira', '${stateIdRioGrandeSul}'),
        ('Ciríaco', '${stateIdRioGrandeSul}'),
        ('Colinas', '${stateIdRioGrandeSul}'),
        ('Colorado', '${stateIdRioGrandeSul}'),
        ('Condor', '${stateIdRioGrandeSul}'),
        ('Constantina', '${stateIdRioGrandeSul}'),
        ('Coqueiro Baixo', '${stateIdRioGrandeSul}'),
        ('Coqueiros do Sul', '${stateIdRioGrandeSul}'),
        ('Coronel Barros', '${stateIdRioGrandeSul}'),
        ('Coronel Bicaco', '${stateIdRioGrandeSul}'),
        ('Coronel Pilar', '${stateIdRioGrandeSul}'),
        ('Cotiporã', '${stateIdRioGrandeSul}'),
        ('Coxilha', '${stateIdRioGrandeSul}'),
        ('Crissiumal', '${stateIdRioGrandeSul}'),
        ('Cristal', '${stateIdRioGrandeSul}'),
        ('Cristal do Sul', '${stateIdRioGrandeSul}'),
        ('Cruz Alta', '${stateIdRioGrandeSul}'),
        ('Cruzaltense', '${stateIdRioGrandeSul}'),
        ('Cruzeiro do Sul', '${stateIdRioGrandeSul}'),
        ('David Canabarro', '${stateIdRioGrandeSul}'),
        ('Derrubadas', '${stateIdRioGrandeSul}'),
        ('Dezesseis de Novembro', '${stateIdRioGrandeSul}'),
        ('Dilermando de Aguiar', '${stateIdRioGrandeSul}'),
        ('Dois Irmãos', '${stateIdRioGrandeSul}'),
        ('Dois Irmãos das Missões', '${stateIdRioGrandeSul}'),
        ('Dois Lajeados', '${stateIdRioGrandeSul}'),
        ('Dom Feliciano', '${stateIdRioGrandeSul}'),
        ('Dom Pedrito', '${stateIdRioGrandeSul}'),
        ('Dom Pedro de Alcântara', '${stateIdRioGrandeSul}'),
        ('Dona Francisca', '${stateIdRioGrandeSul}'),
        ('Doutor Maurício Cardoso', '${stateIdRioGrandeSul}'),
        ('Doutor Ricardo', '${stateIdRioGrandeSul}'),
        ('Eldorado do Sul', '${stateIdRioGrandeSul}'),
        ('Encantado', '${stateIdRioGrandeSul}'),
        ('Encruzilhada do Sul', '${stateIdRioGrandeSul}'),
        ('Engenho Velho', '${stateIdRioGrandeSul}'),
        ('Entre Rios do Sul', '${stateIdRioGrandeSul}'),
        ('Entre-Ijuís', '${stateIdRioGrandeSul}'),
        ('Erebango', '${stateIdRioGrandeSul}'),
        ('Erechim', '${stateIdRioGrandeSul}'),
        ('Ernestina', '${stateIdRioGrandeSul}'),
        ('Erval Grande', '${stateIdRioGrandeSul}'),
        ('Erval Seco', '${stateIdRioGrandeSul}'),
        ('Esmeralda', '${stateIdRioGrandeSul}'),
        ('Esperança do Sul', '${stateIdRioGrandeSul}'),
        ('Espumoso', '${stateIdRioGrandeSul}'),
        ('Estação', '${stateIdRioGrandeSul}'),
        ('Estância Velha', '${stateIdRioGrandeSul}'),
        ('Esteio', '${stateIdRioGrandeSul}'),
        ('Estrela', '${stateIdRioGrandeSul}'),
        ('Estrela Velha', '${stateIdRioGrandeSul}'),
        ('Eugênio de Castro', '${stateIdRioGrandeSul}'),
        ('Fagundes Varela', '${stateIdRioGrandeSul}'),
        ('Farroupilha', '${stateIdRioGrandeSul}'),
        ('Faxinal do Soturno', '${stateIdRioGrandeSul}'),
        ('Faxinalzinho', '${stateIdRioGrandeSul}'),
        ('Fazenda Vilanova', '${stateIdRioGrandeSul}'),
        ('Feliz', '${stateIdRioGrandeSul}'),
        ('Flores da Cunha', '${stateIdRioGrandeSul}'),
        ('Floriano Peixoto', '${stateIdRioGrandeSul}'),
        ('Fontoura Xavier', '${stateIdRioGrandeSul}'),
        ('Formigueiro', '${stateIdRioGrandeSul}'),
        ('Forquetinha', '${stateIdRioGrandeSul}'),
        ('Fortaleza dos Valos', '${stateIdRioGrandeSul}'),
        ('Frederico Westphalen', '${stateIdRioGrandeSul}'),
        ('Garibaldi', '${stateIdRioGrandeSul}'),
        ('Garruchos', '${stateIdRioGrandeSul}'),
        ('Gaurama', '${stateIdRioGrandeSul}'),
        ('General Câmara', '${stateIdRioGrandeSul}'),
        ('Gentil', '${stateIdRioGrandeSul}'),
        ('Getúlio Vargas', '${stateIdRioGrandeSul}'),
        ('Giruá', '${stateIdRioGrandeSul}'),
        ('Glorinha', '${stateIdRioGrandeSul}'),
        ('Gramado', '${stateIdRioGrandeSul}'),
        ('Gramado dos Loureiros', '${stateIdRioGrandeSul}'),
        ('Gramado Xavier', '${stateIdRioGrandeSul}'),
        ('Gravataí', '${stateIdRioGrandeSul}'),
        ('Guabiju', '${stateIdRioGrandeSul}'),
        ('Guaíba', '${stateIdRioGrandeSul}'),
        ('Guaporé', '${stateIdRioGrandeSul}'),
        ('Guarani das Missões', '${stateIdRioGrandeSul}'),
        ('Harmonia', '${stateIdRioGrandeSul}'),
        ('Herval', '${stateIdRioGrandeSul}'),
        ('Herveiras', '${stateIdRioGrandeSul}'),
        ('Horizontina', '${stateIdRioGrandeSul}'),
        ('Hulha Negra', '${stateIdRioGrandeSul}'),
        ('Humaitá', '${stateIdRioGrandeSul}'),
        ('Ibarama', '${stateIdRioGrandeSul}'),
        ('Ibiaçá', '${stateIdRioGrandeSul}'),
        ('Ibiraiaras', '${stateIdRioGrandeSul}'),
        ('Ibirapuitã', '${stateIdRioGrandeSul}'),
        ('Ibirubá', '${stateIdRioGrandeSul}'),
        ('Igrejinha', '${stateIdRioGrandeSul}'),
        ('Ijuí', '${stateIdRioGrandeSul}'),
        ('Ilópolis', '${stateIdRioGrandeSul}'),
        ('Imbé', '${stateIdRioGrandeSul}'),
        ('Imigrante', '${stateIdRioGrandeSul}'),
        ('Independência', '${stateIdRioGrandeSul}'),
        ('Inhacorá', '${stateIdRioGrandeSul}'),
        ('Ipê', '${stateIdRioGrandeSul}'),
        ('Ipiranga do Sul', '${stateIdRioGrandeSul}'),
        ('Iraí', '${stateIdRioGrandeSul}'),
        ('Itaara', '${stateIdRioGrandeSul}'),
        ('Itacurubi', '${stateIdRioGrandeSul}'),
        ('Itapuca', '${stateIdRioGrandeSul}'),
        ('Itaqui', '${stateIdRioGrandeSul}'),
        ('Itati', '${stateIdRioGrandeSul}'),
        ('Itatiba do Sul', '${stateIdRioGrandeSul}'),
        ('Ivorá', '${stateIdRioGrandeSul}'),
        ('Ivoti', '${stateIdRioGrandeSul}'),
        ('Jaboticaba', '${stateIdRioGrandeSul}'),
        ('Jacuizinho', '${stateIdRioGrandeSul}'),
        ('Jacutinga', '${stateIdRioGrandeSul}'),
        ('Jaguarão', '${stateIdRioGrandeSul}'),
        ('Jaguari', '${stateIdRioGrandeSul}'),
        ('Jaquirana', '${stateIdRioGrandeSul}'),
        ('Jari', '${stateIdRioGrandeSul}'),
        ('Jóia', '${stateIdRioGrandeSul}'),
        ('Júlio de Castilhos', '${stateIdRioGrandeSul}'),
        ('Lagoa Bonita do Sul', '${stateIdRioGrandeSul}'),
        ('Lagoa dos Três Cantos', '${stateIdRioGrandeSul}'),
        ('Lagoa Vermelha', '${stateIdRioGrandeSul}'),
        ('Lagoão', '${stateIdRioGrandeSul}'),
        ('Lajeado', '${stateIdRioGrandeSul}'),
        ('Lajeado do Bugre', '${stateIdRioGrandeSul}'),
        ('Lavras do Sul', '${stateIdRioGrandeSul}'),
        ('Liberato Salzano', '${stateIdRioGrandeSul}'),
        ('Lindolfo Collor', '${stateIdRioGrandeSul}'),
        ('Linha Nova', '${stateIdRioGrandeSul}'),
        ('Maçambara', '${stateIdRioGrandeSul}'),
        ('Machadinho', '${stateIdRioGrandeSul}'),
        ('Mampituba', '${stateIdRioGrandeSul}'),
        ('Manoel Viana', '${stateIdRioGrandeSul}'),
        ('Maquiné', '${stateIdRioGrandeSul}'),
        ('Maratá', '${stateIdRioGrandeSul}'),
        ('Marau', '${stateIdRioGrandeSul}'),
        ('Marcelino Ramos', '${stateIdRioGrandeSul}'),
        ('Mariana Pimentel', '${stateIdRioGrandeSul}'),
        ('Mariano Moro', '${stateIdRioGrandeSul}'),
        ('Marques de Souza', '${stateIdRioGrandeSul}'),
        ('Mata', '${stateIdRioGrandeSul}'),
        ('Mato Castelhano', '${stateIdRioGrandeSul}'),
        ('Mato Leitão', '${stateIdRioGrandeSul}'),
        ('Mato Queimado', '${stateIdRioGrandeSul}'),
        ('Maximiliano de Almeida', '${stateIdRioGrandeSul}'),
        ('Minas do Leão', '${stateIdRioGrandeSul}'),
        ('Miraguaí', '${stateIdRioGrandeSul}'),
        ('Montauri', '${stateIdRioGrandeSul}'),
        ('Monte Alegre dos Campos', '${stateIdRioGrandeSul}'),
        ('Monte Belo do Sul', '${stateIdRioGrandeSul}'),
        ('Montenegro', '${stateIdRioGrandeSul}'),
        ('Mormaço', '${stateIdRioGrandeSul}'),
        ('Morrinhos do Sul', '${stateIdRioGrandeSul}'),
        ('Morro Redondo', '${stateIdRioGrandeSul}'),
        ('Morro Reuter', '${stateIdRioGrandeSul}'),
        ('Mostardas', '${stateIdRioGrandeSul}'),
        ('Muçum', '${stateIdRioGrandeSul}'),
        ('Muitos Capões', '${stateIdRioGrandeSul}'),
        ('Muliterno', '${stateIdRioGrandeSul}'),
        ('Não-Me-Toque', '${stateIdRioGrandeSul}'),
        ('Nicolau Vergueiro', '${stateIdRioGrandeSul}'),
        ('Nonoai', '${stateIdRioGrandeSul}'),
        ('Nova Alvorada', '${stateIdRioGrandeSul}'),
        ('Nova Araçá', '${stateIdRioGrandeSul}'),
        ('Nova Bassano', '${stateIdRioGrandeSul}'),
        ('Nova Boa Vista', '${stateIdRioGrandeSul}'),
        ('Nova Bréscia', '${stateIdRioGrandeSul}'),
        ('Nova Candelária', '${stateIdRioGrandeSul}'),
        ('Nova Esperança do Sul', '${stateIdRioGrandeSul}'),
        ('Nova Hartz', '${stateIdRioGrandeSul}'),
        ('Nova Pádua', '${stateIdRioGrandeSul}'),
        ('Nova Palma', '${stateIdRioGrandeSul}'),
        ('Nova Petrópolis', '${stateIdRioGrandeSul}'),
        ('Nova Prata', '${stateIdRioGrandeSul}'),
        ('Nova Ramada', '${stateIdRioGrandeSul}'),
        ('Nova Roma do Sul', '${stateIdRioGrandeSul}'),
        ('Nova Santa Rita', '${stateIdRioGrandeSul}'),
        ('Novo Barreiro', '${stateIdRioGrandeSul}'),
        ('Novo Cabrais', '${stateIdRioGrandeSul}'),
        ('Novo Hamburgo', '${stateIdRioGrandeSul}'),
        ('Novo Machado', '${stateIdRioGrandeSul}'),
        ('Novo Tiradentes', '${stateIdRioGrandeSul}'),
        ('Novo Xingu', '${stateIdRioGrandeSul}'),
        ('Osório', '${stateIdRioGrandeSul}'),
        ('Paim Filho', '${stateIdRioGrandeSul}'),
        ('Palmares do Sul', '${stateIdRioGrandeSul}'),
        ('Palmeira das Missões', '${stateIdRioGrandeSul}'),
        ('Palmitinho', '${stateIdRioGrandeSul}'),
        ('Panambi', '${stateIdRioGrandeSul}'),
        ('Pantano Grande', '${stateIdRioGrandeSul}'),
        ('Paraí', '${stateIdRioGrandeSul}'),
        ('Paraíso do Sul', '${stateIdRioGrandeSul}'),
        ('Pareci Novo', '${stateIdRioGrandeSul}'),
        ('Parobé', '${stateIdRioGrandeSul}'),
        ('Passa Sete', '${stateIdRioGrandeSul}'),
        ('Passo do Sobrado', '${stateIdRioGrandeSul}'),
        ('Passo Fundo', '${stateIdRioGrandeSul}'),
        ('Paulo Bento', '${stateIdRioGrandeSul}'),
        ('Paverama', '${stateIdRioGrandeSul}'),
        ('Pedras Altas', '${stateIdRioGrandeSul}'),
        ('Pedro Osório', '${stateIdRioGrandeSul}'),
        ('Pejuçara', '${stateIdRioGrandeSul}'),
        ('Pelotas', '${stateIdRioGrandeSul}'),
        ('Picada Café', '${stateIdRioGrandeSul}'),
        ('Pinhal', '${stateIdRioGrandeSul}'),
        ('Pinhal da Serra', '${stateIdRioGrandeSul}'),
        ('Pinhal Grande', '${stateIdRioGrandeSul}'),
        ('Pinheirinho do Vale', '${stateIdRioGrandeSul}'),
        ('Pinheiro Machado', '${stateIdRioGrandeSul}'),
        ('Pirapó', '${stateIdRioGrandeSul}'),
        ('Piratini', '${stateIdRioGrandeSul}'),
        ('Planalto', '${stateIdRioGrandeSul}'),
        ('Poço das Antas', '${stateIdRioGrandeSul}'),
        ('Pontão', '${stateIdRioGrandeSul}'),
        ('Ponte Preta', '${stateIdRioGrandeSul}'),
        ('Portão', '${stateIdRioGrandeSul}'),
        ('Porto Alegre', '${stateIdRioGrandeSul}'),
        ('Porto Lucena', '${stateIdRioGrandeSul}'),
        ('Porto Mauá', '${stateIdRioGrandeSul}'),
        ('Porto Vera Cruz', '${stateIdRioGrandeSul}'),
        ('Porto Xavier', '${stateIdRioGrandeSul}'),
        ('Pouso Novo', '${stateIdRioGrandeSul}'),
        ('Presidente Lucena', '${stateIdRioGrandeSul}'),
        ('Progresso', '${stateIdRioGrandeSul}'),
        ('Protásio Alves', '${stateIdRioGrandeSul}'),
        ('Putinga', '${stateIdRioGrandeSul}'),
        ('Quaraí', '${stateIdRioGrandeSul}'),
        ('Quatro Irmãos', '${stateIdRioGrandeSul}'),
        ('Quevedos', '${stateIdRioGrandeSul}'),
        ('Quinze de Novembro', '${stateIdRioGrandeSul}'),
        ('Redentora', '${stateIdRioGrandeSul}'),
        ('Relvado', '${stateIdRioGrandeSul}'),
        ('Restinga Seca', '${stateIdRioGrandeSul}'),
        ('Rio dos Índios', '${stateIdRioGrandeSul}'),
        ('Rio Grande', '${stateIdRioGrandeSul}'),
        ('Rio Pardo', '${stateIdRioGrandeSul}'),
        ('Riozinho', '${stateIdRioGrandeSul}'),
        ('Roca Sales', '${stateIdRioGrandeSul}'),
        ('Rodeio Bonito', '${stateIdRioGrandeSul}'),
        ('Rolador', '${stateIdRioGrandeSul}'),
        ('Rolante', '${stateIdRioGrandeSul}'),
        ('Ronda Alta', '${stateIdRioGrandeSul}'),
        ('Rondinha', '${stateIdRioGrandeSul}'),
        ('Roque Gonzales', '${stateIdRioGrandeSul}'),
        ('Rosário do Sul', '${stateIdRioGrandeSul}'),
        ('Sagrada Família', '${stateIdRioGrandeSul}'),
        ('Saldanha Marinho', '${stateIdRioGrandeSul}'),
        ('Salto do Jacuí', '${stateIdRioGrandeSul}'),
        ('Salvador das Missões', '${stateIdRioGrandeSul}'),
        ('Salvador do Sul', '${stateIdRioGrandeSul}'),
        ('Sananduva', '${stateIdRioGrandeSul}'),
        ('Santa Bárbara do Sul', '${stateIdRioGrandeSul}'),
        ('Santa Cecília do Sul', '${stateIdRioGrandeSul}'),
        ('Santa Clara do Sul', '${stateIdRioGrandeSul}'),
        ('Santa Cruz do Sul', '${stateIdRioGrandeSul}'),
        ('Santa Margarida do Sul', '${stateIdRioGrandeSul}'),
        ('Santa Maria', '${stateIdRioGrandeSul}'),
        ('Santa Maria do Herval', '${stateIdRioGrandeSul}'),
        ('Santa Rosa', '${stateIdRioGrandeSul}'),
        ('Santa Tereza', '${stateIdRioGrandeSul}'),
        ('Santa Vitória do Palmar', '${stateIdRioGrandeSul}'),
        ('Santana da Boa Vista', '${stateIdRioGrandeSul}'),
        ('Santana do Livramento', '${stateIdRioGrandeSul}'),
        ('Santiago', '${stateIdRioGrandeSul}'),
        ('Santo Ângelo', '${stateIdRioGrandeSul}'),
        ('Santo Antônio da Patrulha', '${stateIdRioGrandeSul}'),
        ('Santo Antônio das Missões', '${stateIdRioGrandeSul}'),
        ('Santo Antônio do Palma', '${stateIdRioGrandeSul}'),
        ('Santo Antônio do Planalto', '${stateIdRioGrandeSul}'),
        ('Santo Augusto', '${stateIdRioGrandeSul}'),
        ('Santo Cristo', '${stateIdRioGrandeSul}'),
        ('Santo Expedito do Sul', '${stateIdRioGrandeSul}'),
        ('São Borja', '${stateIdRioGrandeSul}'),
        ('São Domingos do Sul', '${stateIdRioGrandeSul}'),
        ('São Francisco de Assis', '${stateIdRioGrandeSul}'),
        ('São Francisco de Paula', '${stateIdRioGrandeSul}'),
        ('São Gabriel', '${stateIdRioGrandeSul}'),
        ('São Jerônimo', '${stateIdRioGrandeSul}'),
        ('São João da Urtiga', '${stateIdRioGrandeSul}'),
        ('São João do Polêsine', '${stateIdRioGrandeSul}'),
        ('São Jorge', '${stateIdRioGrandeSul}'),
        ('São José das Missões', '${stateIdRioGrandeSul}'),
        ('São José do Herval', '${stateIdRioGrandeSul}'),
        ('São José do Hortêncio', '${stateIdRioGrandeSul}'),
        ('São José do Inhacorá', '${stateIdRioGrandeSul}'),
        ('São José do Norte', '${stateIdRioGrandeSul}'),
        ('São José do Ouro', '${stateIdRioGrandeSul}'),
        ('São José do Sul', '${stateIdRioGrandeSul}'),
        ('São José dos Ausentes', '${stateIdRioGrandeSul}'),
        ('São Leopoldo', '${stateIdRioGrandeSul}'),
        ('São Lourenço do Sul', '${stateIdRioGrandeSul}'),
        ('São Luiz Gonzaga', '${stateIdRioGrandeSul}'),
        ('São Marcos', '${stateIdRioGrandeSul}'),
        ('São Martinho', '${stateIdRioGrandeSul}'),
        ('São Martinho da Serra', '${stateIdRioGrandeSul}'),
        ('São Miguel das Missões', '${stateIdRioGrandeSul}'),
        ('São Nicolau', '${stateIdRioGrandeSul}'),
        ('São Paulo das Missões', '${stateIdRioGrandeSul}'),
        ('São Pedro da Serra', '${stateIdRioGrandeSul}'),
        ('São Pedro das Missões', '${stateIdRioGrandeSul}'),
        ('São Pedro do Butiá', '${stateIdRioGrandeSul}'),
        ('São Pedro do Sul', '${stateIdRioGrandeSul}'),
        ('São Sebastião do Caí', '${stateIdRioGrandeSul}'),
        ('São Sepé', '${stateIdRioGrandeSul}'),
        ('São Valentim', '${stateIdRioGrandeSul}'),
        ('São Valentim do Sul', '${stateIdRioGrandeSul}'),
        ('São Valério do Sul', '${stateIdRioGrandeSul}'),
        ('São Vendelino', '${stateIdRioGrandeSul}'),
        ('São Vicente do Sul', '${stateIdRioGrandeSul}'),
        ('Sapiranga', '${stateIdRioGrandeSul}'),
        ('Sapucaia do Sul', '${stateIdRioGrandeSul}'),
        ('Sarandi', '${stateIdRioGrandeSul}'),
        ('Seberi', '${stateIdRioGrandeSul}'),
        ('Sede Nova', '${stateIdRioGrandeSul}'),
        ('Segredo', '${stateIdRioGrandeSul}'),
        ('Selbach', '${stateIdRioGrandeSul}'),
        ('Senador Salgado Filho', '${stateIdRioGrandeSul}'),
        ('Sentinela do Sul', '${stateIdRioGrandeSul}'),
        ('Serafina Corrêa', '${stateIdRioGrandeSul}'),
        ('Sério', '${stateIdRioGrandeSul}'),
        ('Sertão', '${stateIdRioGrandeSul}'),
        ('Sertão Santana', '${stateIdRioGrandeSul}'),
        ('Sete de Setembro', '${stateIdRioGrandeSul}'),
        ('Severiano de Almeida', '${stateIdRioGrandeSul}'),
        ('Silveira Martins', '${stateIdRioGrandeSul}'),
        ('Sinimbu', '${stateIdRioGrandeSul}'),
        ('Sobradinho', '${stateIdRioGrandeSul}'),
        ('Soledade', '${stateIdRioGrandeSul}'),
        ('Tabaí', '${stateIdRioGrandeSul}'),
        ('Tapejara', '${stateIdRioGrandeSul}'),
        ('Tapera', '${stateIdRioGrandeSul}'),
        ('Tapes', '${stateIdRioGrandeSul}'),
        ('Taquara', '${stateIdRioGrandeSul}'),
        ('Taquari', '${stateIdRioGrandeSul}'),
        ('Taquaruçu do Sul', '${stateIdRioGrandeSul}'),
        ('Tavares', '${stateIdRioGrandeSul}'),
        ('Tenente Portela', '${stateIdRioGrandeSul}'),
        ('Terra de Areia', '${stateIdRioGrandeSul}'),
        ('Teutônia', '${stateIdRioGrandeSul}'),
        ('Tio Hugo', '${stateIdRioGrandeSul}'),
        ('Tiradentes do Sul', '${stateIdRioGrandeSul}'),
        ('Toropi', '${stateIdRioGrandeSul}'),
        ('Torres', '${stateIdRioGrandeSul}'),
        ('Tramandaí', '${stateIdRioGrandeSul}'),
        ('Travesseiro', '${stateIdRioGrandeSul}'),
        ('Três Arroios', '${stateIdRioGrandeSul}'),
        ('Três Cachoeiras', '${stateIdRioGrandeSul}'),
        ('Três Coroas', '${stateIdRioGrandeSul}'),
        ('Três de Maio', '${stateIdRioGrandeSul}'),
        ('Três Forquilhas', '${stateIdRioGrandeSul}'),
        ('Três Palmeiras', '${stateIdRioGrandeSul}'),
        ('Três Passos', '${stateIdRioGrandeSul}'),
        ('Trindade do Sul', '${stateIdRioGrandeSul}'),
        ('Triunfo', '${stateIdRioGrandeSul}'),
        ('Tucunduva', '${stateIdRioGrandeSul}'),
        ('Tunas', '${stateIdRioGrandeSul}'),
        ('Tupanci do Sul', '${stateIdRioGrandeSul}'),
        ('Tupanciretã', '${stateIdRioGrandeSul}'),
        ('Tupandi', '${stateIdRioGrandeSul}'),
        ('Tuparendi', '${stateIdRioGrandeSul}'),
        ('Turuçu', '${stateIdRioGrandeSul}'),
        ('Ubiretama', '${stateIdRioGrandeSul}'),
        ('União da Serra', '${stateIdRioGrandeSul}'),
        ('Unistalda', '${stateIdRioGrandeSul}'),
        ('Uruguaiana', '${stateIdRioGrandeSul}'),
        ('Vacaria', '${stateIdRioGrandeSul}'),
        ('Vale do Sol', '${stateIdRioGrandeSul}'),
        ('Vale Real', '${stateIdRioGrandeSul}'),
        ('Vale Verde', '${stateIdRioGrandeSul}'),
        ('Vanini', '${stateIdRioGrandeSul}'),
        ('Venâncio Aires', '${stateIdRioGrandeSul}'),
        ('Vera Cruz', '${stateIdRioGrandeSul}'),
        ('Veranópolis', '${stateIdRioGrandeSul}'),
        ('Vespasiano Correa', '${stateIdRioGrandeSul}'),
        ('Viadutos', '${stateIdRioGrandeSul}'),
        ('Viamão', '${stateIdRioGrandeSul}'),
        ('Vicente Dutra', '${stateIdRioGrandeSul}'),
        ('Victor Graeff', '${stateIdRioGrandeSul}'),
        ('Vila Flores', '${stateIdRioGrandeSul}'),
        ('Vila Lângaro', '${stateIdRioGrandeSul}'),
        ('Vila Maria', '${stateIdRioGrandeSul}'),
        ('Vila Nova do Sul', '${stateIdRioGrandeSul}'),
        ('Vista Alegre', '${stateIdRioGrandeSul}'),
        ('Vista Alegre do Prata', '${stateIdRioGrandeSul}'),
        ('Vista Gaúcha', '${stateIdRioGrandeSul}'),
        ('Vitória das Missões', '${stateIdRioGrandeSul}'),
        ('Westfália', '${stateIdRioGrandeSul}'),
        ('Xangri-lá', '${stateIdRioGrandeSul}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdRioGrandeSul = 'c2394216-c1dc-4d42-9fe1-1444e57ff9d9';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdRioGrandeSul}';
    `);
  }
}
