import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertCitiesForStateGoias1744427975730
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const stateIdGoias = 'a1f81c63-9c30-46f1-a4bb-f8b476eea010';

    await queryRunner.query(`
      INSERT INTO cities(name, state_id) VALUES
        ('Água Fria de Goiás', '${stateIdGoias}'),
        ('Águas Lindas de Goiás', '${stateIdGoias}'),
        ('Alexânia', '${stateIdGoias}'),
        ('Alto Horizonte', '${stateIdGoias}'),
        ('Alvorada do Norte', '${stateIdGoias}'),
        ('Amaralina', '${stateIdGoias}'),
        ('Americano do Brasil', '${stateIdGoias}'),
        ('Anápolis', '${stateIdGoias}'),
        ('Anhanguera', '${stateIdGoias}'),
        ('Aparecida de Goiânia', '${stateIdGoias}'),
        ('Aporé', '${stateIdGoias}'),
        ('Araguapaz', '${stateIdGoias}'),
        ('Araguari', '${stateIdGoias}'),
        ('Arenópolis', '${stateIdGoias}'),
        ('Aruanã', '${stateIdGoias}'),
        ('Aurilândia', '${stateIdGoias}'),
        ('Barro Alto', '${stateIdGoias}'),
        ('Bela Vista de Goiás', '${stateIdGoias}'),
        ('Bom Jesus de Goiás', '${stateIdGoias}'),
        ('Bonópolis', '${stateIdGoias}'),
        ('Brazabrantes', '${stateIdGoias}'),
        ('Buritinópolis', '${stateIdGoias}'),
        ('Caiapônia', '${stateIdGoias}'),
        ('Caldas Novas', '${stateIdGoias}'),
        ('Carmo do Rio Verde', '${stateIdGoias}'),
        ('Castelândia', '${stateIdGoias}'),
        ('Ceres', '${stateIdGoias}'),
        ('Cezarina', '${stateIdGoias}'),
        ('Chapadão do Céu', '${stateIdGoias}'),
        ('Cocalzinho de Goiás', '${stateIdGoias}'),
        ('Cristalina', '${stateIdGoias}'),
        ('Cromínia', '${stateIdGoias}'),
        ('Cumari', '${stateIdGoias}'),
        ('Damianópolis', '${stateIdGoias}'),
        ('Davinópolis', '${stateIdGoias}'),
        ('Diorama', '${stateIdGoias}'),
        ('Divinópolis de Goiás', '${stateIdGoias}'),
        ('Doverlândia', '${stateIdGoias}'),
        ('Edealina', '${stateIdGoias}'),
        ('Edéia', '${stateIdGoias}'),
        ('Fazenda Nova', '${stateIdGoias}'),
        ('Firminópolis', '${stateIdGoias}'),
        ('Flores de Goiás', '${stateIdGoias}'),
        ('Formosa', '${stateIdGoias}'),
        ('Formoso', '${stateIdGoias}'),
        ('Gameleira de Goiás', '${stateIdGoias}'),
        ('Goianápolis', '${stateIdGoias}'),
        ('Goiânia', '${stateIdGoias}'),
        ('Goianira', '${stateIdGoias}'),
        ('Goiás', '${stateIdGoias}'),
        ('Guapó', '${stateIdGoias}'),
        ('Guaraíta', '${stateIdGoias}'),
        ('Guarinos', '${stateIdGoias}'),
        ('Heitoraí', '${stateIdGoias}'),
        ('Hidrolândia', '${stateIdGoias}'),
        ('Hidrolina', '${stateIdGoias}'),
        ('Iaciara', '${stateIdGoias}'),
        ('Inhumas', '${stateIdGoias}'),
        ('Ipameri', '${stateIdGoias}'),
        ('Ipiranga de Goiás', '${stateIdGoias}'),
        ('Iporá', '${stateIdGoias}'),
        ('Israelândia', '${stateIdGoias}'),
        ('Itaberaí', '${stateIdGoias}'),
        ('Itaguari', '${stateIdGoias}'),
        ('Itaguaru', '${stateIdGoias}'),
        ('Itapuranga', '${stateIdGoias}'),
        ('Itaracu', '${stateIdGoias}'),
        ('Itauçu', '${stateIdGoias}'),
        ('Itumbiara', '${stateIdGoias}'),
        ('Ivolândia', '${stateIdGoias}'),
        ('Jandaia', '${stateIdGoias}'),
        ('Jaraguá', '${stateIdGoias}'),
        ('Jataí', '${stateIdGoias}'),
        ('Jaupaci', '${stateIdGoias}'),
        ('Jesúpolis', '${stateIdGoias}'),
        ('Joviânia', '${stateIdGoias}'),
        ('Jussara', '${stateIdGoias}'),
        ('Lagoa Santa', '${stateIdGoias}'),
        ('Leopoldo de Bulhões', '${stateIdGoias}'),
        ('Luziânia', '${stateIdGoias}'),
        ('Mairipotaba', '${stateIdGoias}'),
        ('Mambaí', '${stateIdGoias}'),
        ('Mara Rosa', '${stateIdGoias}'),
        ('Marzagão', '${stateIdGoias}'),
        ('Mimoso de Goiás', '${stateIdGoias}'),
        ('Minas Novas', '${stateIdGoias}'),
        ('Miranorte', '${stateIdGoias}'),
        ('Mundo Novo', '${stateIdGoias}'),
        ('Mutunópolis', '${stateIdGoias}'),
        ('Nazário', '${stateIdGoias}'),
        ('Nerópolis', '${stateIdGoias}'),
        ('Nova Crixás', '${stateIdGoias}'),
        ('Nova Glória', '${stateIdGoias}'),
        ('Nova Iguaçu de Goiás', '${stateIdGoias}'),
        ('Nova Roma', '${stateIdGoias}'),
        ('Novo Brasil', '${stateIdGoias}'),
        ('Novo Gama', '${stateIdGoias}'),
        ('Novo Planalto', '${stateIdGoias}'),
        ('Orizona', '${stateIdGoias}'),
        ('Ouro Verde de Goiás', '${stateIdGoias}'),
        ('Ouvidor', '${stateIdGoias}'),
        ('Padre Bernardo', '${stateIdGoias}'),
        ('Palmeiras de Goiás', '${stateIdGoias}'),
        ('Palme do Goiás', '${stateIdGoias}'),
        ('Panamá', '${stateIdGoias}'),
        ('Paranaiguara', '${stateIdGoias}'),
        ('Paraúna', '${stateIdGoias}'),
        ('Perolândia', '${stateIdGoias}'),
        ('Petrolina de Goiás', '${stateIdGoias}'),
        ('Pilar de Goiás', '${stateIdGoias}'),
        ('Piracanjuba', '${stateIdGoias}'),
        ('Pirenópolis', '${stateIdGoias}'),
        ('Pires do Rio', '${stateIdGoias}'),
        ('Planaltina', '${stateIdGoias}'),
        ('Pontalina', '${stateIdGoias}'),
        ('Porangatu', '${stateIdGoias}'),
        ('Posse', '${stateIdGoias}'),
        ('Professor Jamil', '${stateIdGoias}'),
        ('Quirinópolis', '${stateIdGoias}'),
        ('Rialma', '${stateIdGoias}'),
        ('Rianápolis', '${stateIdGoias}'),
        ('Rio Quente', '${stateIdGoias}'),
        ('Rio Verde', '${stateIdGoias}'),
        ('Rubiataba', '${stateIdGoias}'),
        ('Sanclerlândia', '${stateIdGoias}'),
        ('Santa Bárbara de Goiás', '${stateIdGoias}'),
        ('Santa Cruz de Goiás', '${stateIdGoias}'),
        ('Santa Helena de Goiás', '${stateIdGoias}'),
        ('Santa Isabel', '${stateIdGoias}'),
        ('Santa Rita do Novo Destino', '${stateIdGoias}'),
        ('Santa Rosa de Goiás', '${stateIdGoias}'),
        ('Santa Tereza de Goiás', '${stateIdGoias}'),
        ('Santo Antônio do Descoberto', '${stateIdGoias}'),
        ('São Domingos', '${stateIdGoias}'),
        ('São João d\`Aliança', '${stateIdGoias}'),
        ('São João da Paraúna', '${stateIdGoias}'),
        ('São Luís de Montes Belos', '${stateIdGoias}'),
        ('São Luíz do Norte', '${stateIdGoias}'),
        ('São Miguel do Araguaia', '${stateIdGoias}'),
        ('São Simão', '${stateIdGoias}'),
        ('Senador Canedo', '${stateIdGoias}'),
        ('Serranópolis', '${stateIdGoias}'),
        ('Silvânia', '${stateIdGoias}'),
        ('Simolândia', '${stateIdGoias}'),
        ('Sousana', '${stateIdGoias}'),
        ('Spanholândia', '${stateIdGoias}'),
        ('Vianópolis', '${stateIdGoias}'),
        ('Vicentinópolis', '${stateIdGoias}'),
        ('Vila Boa', '${stateIdGoias}'),
        ('Vila Propício', '${stateIdGoias}');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const stateIdGoias = 'a1f81c63-9c30-46f1-a4bb-f8b476eea010';

    await queryRunner.query(`
      DELETE FROM cities WHERE state_id = '${stateIdGoias}';
    `);
  }
}
